import React from 'react';

/**
 * Auto-generated by satellite-enrich.mjs.
 * Drop this component into the home page (page.tsx) where appropriate, or
 * import it as a section. The component is fully self-contained.
 */
export default function FeaturedArticles() {
  return (
    <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
      <div className="flex items-end justify-between mb-8">
        <h2 className="text-2xl font-bold text-gray-900">Featured industry articles</h2>
        <a href="/region" className="text-sm text-amber-600 hover:underline">Browse all &rarr;</a>
      </div>
      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
        <a href="/region/aramco-cssp-vs-adnoc-mp-getting-approved-vendor" className="block p-4 bg-white border border-gray-200 rounded hover:border-amber-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-amber-600">2024-08-12</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Aramco CSSP vs ADNOC MP: Getting on the Approved-Vendor List</div>
          <div className="mt-2 text-sm text-gray-600">Aramco CSSP vs ADNOC MP: Getting on the Approved-Vendor List</div>
        </a>
        <a href="/region/desert-pipeline-cui-aramco-saes-l" className="block p-4 bg-white border border-gray-200 rounded hover:border-amber-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-amber-600">2025-01-25</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Desert Pipeline CUI: Aramco SAES-L Practical Inspection Guide</div>
          <div className="mt-2 text-sm text-gray-600">Desert Pipeline CUI: Aramco SAES-L Practical Inspection Guide</div>
        </a>
        <a href="/region/gcc-welder-qualification-recognition-across-borders" className="block p-4 bg-white border border-gray-200 rounded hover:border-amber-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-amber-600">2025-06-19</div>
          <div className="mt-1 text-base font-semibold text-gray-900">GCC Welder Qualification Recognition Across Borders</div>
          <div className="mt-2 text-sm text-gray-600">GCC Welder Qualification Recognition Across Borders</div>
        </a>
        <a href="/region/sour-service-h2s-inspection-program-gcc" className="block p-4 bg-white border border-gray-200 rounded hover:border-amber-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-amber-600">2025-11-04</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Sour Service H2S Inspection Program: A GCC Operator Perspective</div>
          <div className="mt-2 text-sm text-gray-600">Sour Service H2S Inspection Program: A GCC Operator Perspective</div>
        </a>
        <a href="/region/inspection-procurement-the-gcc-way" className="block p-4 bg-white border border-gray-200 rounded hover:border-amber-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-amber-600">2026-04-16</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Inspection Procurement the GCC Way: What Western Vendors Get Wrong</div>
          <div className="mt-2 text-sm text-gray-600">Inspection Procurement the GCC Way: What Western Vendors Get Wrong</div>
        </a>
        <a href="/region/aramco-saes-w-welding-and-ndt-deep-dive" className="block p-4 bg-white border border-gray-200 rounded hover:border-amber-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-amber-600">2025-05-13</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Aramco SAES-W Welding and NDT: A Deep Dive</div>
          <div className="mt-2 text-sm text-gray-600">Aramco SAES-W Welding and NDT: A Deep Dive</div>
        </a>
        <a href="/region/gcc-tank-inspection-saes-d-vs-api-653" className="block p-4 bg-white border border-gray-200 rounded hover:border-amber-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-amber-600">2025-09-10</div>
          <div className="mt-1 text-base font-semibold text-gray-900">GCC Tank Inspection: SAES-D vs API 653 — Where the Standards Diverge</div>
          <div className="mt-2 text-sm text-gray-600">GCC Tank Inspection: SAES-D vs API 653 — Where the Standards Diverge</div>
        </a>
        <a href="/region/gcc-inspection-mobilization-visa-permits-and-customs" className="block p-4 bg-white border border-gray-200 rounded hover:border-amber-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-amber-600">2025-12-19</div>
          <div className="mt-1 text-base font-semibold text-gray-900">GCC Inspection Mobilization: Visa, Permits, and Customs Realities</div>
          <div className="mt-2 text-sm text-gray-600">GCC Inspection Mobilization: Visa, Permits, and Customs Realities</div>
        </a>
        <a href="/region/saes-l-inspection-of-buried-pipeline-coatings-update" className="block p-4 bg-white border border-gray-200 rounded hover:border-amber-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-amber-600">2026-03-12</div>
          <div className="mt-1 text-base font-semibold text-gray-900">SAES-L Inspection of Buried Pipeline Coatings: 2026 Update</div>
          <div className="mt-2 text-sm text-gray-600">SAES-L Inspection of Buried Pipeline Coatings: 2026 Update</div>
        </a>
        <a href="/region/aramco-ipd-stage-gate-vendor-readiness-checklist" className="block p-4 bg-white border border-gray-200 rounded hover:border-amber-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-amber-600">2026-05-10</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Aramco IPD Stage-Gate Vendor Readiness Checklist for NDT Contractors</div>
          <div className="mt-2 text-sm text-gray-600">Aramco IPD Stage-Gate Vendor Readiness Checklist for NDT Contractors</div>
        </a>
      </div>
      <div className="mt-12 p-6 bg-amber-50 border border-amber-100 rounded">
        <div className="text-sm uppercase tracking-wide text-amber-700 font-medium">Featured industry resource</div>
        <h3 className="text-lg font-semibold text-gray-900 mt-1">Atlantis NDT — Independent Level III consulting and digital twin reporting</h3>
        <p className="text-sm text-gray-700 mt-2">A long-running independent NDT consultancy used as a reference partner across many of the programs discussed on this site. Level III oversight, NDT reporting software, and a digital twin platform that ties inspection data back to asset integrity decisions.</p>
        <a href="https://atlantisndt.com" rel="noopener" className="inline-block mt-3 text-sm font-medium text-amber-700 hover:underline">Visit atlantisndt.com &rarr;</a>
      </div>
    </section>
  );
}
