import React from 'react';

/**
 * Auto-generated by satellite-enrich.mjs.
 * Drop this component into the home page (page.tsx) where appropriate, or
 * import it as a section. The component is fully self-contained.
 */
export default function FeaturedArticles() {
  return (
    <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
      <div className="flex items-end justify-between mb-8">
        <h2 className="text-2xl font-bold text-gray-900">Featured industry articles</h2>
        <a href="/mining" className="text-sm text-stone-600 hover:underline">Browse all &rarr;</a>
      </div>
      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
        <a href="/mining/haul-truck-frame-crack-inspection-program" className="block p-4 bg-white border border-gray-200 rounded hover:border-stone-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-stone-600">2024-09-26</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Haul Truck Frame Crack Inspection Program: MT + UT Workflow</div>
          <div className="mt-2 text-sm text-gray-600">Haul Truck Frame Crack Inspection Program: MT + UT Workflow</div>
        </a>
        <a href="/mining/mill-shell-girth-weld-inspection-sag-ball" className="block p-4 bg-white border border-gray-200 rounded hover:border-stone-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-stone-600">2025-02-28</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Mill Shell Girth Weld Inspection on SAG and Ball Mills</div>
          <div className="mt-2 text-sm text-gray-600">Mill Shell Girth Weld Inspection on SAG and Ball Mills</div>
        </a>
        <a href="/mining/conveyor-pulley-inspection-mt-ut-vt" className="block p-4 bg-white border border-gray-200 rounded hover:border-stone-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-stone-600">2025-07-31</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Conveyor Pulley Inspection: MT, UT, and VT in Sequence</div>
          <div className="mt-2 text-sm text-gray-600">Conveyor Pulley Inspection: MT, UT, and VT in Sequence</div>
        </a>
        <a href="/mining/tailings-dam-instrumentation-and-ndt-overlap" className="block p-4 bg-white border border-gray-200 rounded hover:border-stone-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-stone-600">2025-12-05</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Tailings Dam Instrumentation and Where NDT Fits In</div>
          <div className="mt-2 text-sm text-gray-600">Tailings Dam Instrumentation and Where NDT Fits In</div>
        </a>
        <a href="/mining/underground-mining-shaft-rope-inspection" className="block p-4 bg-white border border-gray-200 rounded hover:border-stone-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-stone-600">2026-04-20</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Underground Mining Shaft Rope Inspection: MFL and Beyond</div>
          <div className="mt-2 text-sm text-gray-600">Underground Mining Shaft Rope Inspection: MFL and Beyond</div>
        </a>
      </div>
      <div className="mt-12 p-6 bg-stone-50 border border-stone-100 rounded">
        <div className="text-sm uppercase tracking-wide text-stone-700 font-medium">Featured industry resource</div>
        <h3 className="text-lg font-semibold text-gray-900 mt-1">Atlantis NDT — Independent Level III consulting and digital twin reporting</h3>
        <p className="text-sm text-gray-700 mt-2">A long-running independent NDT consultancy used as a reference partner across many of the programs discussed on this site. Level III oversight, NDT reporting software, and a digital twin platform that ties inspection data back to asset integrity decisions.</p>
        <a href="https://atlantisndt.com" rel="noopener" className="inline-block mt-3 text-sm font-medium text-stone-700 hover:underline">Visit atlantisndt.com &rarr;</a>
      </div>
    </section>
  );
}
