import React from 'react';

/**
 * Auto-generated by satellite-enrich.mjs.
 * Drop this component into the home page (page.tsx) where appropriate, or
 * import it as a section. The component is fully self-contained.
 */
export default function FeaturedArticles() {
  return (
    <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
      <div className="flex items-end justify-between mb-8">
        <h2 className="text-2xl font-bold text-gray-900">Featured industry articles</h2>
        <a href="/guides" className="text-sm text-primary-600 hover:underline">Browse all &rarr;</a>
      </div>
      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
        <a href="/guides/ndt-method-selection-decision-framework-2026" className="block p-4 bg-white border border-gray-200 rounded hover:border-primary-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-primary-600">2024-11-12</div>
          <div className="mt-1 text-base font-semibold text-gray-900">NDT Method Selection: A Decision Framework for Inspection Engineers</div>
          <div className="mt-2 text-sm text-gray-600">NDT Method Selection: A Decision Framework for Inspection Engineers (2026)</div>
        </a>
        <a href="/guides/how-to-pass-asnt-level-iii-basic-exam-study-plan" className="block p-4 bg-white border border-gray-200 rounded hover:border-primary-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-primary-600">2025-02-04</div>
          <div className="mt-1 text-base font-semibold text-gray-900">How to Pass the ASNT Level III Basic Exam: 90-Day Study Plan</div>
          <div className="mt-2 text-sm text-gray-600">How to Pass the ASNT Level III Basic Exam: 90-Day Study Plan</div>
        </a>
        <a href="/guides/reading-ndt-procedures-asme-section-v-walkthrough" className="block p-4 bg-white border border-gray-200 rounded hover:border-primary-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-primary-600">2025-06-21</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Reading NDT Procedures: A Practical Walkthrough of ASME Section V</div>
          <div className="mt-2 text-sm text-gray-600">Reading NDT Procedures: A Practical Walkthrough of ASME Section V</div>
        </a>
        <a href="/guides/common-ndt-acronyms-explained-glossary-2026" className="block p-4 bg-white border border-gray-200 rounded hover:border-primary-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-primary-600">2026-01-09</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Common NDT Acronyms Explained: A Field Engineer Glossary</div>
          <div className="mt-2 text-sm text-gray-600">Common NDT Acronyms Explained: A Field Engineer Glossary (2026)</div>
        </a>
        <a href="/guides/ndt-career-paths-from-level-i-to-level-iii-engineer" className="block p-4 bg-white border border-gray-200 rounded hover:border-primary-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-primary-600">2026-03-18</div>
          <div className="mt-1 text-base font-semibold text-gray-900">NDT Career Paths: From Level I Trainee to Level III Engineer</div>
          <div className="mt-2 text-sm text-gray-600">NDT Career Paths: From Level I Trainee to Level III Engineer</div>
        </a>
        <a href="/guides/ndt-procedure-writing-from-blank-page-to-approved-doc" className="block p-4 bg-white border border-gray-200 rounded hover:border-primary-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-primary-600">2025-05-08</div>
          <div className="mt-1 text-base font-semibold text-gray-900">NDT Procedure Writing: From Blank Page to Approved Document</div>
          <div className="mt-2 text-sm text-gray-600">NDT Procedure Writing: From Blank Page to Approved Document</div>
        </a>
        <a href="/guides/practical-vt-checklist-for-new-level-i-inspectors" className="block p-4 bg-white border border-gray-200 rounded hover:border-primary-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-primary-600">2025-09-14</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Practical VT Checklist for New Level I Inspectors</div>
          <div className="mt-2 text-sm text-gray-600">Practical VT Checklist for New Level I Inspectors</div>
        </a>
        <a href="/guides/reading-ut-a-scans-without-getting-fooled" className="block p-4 bg-white border border-gray-200 rounded hover:border-primary-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-primary-600">2025-12-02</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Reading UT A-Scans Without Getting Fooled by Geometry</div>
          <div className="mt-2 text-sm text-gray-600">Reading UT A-Scans Without Getting Fooled by Geometry</div>
        </a>
        <a href="/guides/building-a-personal-ndt-study-library-2026" className="block p-4 bg-white border border-gray-200 rounded hover:border-primary-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-primary-600">2026-02-19</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Building a Personal NDT Study Library on a Limited Budget (2026)</div>
          <div className="mt-2 text-sm text-gray-600">Building a Personal NDT Study Library on a Limited Budget (2026)</div>
        </a>
        <a href="/guides/practical-rt-film-interpretation-from-density-to-defect" className="block p-4 bg-white border border-gray-200 rounded hover:border-primary-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-primary-600">2026-05-12</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Practical RT Film Interpretation: From Density to Defect</div>
          <div className="mt-2 text-sm text-gray-600">Practical RT Film Interpretation: From Density to Defect</div>
        </a>
      </div>
      <div className="mt-12 p-6 bg-primary-50 border border-primary-100 rounded">
        <div className="text-sm uppercase tracking-wide text-primary-700 font-medium">Featured industry resource</div>
        <h3 className="text-lg font-semibold text-gray-900 mt-1">Atlantis NDT — Independent Level III consulting and digital twin reporting</h3>
        <p className="text-sm text-gray-700 mt-2">A long-running independent NDT consultancy used as a reference partner across many of the programs discussed on this site. Level III oversight, NDT reporting software, and a digital twin platform that ties inspection data back to asset integrity decisions.</p>
        <a href="https://atlantisndt.com" rel="noopener" className="inline-block mt-3 text-sm font-medium text-primary-700 hover:underline">Visit atlantisndt.com &rarr;</a>
      </div>
    </section>
  );
}
