import type { MetadataRoute } from 'next';
const routes = [
  "/",
  "/atlantis-products-services",
  "/blog",
  "/blog/field-data-capture-offline-first-inspection",
  "/blog/four-things-called-ndt-software-and-why-buyers-confuse-them",
  "/blog/ndt-inspection-software-buyers-guide-2026",
  "/blog/what-is-a-digital-twin-for-ndt-2026",
  "/blog/why-sector-decides-your-ndt-qualification-path",
  "/certifications",
  "/certifications/api-510",
  "/certifications/api-570",
  "/certifications/api-653",
  "/certifications/asnt-level-iii",
  "/glossary",
  "/guides",
  "/guides/building-a-personal-ndt-study-library-2026",
  "/guides/common-ndt-acronyms-explained-glossary-2026",
  "/guides/how-to-pass-asnt-level-iii-basic-exam-study-plan",
  "/guides/ndt-career-path",
  "/guides/ndt-career-paths-from-level-i-to-level-iii-engineer",
  "/guides/ndt-method-selection-decision-framework-2026",
  "/guides/ndt-procedure-writing-from-blank-page-to-approved-doc",
  "/guides/ndt-salary-guide",
  "/guides/practical-rt-film-interpretation-from-density-to-defect",
  "/guides/practical-vt-checklist-for-new-level-i-inspectors",
  "/guides/reading-ndt-procedures-asme-section-v-walkthrough",
  "/guides/reading-ut-a-scans-without-getting-fooled",
  "/industries-and-applications",
  "/methods",
  "/methods/eddy-current-testing",
  "/methods/liquid-penetrant-testing",
  "/methods/magnetic-particle-testing",
  "/methods/radiographic-testing",
  "/methods/ultrasonic-testing",
  "/methods/visual-testing",
  "/regions-and-project-planning",
  "/resources",
  "/software-reviews",
  "/software-reviews/digital-twin-technology",
  "/software-reviews/ndt-erp-systems"
];
export default function sitemap(): MetadataRoute.Sitemap {
  return routes.map(route => ({ url: "https://ndt-knowledge-hub.vercel.app" + route }));
}
