import type { VercelRequest, VercelResponse } from '@vercel/node';

interface Blog {
  id: string;
  title: string;
  slug: string;
  date: string;
  snippet: string;
  content: string;
  metaDescription?: string;
  author?: string;
  order: number;
  createdAt: string;
  updatedAt: string;
}

// In-memory storage (temporary solution - will reset on each deployment)
// For production, you should use Vercel KV, Supabase, or another database
let blogsCache: Blog[] = [
  {
    id: '1',
    title: 'Understanding Ultrasonic Testing in NDT',
    slug: 'ultrasonic-testing',
    date: 'October 1, 2025',
    snippet: 'Explore how ultrasonic testing helps detect internal flaws in materials without causing damage.',
    content: `<h2>Understanding Ultrasonic Testing in NDT</h2>
<p>Ultrasonic testing is a non-destructive testing method that uses high-frequency sound waves to detect internal defects in materials.</p>
<h3>How It Works</h3>
<p>Ultrasonic waves are transmitted through the material being tested. When these waves encounter a defect or boundary, they are reflected back to the receiver. By analyzing the reflected signals, inspectors can determine the size, location, and nature of defects.</p>
<h3>Applications</h3>
<ul>
<li>Detecting cracks in metals</li>
<li>Measuring material thickness</li>
<li>Inspecting welds</li>
<li>Finding voids and inclusions</li>
</ul>
<h3>Advantages</h3>
<p>Ultrasonic testing offers excellent penetration, quick results, and can be applied to thick materials. It's also safe and doesn't require radiation.</p>`,
    author: 'Atlantis NDT',
    order: 1,
    createdAt: '2025-10-01',
    updatedAt: '2025-10-01'
  },
  {
    id: '2',
    title: 'Magnetic Particle Testing: Best Practices',
    slug: 'magnetic-particle-testing',
    date: 'October 3, 2025',
    snippet: 'Learn how magnetic particle testing detects surface and near-surface defects efficiently.',
    content: `<h2>Magnetic Particle Testing: Best Practices</h2>
<p>Magnetic particle testing (MPT) is a non-destructive method used to detect surface and near-surface defects in ferromagnetic materials.</p>
<h3>Principle</h3>
<p>When a ferromagnetic material is magnetized, surface and near-surface defects create disturbances in the magnetic field. Iron particles, when applied to the magnetized surface, accumulate at these defect areas, making them visible.</p>
<h3>Best Practices</h3>
<ul>
<li>Ensure proper surface preparation</li>
<li>Use appropriate magnetic field strength</li>
<li>Apply particles correctly</li>
<li>Maintain proper lighting for inspection</li>
<li>Document all findings</li>
</ul>
<h3>Limitations</h3>
<p>MPT only works on ferromagnetic materials and has limited penetration for subsurface defects. However, it's excellent for detecting surface discontinuities.</p>`,
    author: 'Atlantis NDT',
    order: 2,
    createdAt: '2025-10-03',
    updatedAt: '2025-10-03'
  },
  {
    id: '3',
    title: 'Visual Testing Techniques for Modern NDT',
    slug: 'visual-testing',
    date: 'October 5, 2025',
    snippet: 'A guide to direct and remote visual inspection methods for industrial assets.',
    content: `<h2>Visual Testing Techniques for Modern NDT</h2>
<p>Visual testing is the most widely used non-destructive testing method. It includes both direct visual inspection and remote visual inspection.</p>
<h3>Direct Visual Inspection</h3>
<p>The inspector directly observes the component using natural or artificial lighting. This method is simple and requires minimal equipment.</p>
<h3>Remote Visual Inspection (RVI)</h3>
<p>RVI employs cameras, endoscopes, and borescopes to inspect areas that are not directly accessible. This is useful in confined spaces and hazardous environments.</p>
<h3>Modern Tools</h3>
<ul>
<li>High-resolution cameras</li>
<li>Thermal imaging</li>
<li>Fiber optics</li>
<li>Digital documentation</li>
</ul>`,
    author: 'Atlantis NDT',
    order: 3,
    createdAt: '2025-10-05',
    updatedAt: '2025-10-05'
  },
  {
    id: '4',
    title: 'Radiographic Testing in Industrial Applications',
    slug: 'radiographic-testing',
    date: 'October 7, 2025',
    snippet: 'Understand X-ray and gamma ray techniques for internal flaw detection and weld inspections.',
    content: `<h2>Radiographic Testing in Industrial Applications</h2>
<p>Radiographic testing uses X-rays or gamma rays to create images of components, revealing internal defects and material variations.</p>
<h3>X-Ray Radiography</h3>
<p>X-rays are generated by equipment and provide good control over parameters. They're ideal for portable applications.</p>
<h3>Gamma Ray Radiography</h3>
<p>Gamma rays are emitted by radioactive sources like Iridium-192. They're excellent for field work but require strict safety protocols.</p>
<h3>Applications</h3>
<ul>
<li>Weld inspections</li>
<li>Casting quality control</li>
<li>Foreign object detection</li>
<li>Corrosion assessment</li>
</ul>`,
    author: 'Atlantis NDT',
    order: 4,
    createdAt: '2025-10-07',
    updatedAt: '2025-10-07'
  },
  {
    id: '5',
    title: 'Eddy Current Testing Explained',
    slug: 'eddy-current-testing',
    date: 'October 10, 2025',
    snippet: 'An introduction to eddy current testing and its applications in quality control.',
    content: `<h2>Eddy Current Testing Explained</h2>
<p>Eddy current testing is an electromagnetic method for detecting surface and near-surface defects in conductive materials.</p>
<h3>How It Works</h3>
<p>An alternating current through a coil creates an alternating magnetic field. When placed near a conductive material, this induces eddy currents in the material. Defects disrupt these currents, and the changes are detected by the probe.</p>
<h3>Advantages</h3>
<ul>
<li>Rapid inspection speed</li>
<li>Excellent for thin materials</li>
<li>Can detect very small defects</li>
<li>Non-contact method</li>
</ul>
<h3>Applications</h3>
<ul>
<li>Detecting cracks in aircraft components</li>
<li>Heat exchanger tube inspection</li>
<li>Quality control in manufacturing</li>
</ul>`,
    author: 'Atlantis NDT',
    order: 5,
    createdAt: '2025-10-10',
    updatedAt: '2025-10-10'
  },
  {
    id: '6',
    title: 'Penetrant Testing: Detecting Surface Defects',
    slug: 'penetrant-testing',
    date: 'October 12, 2025',
    snippet: 'A deep dive into liquid penetrant testing and its role in non-destructive inspections.',
    content: `<h2>Penetrant Testing: Detecting Surface Defects</h2>
<p>Penetrant testing, also known as liquid penetrant testing (LPT), is a non-destructive method for detecting surface-breaking defects in non-porous materials.</p>
<h3>Process</h3>
<p>A low-viscosity liquid penetrant is applied to the clean surface of the component. The penetrant enters surface-breaking discontinuities through capillary action. After removal of excess penetrant, a developer is applied to draw the penetrant out of defects, making them visible.</p>
<h3>Types of Penetrants</h3>
<ul>
<li>Fluorescent penetrants</li>
<li>Red dye penetrants</li>
<li>Visible dye penetrants</li>
</ul>
<h3>Best For</h3>
<ul>
<li>Detecting cracks</li>
<li>Finding porosity</li>
<li>Identifying sealing surface defects</li>
<li>Quality assurance</li>
</ul>`,
    author: 'Atlantis NDT',
    order: 6,
    createdAt: '2025-10-12',
    updatedAt: '2025-10-12'
  }
];

export default async function handler(req: VercelRequest, res: VercelResponse) {
  // Enable CORS
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  try {
    // GET /api/blogs - Get all blogs
    if (req.method === 'GET') {
      return res.status(200).json(blogsCache.sort((a, b) => a.order - b.order));
    }

    // POST /api/blogs - Create new blog
    if (req.method === 'POST') {
      const { title, slug, date, snippet, content, metaDescription, author, order } = req.body;

      // Validate required fields
      if (!title || !slug || !content) {
        return res.status(400).json({ error: 'Missing required fields: title, slug, content' });
      }

      // Check for duplicate slug
      if (blogsCache.some(blog => blog.slug === slug)) {
        return res.status(400).json({ error: 'Blog with this slug already exists' });
      }

      const newBlog: Blog = {
        id: Date.now().toString(),
        title,
        slug,
        date: date || new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }),
        snippet: snippet || '',
        content,
        metaDescription,
        author: author || 'Atlantis NDT',
        order: order || (blogsCache.length > 0 ? Math.max(...blogsCache.map(b => b.order)) + 1 : 1),
        createdAt: new Date().toISOString().split('T')[0],
        updatedAt: new Date().toISOString().split('T')[0],
      };

      blogsCache.push(newBlog);

      return res.status(201).json(newBlog);
    }

    // PUT /api/blogs - Update blog
    if (req.method === 'PUT') {
      const { id, title, slug, date, snippet, content, metaDescription, author, order } = req.body;

      if (!id) {
        return res.status(400).json({ error: 'Blog ID is required' });
      }

      const index = blogsCache.findIndex(blog => blog.id === id);
      if (index === -1) {
        return res.status(404).json({ error: 'Blog not found' });
      }

      // Check for duplicate slug (excluding current blog)
      if (slug && blogsCache.some(blog => blog.slug === slug && blog.id !== id)) {
        return res.status(400).json({ error: 'Blog with this slug already exists' });
      }

      const updatedBlog: Blog = {
        ...blogsCache[index],
        title: title || blogsCache[index].title,
        slug: slug || blogsCache[index].slug,
        date: date || blogsCache[index].date,
        snippet: snippet !== undefined ? snippet : blogsCache[index].snippet,
        content: content || blogsCache[index].content,
        metaDescription: metaDescription !== undefined ? metaDescription : blogsCache[index].metaDescription,
        author: author !== undefined ? author : blogsCache[index].author,
        order: order !== undefined ? order : blogsCache[index].order,
        updatedAt: new Date().toISOString().split('T')[0],
      };

      blogsCache[index] = updatedBlog;

      return res.status(200).json(updatedBlog);
    }

    // DELETE /api/blogs - Delete blog
    if (req.method === 'DELETE') {
      const { id } = req.query;

      if (!id || typeof id !== 'string') {
        return res.status(400).json({ error: 'Blog ID is required' });
      }

      const initialLength = blogsCache.length;
      blogsCache = blogsCache.filter(blog => blog.id !== id);

      if (blogsCache.length === initialLength) {
        return res.status(404).json({ error: 'Blog not found' });
      }

      return res.status(200).json({ message: 'Blog deleted successfully' });
    }

    return res.status(405).json({ error: 'Method not allowed' });
  } catch (error) {
    console.error('API Error:', error);
    return res.status(500).json({ error: 'Internal server error', details: error instanceof Error ? error.message : 'Unknown error' });
  }
}
