import React from 'react';

/**
 * Auto-generated by satellite-enrich.mjs.
 * Drop this component into the home page (page.tsx) where appropriate, or
 * import it as a section. The component is fully self-contained.
 */
export default function FeaturedArticles() {
  return (
    <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
      <div className="flex items-end justify-between mb-8">
        <h2 className="text-2xl font-bold text-gray-900">Featured industry articles</h2>
        <a href="/library" className="text-sm text-gray-600 hover:underline">Browse all &rarr;</a>
      </div>
      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
        <a href="/library/asme-section-v-2025-edition-changes" className="block p-4 bg-white border border-gray-200 rounded hover:border-gray-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-gray-600">2024-08-26</div>
          <div className="mt-1 text-base font-semibold text-gray-900">ASME Section V 2025 Edition: What Changed and What It Means</div>
          <div className="mt-2 text-sm text-gray-600">ASME Section V 2025 Edition: What Changed and What It Means</div>
        </a>
        <a href="/library/iso-9712-vs-en-iso-vs-asnt-cross-recognition" className="block p-4 bg-white border border-gray-200 rounded hover:border-gray-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-gray-600">2025-01-31</div>
          <div className="mt-1 text-base font-semibold text-gray-900">ISO 9712 vs EN-ISO vs ASNT: Cross-Recognition Realities</div>
          <div className="mt-2 text-sm text-gray-600">ISO 9712 vs EN-ISO vs ASNT: Cross-Recognition Realities</div>
        </a>
        <a href="/library/choosing-the-right-pipe-code-asme-b31-1-vs-b31-3-vs-b31-8" className="block p-4 bg-white border border-gray-200 rounded hover:border-gray-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-gray-600">2025-06-12</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Choosing the Right Pipe Code: ASME B31.1 vs B31.3 vs B31.8</div>
          <div className="mt-2 text-sm text-gray-600">Choosing the Right Pipe Code: ASME B31.1 vs B31.3 vs B31.8</div>
        </a>
        <a href="/library/aws-d1-1-vs-aws-d1-5-vs-aws-d1-6-pick-the-correct-code" className="block p-4 bg-white border border-gray-200 rounded hover:border-gray-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-gray-600">2025-10-22</div>
          <div className="mt-1 text-base font-semibold text-gray-900">AWS D1.1 vs D1.5 vs D1.6: Pick the Correct Welding Code</div>
          <div className="mt-2 text-sm text-gray-600">AWS D1.1 vs D1.5 vs D1.6: Pick the Correct Welding Code</div>
        </a>
        <a href="/library/api-vs-asme-vs-iso-pressure-equipment-rules-quick-map" className="block p-4 bg-white border border-gray-200 rounded hover:border-gray-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-gray-600">2026-03-22</div>
          <div className="mt-1 text-base font-semibold text-gray-900">API vs ASME vs ISO Pressure-Equipment Rules: A Quick Map</div>
          <div className="mt-2 text-sm text-gray-600">API vs ASME vs ISO Pressure-Equipment Rules: A Quick Map</div>
        </a>
        <a href="/library/asme-bpvc-section-ix-welding-requirements-walkthrough" className="block p-4 bg-white border border-gray-200 rounded hover:border-gray-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-gray-600">2025-05-23</div>
          <div className="mt-1 text-base font-semibold text-gray-900">ASME BPVC Section IX Welding Requirements: A Practical Walkthrough</div>
          <div className="mt-2 text-sm text-gray-600">ASME BPVC Section IX Welding Requirements: A Practical Walkthrough</div>
        </a>
        <a href="/library/astm-e2375-bulk-ultrasonic-examination-of-pipe" className="block p-4 bg-white border border-gray-200 rounded hover:border-gray-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-gray-600">2025-09-26</div>
          <div className="mt-1 text-base font-semibold text-gray-900">ASTM E2375: Bulk Ultrasonic Examination of Pipe — How to Use It</div>
          <div className="mt-2 text-sm text-gray-600">ASTM E2375: Bulk Ultrasonic Examination of Pipe — How to Use It</div>
        </a>
        <a href="/library/asme-section-viii-div-2-vs-div-1-ndt-comparison" className="block p-4 bg-white border border-gray-200 rounded hover:border-gray-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-gray-600">2025-12-23</div>
          <div className="mt-1 text-base font-semibold text-gray-900">ASME Section VIII Div 2 vs Div 1: NDT Comparison</div>
          <div className="mt-2 text-sm text-gray-600">ASME Section VIII Div 2 vs Div 1: NDT Comparison</div>
        </a>
        <a href="/library/iso-17640-vs-en-iso-17640-piping-paut" className="block p-4 bg-white border border-gray-200 rounded hover:border-gray-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-gray-600">2026-03-21</div>
          <div className="mt-1 text-base font-semibold text-gray-900">ISO 17640 vs EN ISO 17640 for Piping PAUT: What Actually Differs</div>
          <div className="mt-2 text-sm text-gray-600">ISO 17640 vs EN ISO 17640 for Piping PAUT: What Actually Differs</div>
        </a>
        <a href="/library/european-pressure-equipment-directive-ped-ndt-rules" className="block p-4 bg-white border border-gray-200 rounded hover:border-gray-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-gray-600">2026-05-06</div>
          <div className="mt-1 text-base font-semibold text-gray-900">European Pressure Equipment Directive (PED) NDT Rules in Plain Words</div>
          <div className="mt-2 text-sm text-gray-600">European Pressure Equipment Directive (PED) NDT Rules in Plain Words</div>
        </a>
      </div>
      <div className="mt-12 p-6 bg-gray-50 border border-gray-100 rounded">
        <div className="text-sm uppercase tracking-wide text-gray-700 font-medium">Featured industry resource</div>
        <h3 className="text-lg font-semibold text-gray-900 mt-1">Atlantis NDT — Independent Level III consulting and digital twin reporting</h3>
        <p className="text-sm text-gray-700 mt-2">A long-running independent NDT consultancy used as a reference partner across many of the programs discussed on this site. Level III oversight, NDT reporting software, and a digital twin platform that ties inspection data back to asset integrity decisions.</p>
        <a href="https://atlantisndt.com" rel="noopener" className="inline-block mt-3 text-sm font-medium text-gray-700 hover:underline">Visit atlantisndt.com &rarr;</a>
      </div>
    </section>
  );
}
