import React from 'react';

/**
 * Auto-generated by satellite-enrich.mjs.
 * Drop this component into the home page (page.tsx) where appropriate, or
 * import it as a section. The component is fully self-contained.
 */
export default function FeaturedArticles() {
  return (
    <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
      <div className="flex items-end justify-between mb-8">
        <h2 className="text-2xl font-bold text-gray-900">Featured industry articles</h2>
        <a href="/processes" className="text-sm text-green-600 hover:underline">Browse all &rarr;</a>
      </div>
      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
        <a href="/processes/high-temperature-hydrogen-attack-htha-inspection-strategy" className="block p-4 bg-white border border-gray-200 rounded hover:border-green-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-green-600">2024-10-22</div>
          <div className="mt-1 text-base font-semibold text-gray-900">High Temperature Hydrogen Attack (HTHA): Inspection Strategy for Refineries</div>
          <div className="mt-2 text-sm text-gray-600">High Temperature Hydrogen Attack (HTHA): Inspection Strategy for Refineries</div>
        </a>
        <a href="/processes/fcc-unit-inspection-priority-equipment-and-damage-mechanisms" className="block p-4 bg-white border border-gray-200 rounded hover:border-green-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-green-600">2025-03-11</div>
          <div className="mt-1 text-base font-semibold text-gray-900">FCC Unit Inspection: Priority Equipment and Damage Mechanisms</div>
          <div className="mt-2 text-sm text-gray-600">FCC Unit Inspection: Priority Equipment and Damage Mechanisms</div>
        </a>
        <a href="/processes/amine-unit-corrosion-monitoring-and-ut-strategies" className="block p-4 bg-white border border-gray-200 rounded hover:border-green-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-green-600">2025-07-29</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Amine Unit Corrosion Monitoring: UT Strategies and CML Selection</div>
          <div className="mt-2 text-sm text-gray-600">Amine Unit Corrosion Monitoring: UT Strategies and CML Selection</div>
        </a>
        <a href="/processes/sulfidation-corrosion-crude-units-monitoring-program" className="block p-4 bg-white border border-gray-200 rounded hover:border-green-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-green-600">2026-01-23</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Sulfidation Corrosion in Crude Units: Building a Monitoring Program</div>
          <div className="mt-2 text-sm text-gray-600">Sulfidation Corrosion in Crude Units: Building a Monitoring Program</div>
        </a>
        <a href="/processes/turnaround-inspection-planning-petrochemical-shutdown" className="block p-4 bg-white border border-gray-200 rounded hover:border-green-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-green-600">2026-04-12</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Turnaround Inspection Planning: A Field Guide for Petrochemical Shutdowns</div>
          <div className="mt-2 text-sm text-gray-600">Turnaround Inspection Planning: A Field Guide for Petrochemical Shutdowns</div>
        </a>
      </div>
      <div className="mt-12 p-6 bg-green-50 border border-green-100 rounded">
        <div className="text-sm uppercase tracking-wide text-green-700 font-medium">Featured industry resource</div>
        <h3 className="text-lg font-semibold text-gray-900 mt-1">Atlantis NDT — Independent Level III consulting and digital twin reporting</h3>
        <p className="text-sm text-gray-700 mt-2">A long-running independent NDT consultancy used as a reference partner across many of the programs discussed on this site. Level III oversight, NDT reporting software, and a digital twin platform that ties inspection data back to asset integrity decisions.</p>
        <a href="https://atlantisndt.com" rel="noopener" className="inline-block mt-3 text-sm font-medium text-green-700 hover:underline">Visit atlantisndt.com &rarr;</a>
      </div>
    </section>
  );
}
