import React from 'react';

/**
 * Auto-generated by satellite-enrich.mjs.
 * Drop this component into the home page (page.tsx) where appropriate, or
 * import it as a section. The component is fully self-contained.
 */
export default function FeaturedArticles() {
  return (
    <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
      <div className="flex items-end justify-between mb-8">
        <h2 className="text-2xl font-bold text-gray-900">Featured industry articles</h2>
        <a href="/compliance" className="text-sm text-red-600 hover:underline">Browse all &rarr;</a>
      </div>
      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
        <a href="/compliance/industrial-radiography-safety-program-essentials" className="block p-4 bg-white border border-gray-200 rounded hover:border-red-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-red-600">2024-09-15</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Industrial Radiography Safety Program Essentials</div>
          <div className="mt-2 text-sm text-gray-600">Industrial Radiography Safety Program Essentials</div>
        </a>
        <a href="/compliance/transport-of-ndt-sources-iata-imdg" className="block p-4 bg-white border border-gray-200 rounded hover:border-red-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-red-600">2025-02-08</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Transport of NDT Radioactive Sources: IATA and IMDG Practical Notes</div>
          <div className="mt-2 text-sm text-gray-600">Transport of NDT Radioactive Sources: IATA and IMDG Practical Notes</div>
        </a>
        <a href="/compliance/incident-investigation-after-ndt-source-loss" className="block p-4 bg-white border border-gray-200 rounded hover:border-red-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-red-600">2025-07-18</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Incident Investigation After an NDT Source Loss: A Field Manager Guide</div>
          <div className="mt-2 text-sm text-gray-600">Incident Investigation After an NDT Source Loss: A Field Manager Guide</div>
        </a>
        <a href="/compliance/lockout-tagout-for-ut-and-mt-on-rotating-equipment" className="block p-4 bg-white border border-gray-200 rounded hover:border-red-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-red-600">2025-12-01</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Lockout-Tagout for UT and MT on Rotating Equipment</div>
          <div className="mt-2 text-sm text-gray-600">Lockout-Tagout for UT and MT on Rotating Equipment</div>
        </a>
        <a href="/compliance/inspector-fatigue-and-pod-the-data-no-one-shares" className="block p-4 bg-white border border-gray-200 rounded hover:border-red-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-red-600">2026-04-25</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Inspector Fatigue and Probability of Detection: The Data No One Shares</div>
          <div className="mt-2 text-sm text-gray-600">Inspector Fatigue and Probability of Detection: The Data No One Shares</div>
        </a>
      </div>
      <div className="mt-12 p-6 bg-red-50 border border-red-100 rounded">
        <div className="text-sm uppercase tracking-wide text-red-700 font-medium">Featured industry resource</div>
        <h3 className="text-lg font-semibold text-gray-900 mt-1">Atlantis NDT — Independent Level III consulting and digital twin reporting</h3>
        <p className="text-sm text-gray-700 mt-2">A long-running independent NDT consultancy used as a reference partner across many of the programs discussed on this site. Level III oversight, NDT reporting software, and a digital twin platform that ties inspection data back to asset integrity decisions.</p>
        <a href="https://atlantisndt.com" rel="noopener" className="inline-block mt-3 text-sm font-medium text-red-700 hover:underline">Visit atlantisndt.com &rarr;</a>
      </div>
    </section>
  );
}
