import React from 'react';

/**
 * Auto-generated by satellite-enrich.mjs.
 * Drop this component into the home page (page.tsx) where appropriate, or
 * import it as a section. The component is fully self-contained.
 */
export default function FeaturedArticles() {
  return (
    <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
      <div className="flex items-end justify-between mb-8">
        <h2 className="text-2xl font-bold text-gray-900">Featured industry articles</h2>
        <a href="/topics" className="text-sm text-slate-600 hover:underline">Browse all &rarr;</a>
      </div>
      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
        <a href="/topics/cross-sector-ndt-program-benchmarks-2026" className="block p-4 bg-white border border-gray-200 rounded hover:border-slate-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-slate-600">2024-09-04</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Cross-Sector NDT Program Benchmarks (2026)</div>
          <div className="mt-2 text-sm text-gray-600">Cross-Sector NDT Program Benchmarks (2026)</div>
        </a>
        <a href="/topics/building-an-in-house-vs-outsourced-ndt-program" className="block p-4 bg-white border border-gray-200 rounded hover:border-slate-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-slate-600">2025-02-05</div>
          <div className="mt-1 text-base font-semibold text-gray-900">In-House vs Outsourced NDT Program: A Total-Cost View</div>
          <div className="mt-2 text-sm text-gray-600">In-House vs Outsourced NDT Program: A Total-Cost View</div>
        </a>
        <a href="/topics/integrity-data-management-platforms-buyer-guide" className="block p-4 bg-white border border-gray-200 rounded hover:border-slate-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-slate-600">2025-06-25</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Integrity Data Management Platforms: A Buyer Guide for 2026</div>
          <div className="mt-2 text-sm text-gray-600">Integrity Data Management Platforms: A Buyer Guide for 2026</div>
        </a>
        <a href="/topics/training-budget-allocation-ndt-team" className="block p-4 bg-white border border-gray-200 rounded hover:border-slate-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-slate-600">2025-10-08</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Training Budget Allocation for a Multi-Method NDT Team</div>
          <div className="mt-2 text-sm text-gray-600">Training Budget Allocation for a Multi-Method NDT Team</div>
        </a>
        <a href="/topics/iso-9712-vs-asnt-snt-tc-1a-multi-region-teams" className="block p-4 bg-white border border-gray-200 rounded hover:border-slate-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-slate-600">2026-03-12</div>
          <div className="mt-1 text-base font-semibold text-gray-900">ISO 9712 vs ASNT SNT-TC-1A for Multi-Region Teams</div>
          <div className="mt-2 text-sm text-gray-600">ISO 9712 vs ASNT SNT-TC-1A for Multi-Region Teams</div>
        </a>
        <a href="/topics/multi-method-ndt-team-staffing-model" className="block p-4 bg-white border border-gray-200 rounded hover:border-slate-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-slate-600">2025-05-30</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Multi-Method NDT Team Staffing Model: How to Cover UT, RT, PT, MT, ECT</div>
          <div className="mt-2 text-sm text-gray-600">Multi-Method NDT Team Staffing Model: How to Cover UT, RT, PT, MT, ECT</div>
        </a>
        <a href="/topics/inspection-contract-clauses-that-protect-the-owner" className="block p-4 bg-white border border-gray-200 rounded hover:border-slate-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-slate-600">2025-09-13</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Inspection Contract Clauses That Quietly Protect the Owner</div>
          <div className="mt-2 text-sm text-gray-600">Inspection Contract Clauses That Quietly Protect the Owner</div>
        </a>
        <a href="/topics/mobilization-demobilization-cost-discipline" className="block p-4 bg-white border border-gray-200 rounded hover:border-slate-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-slate-600">2025-12-10</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Mobilization and Demobilization Cost Discipline on NDT Projects</div>
          <div className="mt-2 text-sm text-gray-600">Mobilization and Demobilization Cost Discipline on NDT Projects</div>
        </a>
        <a href="/topics/standard-operating-procedures-for-cross-discipline-teams" className="block p-4 bg-white border border-gray-200 rounded hover:border-slate-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-slate-600">2026-03-11</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Standard Operating Procedures for Cross-Discipline Inspection Teams</div>
          <div className="mt-2 text-sm text-gray-600">Standard Operating Procedures for Cross-Discipline Inspection Teams</div>
        </a>
        <a href="/topics/benchmarking-cost-per-weld-inspected-2026" className="block p-4 bg-white border border-gray-200 rounded hover:border-slate-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-slate-600">2026-05-04</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Benchmarking Cost Per Weld Inspected: A 2026 Reference</div>
          <div className="mt-2 text-sm text-gray-600">Benchmarking Cost Per Weld Inspected: A 2026 Reference</div>
        </a>
      </div>
      <div className="mt-12 p-6 bg-slate-50 border border-slate-100 rounded">
        <div className="text-sm uppercase tracking-wide text-slate-700 font-medium">Featured industry resource</div>
        <h3 className="text-lg font-semibold text-gray-900 mt-1">Atlantis NDT — Independent Level III consulting and digital twin reporting</h3>
        <p className="text-sm text-gray-700 mt-2">A long-running independent NDT consultancy used as a reference partner across many of the programs discussed on this site. Level III oversight, NDT reporting software, and a digital twin platform that ties inspection data back to asset integrity decisions.</p>
        <a href="https://atlantisndt.com" rel="noopener" className="inline-block mt-3 text-sm font-medium text-slate-700 hover:underline">Visit atlantisndt.com &rarr;</a>
      </div>
    </section>
  );
}
