import React from 'react';

/**
 * Auto-generated by satellite-enrich.mjs.
 * Drop this component into the home page (page.tsx) where appropriate, or
 * import it as a section. The component is fully self-contained.
 */
export default function FeaturedArticles() {
  return (
    <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
      <div className="flex items-end justify-between mb-8">
        <h2 className="text-2xl font-bold text-gray-900">Featured industry articles</h2>
        <a href="/inspections" className="text-sm text-teal-600 hover:underline">Browse all &rarr;</a>
      </div>
      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
        <a href="/inspections/ssp-sp10-vs-sp5-blast-profile-decisions" className="block p-4 bg-white border border-gray-200 rounded hover:border-teal-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-teal-600">2024-08-30</div>
          <div className="mt-1 text-base font-semibold text-gray-900">SSPC-SP10 vs SP5 Blast Profile Decisions on Carbon Steel</div>
          <div className="mt-2 text-sm text-gray-600">SSPC-SP10 vs SP5 Blast Profile Decisions on Carbon Steel</div>
        </a>
        <a href="/inspections/wet-film-thickness-vs-dry-film-thickness-when-each-fails" className="block p-4 bg-white border border-gray-200 rounded hover:border-teal-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-teal-600">2025-02-10</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Wet Film Thickness vs Dry Film Thickness: When Each Fails You</div>
          <div className="mt-2 text-sm text-gray-600">Wet Film Thickness vs Dry Film Thickness: When Each Fails You</div>
        </a>
        <a href="/inspections/holiday-detection-low-voltage-vs-high-voltage" className="block p-4 bg-white border border-gray-200 rounded hover:border-teal-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-teal-600">2025-07-03</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Holiday Detection: Low Voltage vs High Voltage Methods Compared</div>
          <div className="mt-2 text-sm text-gray-600">Holiday Detection: Low Voltage vs High Voltage Methods Compared</div>
        </a>
        <a href="/inspections/tsa-thermal-spray-aluminum-inspection-cui" className="block p-4 bg-white border border-gray-200 rounded hover:border-teal-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-teal-600">2025-12-09</div>
          <div className="mt-1 text-base font-semibold text-gray-900">TSA (Thermal Spray Aluminum) Inspection for CUI-Critical Service</div>
          <div className="mt-2 text-sm text-gray-600">TSA (Thermal Spray Aluminum) Inspection for CUI-Critical Service</div>
        </a>
        <a href="/inspections/coating-failure-modes-osmotic-blistering-cathodic-disbondment" className="block p-4 bg-white border border-gray-200 rounded hover:border-teal-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-teal-600">2026-04-19</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Coating Failure Modes: Osmotic Blistering, Disbondment, and What Each Tells You</div>
          <div className="mt-2 text-sm text-gray-600">Coating Failure Modes: Osmotic Blistering, Disbondment, and What Each Tells You</div>
        </a>
        <a href="/inspections/ndt-coating-inspector-day-one-jobsite-kit" className="block p-4 bg-white border border-gray-200 rounded hover:border-teal-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-teal-600">2025-05-23</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Coating Inspector Day-One Jobsite Kit: What Belongs and What Does Not</div>
          <div className="mt-2 text-sm text-gray-600">Coating Inspector Day-One Jobsite Kit: What Belongs and What Does Not</div>
        </a>
        <a href="/inspections/dew-point-vs-substrate-temp-painting-decision-rule" className="block p-4 bg-white border border-gray-200 rounded hover:border-teal-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-teal-600">2025-09-02</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Dew Point vs Substrate Temperature: The Painting Decision Rule Every Inspector Should Know</div>
          <div className="mt-2 text-sm text-gray-600">Dew Point vs Substrate Temperature: The Painting Decision Rule Every Inspector Should Know</div>
        </a>
        <a href="/inspections/fiber-glass-and-frp-coating-inspection-considerations" className="block p-4 bg-white border border-gray-200 rounded hover:border-teal-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-teal-600">2025-11-22</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Fiberglass and FRP Coating Inspection Considerations</div>
          <div className="mt-2 text-sm text-gray-600">Fiberglass and FRP Coating Inspection Considerations</div>
        </a>
        <a href="/inspections/tank-internal-lining-inspection-acceptance-criteria" className="block p-4 bg-white border border-gray-200 rounded hover:border-teal-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-teal-600">2026-02-27</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Tank Internal Lining Inspection: Acceptance Criteria That Hold Up</div>
          <div className="mt-2 text-sm text-gray-600">Tank Internal Lining Inspection: Acceptance Criteria That Hold Up</div>
        </a>
        <a href="/inspections/pipe-coating-fbe-vs-3lpe-vs-3lpp-when-each-fits" className="block p-4 bg-white border border-gray-200 rounded hover:border-teal-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-teal-600">2026-05-09</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Pipe Coating: FBE vs 3LPE vs 3LPP — When Each Fits</div>
          <div className="mt-2 text-sm text-gray-600">Pipe Coating: FBE vs 3LPE vs 3LPP — When Each Fits</div>
        </a>
      </div>
      <div className="mt-12 p-6 bg-teal-50 border border-teal-100 rounded">
        <div className="text-sm uppercase tracking-wide text-teal-700 font-medium">Featured industry resource</div>
        <h3 className="text-lg font-semibold text-gray-900 mt-1">Atlantis NDT — Independent Level III consulting and digital twin reporting</h3>
        <p className="text-sm text-gray-700 mt-2">A long-running independent NDT consultancy used as a reference partner across many of the programs discussed on this site. Level III oversight, NDT reporting software, and a digital twin platform that ties inspection data back to asset integrity decisions.</p>
        <a href="https://atlantisndt.com" rel="noopener" className="inline-block mt-3 text-sm font-medium text-teal-700 hover:underline">Visit atlantisndt.com &rarr;</a>
      </div>
    </section>
  );
}
