import React from 'react';

/**
 * Auto-generated by satellite-enrich.mjs.
 * Drop this component into the home page (page.tsx) where appropriate, or
 * import it as a section. The component is fully self-contained.
 */
export default function FeaturedArticles() {
  return (
    <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
      <div className="flex items-end justify-between mb-8">
        <h2 className="text-2xl font-bold text-gray-900">Featured industry articles</h2>
        <a href="/practice" className="text-sm text-lime-600 hover:underline">Browse all &rarr;</a>
      </div>
      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
        <a href="/practice/gpr-vs-rebar-locator-when-which" className="block p-4 bg-white border border-gray-200 rounded hover:border-lime-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-lime-600">2024-08-22</div>
          <div className="mt-1 text-base font-semibold text-gray-900">GPR vs Rebar Locator: When Each One Earns the Hourly Rate</div>
          <div className="mt-2 text-sm text-gray-600">GPR vs Rebar Locator: When Each One Earns the Hourly Rate</div>
        </a>
        <a href="/practice/concrete-strength-with-rebound-hammer-vs-ut-velocity" className="block p-4 bg-white border border-gray-200 rounded hover:border-lime-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-lime-600">2025-01-30</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Concrete Strength: Rebound Hammer vs Ultrasonic Pulse Velocity</div>
          <div className="mt-2 text-sm text-gray-600">Concrete Strength: Rebound Hammer vs Ultrasonic Pulse Velocity</div>
        </a>
        <a href="/practice/bridge-deck-deterioration-mapping-methods" className="block p-4 bg-white border border-gray-200 rounded hover:border-lime-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-lime-600">2025-07-08</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Bridge Deck Deterioration Mapping: Methods That Actually Work</div>
          <div className="mt-2 text-sm text-gray-600">Bridge Deck Deterioration Mapping: Methods That Actually Work</div>
        </a>
        <a href="/practice/post-tensioned-cable-inspection-impact-echo-and-ut" className="block p-4 bg-white border border-gray-200 rounded hover:border-lime-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-lime-600">2025-11-12</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Post-Tensioned Cable Inspection: Impact-Echo and UT Strategies</div>
          <div className="mt-2 text-sm text-gray-600">Post-Tensioned Cable Inspection: Impact-Echo and UT Strategies</div>
        </a>
        <a href="/practice/steel-structure-weld-inspection-aws-d1-5" className="block p-4 bg-white border border-gray-200 rounded hover:border-lime-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-lime-600">2026-04-02</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Steel Structure Weld Inspection Under AWS D1.5 (Bridge Welding Code)</div>
          <div className="mt-2 text-sm text-gray-600">Steel Structure Weld Inspection Under AWS D1.5 (Bridge Welding Code)</div>
        </a>
      </div>
      <div className="mt-12 p-6 bg-lime-50 border border-lime-100 rounded">
        <div className="text-sm uppercase tracking-wide text-lime-700 font-medium">Featured industry resource</div>
        <h3 className="text-lg font-semibold text-gray-900 mt-1">Atlantis NDT — Independent Level III consulting and digital twin reporting</h3>
        <p className="text-sm text-gray-700 mt-2">A long-running independent NDT consultancy used as a reference partner across many of the programs discussed on this site. Level III oversight, NDT reporting software, and a digital twin platform that ties inspection data back to asset integrity decisions.</p>
        <a href="https://atlantisndt.com" rel="noopener" className="inline-block mt-3 text-sm font-medium text-lime-700 hover:underline">Visit atlantisndt.com &rarr;</a>
      </div>
    </section>
  );
}
