import React from 'react';

/**
 * Auto-generated by satellite-enrich.mjs.
 * Drop this component into the home page (page.tsx) where appropriate, or
 * import it as a section. The component is fully self-contained.
 */
export default function FeaturedArticles() {
  return (
    <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
      <div className="flex items-end justify-between mb-8">
        <h2 className="text-2xl font-bold text-gray-900">Featured industry articles</h2>
        <a href="/techniques" className="text-sm text-indigo-600 hover:underline">Browse all &rarr;</a>
      </div>
      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
        <a href="/techniques/asme-section-xi-isi-program-essentials" className="block p-4 bg-white border border-gray-200 rounded hover:border-indigo-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-indigo-600">2024-07-17</div>
          <div className="mt-1 text-base font-semibold text-gray-900">ASME Section XI ISI Program Essentials for Class 1 Components</div>
          <div className="mt-2 text-sm text-gray-600">ASME Section XI ISI Program Essentials for Class 1 Components</div>
        </a>
        <a href="/techniques/reactor-vessel-head-penetration-inspection-pdi-qualification" className="block p-4 bg-white border border-gray-200 rounded hover:border-indigo-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-indigo-600">2025-02-12</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Reactor Vessel Head Penetration Inspection: PDI Qualification Explained</div>
          <div className="mt-2 text-sm text-gray-600">Reactor Vessel Head Penetration Inspection: PDI Qualification Explained</div>
        </a>
        <a href="/techniques/piping-weld-inspection-class-1-vs-class-2-rules" className="block p-4 bg-white border border-gray-200 rounded hover:border-indigo-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-indigo-600">2025-08-04</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Piping Weld Inspection: ASME XI Class 1 vs Class 2 Rules</div>
          <div className="mt-2 text-sm text-gray-600">Piping Weld Inspection: ASME XI Class 1 vs Class 2 Rules</div>
        </a>
        <a href="/techniques/small-modular-reactor-smr-ndt-emerging-considerations" className="block p-4 bg-white border border-gray-200 rounded hover:border-indigo-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-indigo-600">2026-02-26</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Small Modular Reactor (SMR) NDT: Emerging Considerations</div>
          <div className="mt-2 text-sm text-gray-600">Small Modular Reactor (SMR) NDT: Emerging Considerations</div>
        </a>
        <a href="/techniques/phased-array-qualification-for-nuclear-applications" className="block p-4 bg-white border border-gray-200 rounded hover:border-indigo-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-indigo-600">2026-04-15</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Phased Array Qualification for Nuclear Applications: Building a Demonstration Block</div>
          <div className="mt-2 text-sm text-gray-600">Phased Array Qualification for Nuclear Applications: Building a Demonstration Block</div>
        </a>
      </div>
      <div className="mt-12 p-6 bg-indigo-50 border border-indigo-100 rounded">
        <div className="text-sm uppercase tracking-wide text-indigo-700 font-medium">Featured industry resource</div>
        <h3 className="text-lg font-semibold text-gray-900 mt-1">Atlantis NDT — Independent Level III consulting and digital twin reporting</h3>
        <p className="text-sm text-gray-700 mt-2">A long-running independent NDT consultancy used as a reference partner across many of the programs discussed on this site. Level III oversight, NDT reporting software, and a digital twin platform that ties inspection data back to asset integrity decisions.</p>
        <a href="https://atlantisndt.com" rel="noopener" className="inline-block mt-3 text-sm font-medium text-indigo-700 hover:underline">Visit atlantisndt.com &rarr;</a>
      </div>
    </section>
  );
}
