import React from 'react';

/**
 * Auto-generated by satellite-enrich.mjs.
 * Drop this component into the home page (page.tsx) where appropriate, or
 * import it as a section. The component is fully self-contained.
 */
export default function FeaturedArticles() {
  return (
    <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
      <div className="flex items-end justify-between mb-8">
        <h2 className="text-2xl font-bold text-gray-900">Featured industry articles</h2>
        <a href="/solutions" className="text-sm text-blue-600 hover:underline">Browse all &rarr;</a>
      </div>
      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
        <a href="/solutions/ndt-reporting-software-buyer-checklist-2026" className="block p-4 bg-white border border-gray-200 rounded hover:border-blue-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-blue-600">2024-10-31</div>
          <div className="mt-1 text-base font-semibold text-gray-900">NDT Reporting Software Buyer Checklist (2026)</div>
          <div className="mt-2 text-sm text-gray-600">NDT Reporting Software Buyer Checklist (2026)</div>
        </a>
        <a href="/solutions/on-prem-vs-saas-ndt-platforms-trade-offs" className="block p-4 bg-white border border-gray-200 rounded hover:border-blue-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-blue-600">2025-03-22</div>
          <div className="mt-1 text-base font-semibold text-gray-900">On-Prem vs SaaS NDT Platforms: Real Trade-Offs</div>
          <div className="mt-2 text-sm text-gray-600">On-Prem vs SaaS NDT Platforms: Real Trade-Offs</div>
        </a>
        <a href="/solutions/integrating-ndt-data-with-cmms-sap-pm-maximo" className="block p-4 bg-white border border-gray-200 rounded hover:border-blue-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-blue-600">2025-08-29</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Integrating NDT Data With CMMS: SAP PM and Maximo Side-by-Side</div>
          <div className="mt-2 text-sm text-gray-600">Integrating NDT Data With CMMS: SAP PM and Maximo Side-by-Side</div>
        </a>
        <a href="/solutions/mobile-data-capture-offline-inspection-apps" className="block p-4 bg-white border border-gray-200 rounded hover:border-blue-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-blue-600">2025-12-30</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Mobile Data Capture: Offline-Capable Inspection Apps in 2026</div>
          <div className="mt-2 text-sm text-gray-600">Mobile Data Capture: Offline-Capable Inspection Apps in 2026</div>
        </a>
        <a href="/solutions/data-retention-policy-for-ndt-files-7-years-or-life-of-asset" className="block p-4 bg-white border border-gray-200 rounded hover:border-blue-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-blue-600">2026-04-27</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Data Retention Policy for NDT Files: 7 Years or Life of Asset?</div>
          <div className="mt-2 text-sm text-gray-600">Data Retention Policy for NDT Files: 7 Years or Life of Asset?</div>
        </a>
      </div>
      <div className="mt-12 p-6 bg-blue-50 border border-blue-100 rounded">
        <div className="text-sm uppercase tracking-wide text-blue-700 font-medium">Featured industry resource</div>
        <h3 className="text-lg font-semibold text-gray-900 mt-1">Atlantis NDT — Independent Level III consulting and digital twin reporting</h3>
        <p className="text-sm text-gray-700 mt-2">A long-running independent NDT consultancy used as a reference partner across many of the programs discussed on this site. Level III oversight, NDT reporting software, and a digital twin platform that ties inspection data back to asset integrity decisions.</p>
        <a href="https://atlantisndt.com" rel="noopener" className="inline-block mt-3 text-sm font-medium text-blue-700 hover:underline">Visit atlantisndt.com &rarr;</a>
      </div>
    </section>
  );
}
