import React from 'react';

/**
 * Auto-generated by satellite-enrich.mjs.
 * Drop this component into the home page (page.tsx) where appropriate, or
 * import it as a section. The component is fully self-contained.
 */
export default function FeaturedArticles() {
  return (
    <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
      <div className="flex items-end justify-between mb-8">
        <h2 className="text-2xl font-bold text-gray-900">Featured industry articles</h2>
        <a href="/standards" className="text-sm text-sky-600 hover:underline">Browse all &rarr;</a>
      </div>
      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
        <a href="/standards/nas-410-vs-en-4179-aerospace-certification-paths" className="block p-4 bg-white border border-gray-200 rounded hover:border-sky-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-sky-600">2024-08-05</div>
          <div className="mt-1 text-base font-semibold text-gray-900">NAS 410 vs EN 4179: Two Aerospace NDT Certification Paths Compared</div>
          <div className="mt-2 text-sm text-gray-600">NAS 410 vs EN 4179: Two Aerospace NDT Certification Paths Compared</div>
        </a>
        <a href="/standards/composite-aircraft-structure-ndt-cfrp-inspection" className="block p-4 bg-white border border-gray-200 rounded hover:border-sky-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-sky-600">2024-12-15</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Composite Aircraft Structure NDT: CFRP Inspection Methods</div>
          <div className="mt-2 text-sm text-gray-600">Composite Aircraft Structure NDT: CFRP Inspection Methods</div>
        </a>
        <a href="/standards/engine-disk-bore-inspection-eddy-current-array" className="block p-4 bg-white border border-gray-200 rounded hover:border-sky-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-sky-600">2025-05-06</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Engine Disk Bore Inspection: Eddy Current Array in Aero Engines</div>
          <div className="mt-2 text-sm text-gray-600">Engine Disk Bore Inspection: Eddy Current Array in Aero Engines</div>
        </a>
        <a href="/standards/nadcap-audit-readiness-aerospace-ndt-shop" className="block p-4 bg-white border border-gray-200 rounded hover:border-sky-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-sky-600">2025-10-21</div>
          <div className="mt-1 text-base font-semibold text-gray-900">NADCAP Audit Readiness: A Checklist for the Aerospace NDT Shop</div>
          <div className="mt-2 text-sm text-gray-600">NADCAP Audit Readiness: A Checklist for the Aerospace NDT Shop</div>
        </a>
        <a href="/standards/fluorescent-penetrant-inspection-fpi-aerospace-process-control" className="block p-4 bg-white border border-gray-200 rounded hover:border-sky-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-sky-600">2026-03-30</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Fluorescent Penetrant Inspection (FPI) in Aerospace: Process Control That Works</div>
          <div className="mt-2 text-sm text-gray-600">Fluorescent Penetrant Inspection (FPI) in Aerospace: Process Control That Works</div>
        </a>
        <a href="/standards/shot-peening-inspection-and-coverage-verification" className="block p-4 bg-white border border-gray-200 rounded hover:border-sky-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-sky-600">2025-05-21</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Shot Peening Inspection and Coverage Verification on Aero Parts</div>
          <div className="mt-2 text-sm text-gray-600">Shot Peening Inspection and Coverage Verification on Aero Parts</div>
        </a>
        <a href="/standards/ndt-on-titanium-airframe-structure-considerations" className="block p-4 bg-white border border-gray-200 rounded hover:border-sky-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-sky-600">2025-09-04</div>
          <div className="mt-1 text-base font-semibold text-gray-900">NDT on Titanium Airframe Structure: Method Considerations</div>
          <div className="mt-2 text-sm text-gray-600">NDT on Titanium Airframe Structure: Method Considerations</div>
        </a>
        <a href="/standards/magnetic-particle-on-landing-gear-components" className="block p-4 bg-white border border-gray-200 rounded hover:border-sky-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-sky-600">2025-12-11</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Magnetic Particle Inspection on Landing Gear Components</div>
          <div className="mt-2 text-sm text-gray-600">Magnetic Particle Inspection on Landing Gear Components</div>
        </a>
        <a href="/standards/aerospace-ndt-data-record-retention-2026" className="block p-4 bg-white border border-gray-200 rounded hover:border-sky-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-sky-600">2026-03-01</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Aerospace NDT Data Record Retention: What 2026 Audits Actually Demand</div>
          <div className="mt-2 text-sm text-gray-600">Aerospace NDT Data Record Retention: What 2026 Audits Actually Demand</div>
        </a>
        <a href="/standards/engine-blade-tip-inspection-eddy-current-vs-fpi" className="block p-4 bg-white border border-gray-200 rounded hover:border-sky-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-sky-600">2026-05-13</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Engine Blade Tip Inspection: Eddy Current vs FPI Comparison</div>
          <div className="mt-2 text-sm text-gray-600">Engine Blade Tip Inspection: Eddy Current vs FPI Comparison</div>
        </a>
      </div>
      <div className="mt-12 p-6 bg-sky-50 border border-sky-100 rounded">
        <div className="text-sm uppercase tracking-wide text-sky-700 font-medium">Featured industry resource</div>
        <h3 className="text-lg font-semibold text-gray-900 mt-1">Atlantis NDT — Independent Level III consulting and digital twin reporting</h3>
        <p className="text-sm text-gray-700 mt-2">A long-running independent NDT consultancy used as a reference partner across many of the programs discussed on this site. Level III oversight, NDT reporting software, and a digital twin platform that ties inspection data back to asset integrity decisions.</p>
        <a href="https://atlantisndt.com" rel="noopener" className="inline-block mt-3 text-sm font-medium text-sky-700 hover:underline">Visit atlantisndt.com &rarr;</a>
      </div>
    </section>
  );
}
