import type { MetadataRoute } from 'next';
const routes = [
  "/",
  "/applications",
  "/applications/composite-inspection",
  "/applications/engine-overhaul",
  "/applications/fuselage-fatigue",
  "/applications/landing-gear",
  "/applications/turbine-blade",
  "/atlantis-products-services",
  "/blog",
  "/blog/aerospace-digital-twin-for-fleet-integrity",
  "/blog/crossing-from-industrial-ndt-into-aerospace",
  "/blog/nadcap-compliance-with-ndt-inspection-erp",
  "/blog/what-nadcap-auditors-look-at-before-they-look-at-your-technique",
  "/career",
  "/career/mro-vs-oem",
  "/career/salary-guide",
  "/methods",
  "/methods/digital-radiography-aviation",
  "/methods/eddy-current-aircraft",
  "/methods/phased-array-aerospace",
  "/methods/thermography-composites",
  "/standards",
  "/standards/aerospace-ndt-data-record-retention-2026",
  "/standards/composite-aircraft-structure-ndt-cfrp-inspection",
  "/standards/engine-blade-tip-inspection-eddy-current-vs-fpi",
  "/standards/engine-disk-bore-inspection-eddy-current-array",
  "/standards/fluorescent-penetrant-inspection-fpi-aerospace-process-control",
  "/standards/magnetic-particle-on-landing-gear-components",
  "/standards/nadcap",
  "/standards/nadcap-audit-readiness-aerospace-ndt-shop",
  "/standards/nas-410",
  "/standards/nas-410-vs-en-4179-aerospace-certification-paths",
  "/standards/ndt-on-titanium-airframe-structure-considerations",
  "/standards/shot-peening-inspection-and-coverage-verification"
];
export default function sitemap(): MetadataRoute.Sitemap {
  return routes.map(route => ({ url: "https://aerospace-ndt-standards.vercel.app" + route }));
}
