import React from 'react';

/**
 * Auto-generated by satellite-enrich.mjs.
 * Drop this component into the home page (page.tsx) where appropriate, or
 * import it as a section. The component is fully self-contained.
 */
export default function FeaturedArticles() {
  return (
    <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
      <div className="flex items-end justify-between mb-8">
        <h2 className="text-2xl font-bold text-gray-900">Featured industry articles</h2>
        <a href="/management" className="text-sm text-rose-600 hover:underline">Browse all &rarr;</a>
      </div>
      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
        <a href="/management/cui-inspection-strategy-when-to-strip-insulation" className="block p-4 bg-white border border-gray-200 rounded hover:border-rose-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-rose-600">2024-08-28</div>
          <div className="mt-1 text-base font-semibold text-gray-900">CUI Inspection Strategy: When to Strip Insulation vs Use Pulsed Eddy Current</div>
          <div className="mt-2 text-sm text-gray-600">CUI Inspection Strategy: When to Strip Insulation vs Use Pulsed Eddy Current</div>
        </a>
        <a href="/management/ph-monitoring-vs-corrosion-coupons-which-data-trust" className="block p-4 bg-white border border-gray-200 rounded hover:border-rose-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-rose-600">2025-03-04</div>
          <div className="mt-1 text-base font-semibold text-gray-900">pH Monitoring vs Corrosion Coupons: Which Data Should You Trust?</div>
          <div className="mt-2 text-sm text-gray-600">pH Monitoring vs Corrosion Coupons: Which Data Should You Trust?</div>
        </a>
        <a href="/management/msl-stress-corrosion-cracking-austenitic-stainless" className="block p-4 bg-white border border-gray-200 rounded hover:border-rose-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-rose-600">2025-08-19</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Stress Corrosion Cracking in Austenitic Stainless: Detection and Mitigation</div>
          <div className="mt-2 text-sm text-gray-600">Stress Corrosion Cracking in Austenitic Stainless: Detection and Mitigation</div>
        </a>
        <a href="/management/inhibitor-injection-program-effectiveness-monitoring" className="block p-4 bg-white border border-gray-200 rounded hover:border-rose-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-rose-600">2025-12-22</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Inhibitor Injection Program Effectiveness: How to Actually Monitor It</div>
          <div className="mt-2 text-sm text-gray-600">Inhibitor Injection Program Effectiveness: How to Actually Monitor It</div>
        </a>
        <a href="/management/building-corrosion-management-program-iso-55000" className="block p-4 bg-white border border-gray-200 rounded hover:border-rose-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-rose-600">2026-04-30</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Building a Corrosion Management Program Under ISO 55000</div>
          <div className="mt-2 text-sm text-gray-600">Building a Corrosion Management Program Under ISO 55000</div>
        </a>
        <a href="/management/sweet-vs-sour-corrosion-inspection-program-design" className="block p-4 bg-white border border-gray-200 rounded hover:border-rose-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-rose-600">2025-05-26</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Sweet vs Sour Corrosion: Designing Two Different Inspection Programs</div>
          <div className="mt-2 text-sm text-gray-600">Sweet vs Sour Corrosion: Designing Two Different Inspection Programs</div>
        </a>
        <a href="/management/microbiologically-influenced-corrosion-mic-detection" className="block p-4 bg-white border border-gray-200 rounded hover:border-rose-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-rose-600">2025-09-19</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Microbiologically Influenced Corrosion (MIC): Detection That Actually Works</div>
          <div className="mt-2 text-sm text-gray-600">Microbiologically Influenced Corrosion (MIC): Detection That Actually Works</div>
        </a>
        <a href="/management/erosion-corrosion-vs-flow-accelerated-corrosion" className="block p-4 bg-white border border-gray-200 rounded hover:border-rose-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-rose-600">2025-12-18</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Erosion-Corrosion vs Flow-Accelerated Corrosion: How to Tell Them Apart</div>
          <div className="mt-2 text-sm text-gray-600">Erosion-Corrosion vs Flow-Accelerated Corrosion: How to Tell Them Apart</div>
        </a>
        <a href="/management/galvanic-corrosion-prevention-design-and-inspection" className="block p-4 bg-white border border-gray-200 rounded hover:border-rose-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-rose-600">2026-03-14</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Galvanic Corrosion Prevention: Design Choices and Inspection Strategy</div>
          <div className="mt-2 text-sm text-gray-600">Galvanic Corrosion Prevention: Design Choices and Inspection Strategy</div>
        </a>
        <a href="/management/corrosion-rate-vs-thickness-trends-what-the-data-says" className="block p-4 bg-white border border-gray-200 rounded hover:border-rose-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-rose-600">2026-05-10</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Corrosion Rate vs Thickness Trends: What the Long-Term Data Actually Tells You</div>
          <div className="mt-2 text-sm text-gray-600">Corrosion Rate vs Thickness Trends: What the Long-Term Data Actually Tells You</div>
        </a>
      </div>
      <div className="mt-12 p-6 bg-rose-50 border border-rose-100 rounded">
        <div className="text-sm uppercase tracking-wide text-rose-700 font-medium">Featured industry resource</div>
        <h3 className="text-lg font-semibold text-gray-900 mt-1">Atlantis NDT — Independent Level III consulting and digital twin reporting</h3>
        <p className="text-sm text-gray-700 mt-2">A long-running independent NDT consultancy used as a reference partner across many of the programs discussed on this site. Level III oversight, NDT reporting software, and a digital twin platform that ties inspection data back to asset integrity decisions.</p>
        <a href="https://atlantisndt.com" rel="noopener" className="inline-block mt-3 text-sm font-medium text-rose-700 hover:underline">Visit atlantisndt.com &rarr;</a>
      </div>
    </section>
  );
}
