import ProductPageLayout from "@/components/ProductPageLayout";

const compareRows = [
    { factor: "Ontario nuclear asset profile", atlantis: "Bruce Power (8 operating CANDU reactors at Bruce A & B, ~6,550 MWe &mdash; the largest operating nuclear facility in the world), Ontario Power Generation (OPG) Darlington Nuclear (4 CANDU reactors, ~3,512 MWe + ongoing refurbishment), OPG Pickering (currently in safe-store/decommissioning planning post-2026), plus the Chalk River Laboratories research reactor heritage", competitor: "—" },
    { factor: "Reactor technology", atlantis: "CANDU (Canada Deuterium Uranium) pressurised heavy-water reactors &mdash; the canonical Canadian reactor design, with horizontal pressure tubes, online refuelling, and unique inspection requirements vs PWR/BWR", competitor: "—" },
    { factor: "Damage mechanism stack", atlantis: "Pressure tube hydride blister formation (CANDU-specific), pressure tube wall thinning from fuel bundle wear, calandria tube integrity, end-fitting cracking, feeder pipe FAC (Flow-Accelerated Corrosion), steam generator tube wear and degradation", competitor: "—" },
    { factor: "Regulatory regime", atlantis: "CNSC (Canadian Nuclear Safety Commission), CSA N285 / N287 / N289 nuclear inspection codes, CSA N286 management system standards, plus IAEA safeguards and ASME Section XI Division 1 equivalent provisions where applicable", competitor: "—" },
    { factor: "ROI typical (CANDU reactor)", atlantis: "$5M&ndash;$20M/yr per operating reactor &mdash; driven by refurbishment programme efficiency (Bruce Power MCR is the largest infrastructure project in Canadian history), capacity factor protection, and CNSC audit-pack automation", competitor: "—" },
    { factor: "Implementation", atlantis: "12&ndash;20 weeks first reactor live; 6&ndash;10 weeks per subsequent reactor. Coexistence with existing operator nuclear integrity tools and CNSC reporting infrastructure.", competitor: "—" },
];

const faqs = [
    { question: "Why are Ontario CANDU reactors a distinctive digital twin opportunity?", answer: "Ontario hosts the largest concentration of operating CANDU reactors in the world. Bruce Power operates 8 reactors at Bruce A and Bruce B near Tiverton, ON, with combined capacity ~6,550 MWe &mdash; making Bruce the largest operating nuclear facility on earth by net capacity. Ontario Power Generation (OPG) operates 4 reactors at Darlington (~3,512 MWe), with the Darlington Refurbishment programme extending operating life beyond 2055. The OPG Pickering station is heading toward safe-store/decommissioning planning post-2026, though some refurbishment of Pickering Units 5&ndash;8 has been proposed. The Bruce Major Component Replacement (MCR) refurbishment programme is the largest infrastructure project in Canadian history at a forecast cost of ~CAD $13B over a multi-decade rolling cycle. The integrity engineering, inspection, and regulatory ecosystem concentrated in Toronto-Hamilton-Tiverton-Darlington is unmatched in CANDU operations globally. Atlantis Digital Twin handles CANDU-specific inspection workflows alongside the standard ASME Section XI Division 1 equivalent provisions and the CSA N285/N287/N289 inspection regime." },
    { question: "What are the CANDU-specific inspection workflows that PWR/BWR tools don&rsquo;t handle natively?", answer: "CANDU pressurised heavy-water reactors have several inspection requirements that don&rsquo;t exist in PWR or BWR designs. The pressure tube hydride blister formation workflow is unique: zirconium-alloy pressure tubes (typically Zr-2.5Nb) absorb hydrogen during operation, leading to delayed hydride cracking (DHC) and hydride blister formation that requires periodic ultrasonic and eddy-current inspection. The pressure tube wall thinning from fuel bundle wear (the &lsquo;flow-rotor&rsquo; mechanism) is also CANDU-specific. End fittings (where pressure tubes meet the calandria) require periodic inspection for cracking. Calandria tube integrity (the outer tube containing the pressure tube in the calandria moderator tank) requires specialised inspection. Feeder pipe FAC (Flow-Accelerated Corrosion) is a major CANDU damage mechanism on the carbon-steel feeder pipes connecting fuel channels to the headers. Atlantis ships templates for each of these workflows, aligned to CSA N285.4 / N285.5 inspection code provisions." },
    { question: "How does Atlantis integrate with CNSC and CSA N-series compliance?", answer: "CNSC (Canadian Nuclear Safety Commission) is the federal nuclear regulator. CSA N285 governs periodic inspection of CANDU nuclear power plant components, with N285.1 covering pressure-retaining components, N285.4 covering in-service inspection of fuel channels, and N285.5 covering pressure tubes. CSA N287 covers concrete containment structures. CSA N289 covers seismic qualification. CSA N286 covers management system requirements. Atlantis ships CSA N-series audit-pack templates, generating compliance evidence in &lt;30 seconds from the digital twin data repository. ASME Section XI Division 1 provisions apply where directly relevant (predominantly for components like steam generators where the design follows ASME conventions). IAEA safeguards reporting (the international non-proliferation framework) ties into the inspection data repository for facilities subject to safeguards verification." },
    { question: "How does the Bruce / Darlington refurbishment programme integrate?", answer: "The Bruce Power Major Component Replacement (MCR) programme &mdash; replacing pressure tubes, calandria tubes, feeder pipes, and steam generators across the 8 Bruce reactors on a rolling cycle &mdash; is the largest infrastructure project in Canadian history at ~CAD $13B forecast cost. The OPG Darlington Refurbishment programme is conducting a similar major component replacement across all 4 Darlington reactors. These projects generate enormous inspection data volumes: every replaced pressure tube has a full baseline inspection record, every new feeder pipe has post-installation NDE, every new steam generator has full hydro-test and PWHT records. Atlantis Digital Twin handles the refurbishment data capture workflow: construction-vintage inspection data, baseline post-installation surveys, and the first 5&ndash;10 years of in-service inspection data &mdash; all consolidated in the twin from day one. The advantage of building the digital twin during refurbishment (rather than retrofitting after) is significant: 6&ndash;18 months of post-startup data backfill effort eliminated." },
    { question: "What about steam generator tube integrity and SMR future programmes?", answer: "Steam generator tube integrity is a critical safety concern across all reactor designs. CANDU steam generators (typically Babcock & Wilcox or Babcock Canada designs) use Inconel 600 / 690 tubes with periodic eddy current inspection for SCC, IGA (Intergranular Attack), wear at support plates, and tube denting. Atlantis ships steam generator tube inspection templates aligned to CSA N285.4 / ASME Section XI Division 1 equivalent. Looking forward, the Ontario Small Modular Reactor (SMR) programme &mdash; with the OPG Darlington New Nuclear Project deploying the GE Hitachi BWRX-300 (the first commercial SMR deployment in North America, planned for ~2028 commissioning) &mdash; brings a new reactor technology to Ontario. The BWRX-300 inspection workflow differs from CANDU: PWR-style steam generators replaced with natural-circulation BWR design, traditional vertical fuel bundles instead of horizontal pressure tubes. Atlantis is positioned to support both CANDU integrity work and the upcoming BWRX-300 SMR programmes from a common platform." },
];

export default function NuclearPlantTorontoCombo() {
    const structuredData = {
        "@context": "https://schema.org",
        "@graph": [
            { "@type": "Article", "headline": "Digital Twin for Toronto / Ontario Nuclear: Bruce Power, Darlington OPG [2026]", "datePublished": "2026-05-25", "dateModified": "2026-05-25", "author": { "@type": "Person", "name": "Anoop Rayavarapu" }, "publisher": { "@type": "Organization", "name": "Atlantis NDT" }, "mainEntityOfPage": { "@type": "WebPage", "@id": "https://atlantisndt.com/digital-twins/nuclear-plant-toronto" } },
            { "@type": "FAQPage", "mainEntity": faqs.map(f => ({ "@type": "Question", "name": f.question, "acceptedAnswer": { "@type": "Answer", "text": f.answer } })) }
        ]
    };
    return (
        <ProductPageLayout
            title="Digital Twin for Toronto Nuclear: Bruce Power, Darlington OPG CANDU [2026]"
            description="Toronto / Ontario CANDU digital twin: pressure tube hydride blisters, feeder FAC, steam generator tubes, CSA N285/N287/N289 + CNSC compliance. Built for Bruce + Darlington refurbishment scale. ROI $5M-$20M/yr per reactor."
            canonical="https://atlantisndt.com/digital-twins/nuclear-plant-toronto"
            eyebrow="Use Case · Location"
            h1="Atlantis Digital Twin for Ontario CANDU Reactors: Pressure Tubes, Feeders, Refurbishment [2026]"
            intro="Ontario hosts the largest concentration of operating CANDU reactors in the world &mdash; Bruce Power (8 reactors, ~6,550 MWe, the world&rsquo;s largest operating nuclear facility) and Ontario Power Generation Darlington (4 reactors, ~3,512 MWe, ongoing refurbishment). Atlantis Digital Twin handles CANDU pressure tube hydride blister inspection, feeder pipe FAC, steam generator tube integrity, and the CSA N285/N287/N289 + CNSC audit-pack workflow at refurbishment programme scale."
            heroGradient="from-emerald-700 to-teal-900"
            competitorLabel="Toronto / Ontario Nuclear Specifics"
            compareRows={compareRows}
            faqs={faqs}
            related={[
                { href: "/digital-twins/nuclear-plant", title: "Nuclear Plant Use Case", blurb: "Asset-class deep-dive." },
                { href: "/digital-twin-toronto", title: "Toronto (Location)", blurb: "Full Toronto city DT coverage page." },
                { href: "/digital-twin-canada", title: "Canada Country Coverage", blurb: "Pan-Canada DT programmes." },
                { href: "/digital-twins/heat-exchanger", title: "Heat Exchanger Use Case", blurb: "Adjacent &mdash; steam generator integrity." },
                { href: "/contact", title: "Book an Ontario Nuclear Demo", blurb: "Bring one pressure tube&rsquo;s inspection record. 30-minute demo." },
            ]}
            ctaTitle="See Your CANDU Reactor as a Live Inspection Twin"
            ctaSubtitle="Bring one pressure tube&rsquo;s inspection record and one feeder pipe FAC trend. We&rsquo;ll have it running as an Atlantis twin in a 30-minute demo at Bruce Visitor Centre or OPG Darlington offices."
            structuredData={structuredData}
            bodyChildren={
                <>
                    <h2>Why Ontario is the world&rsquo;s largest CANDU digital twin opportunity</h2>
                    <p>Ontario hosts the largest concentration of operating CANDU reactors in the world. Bruce Power operates 8 reactors at Bruce A (Units 1&ndash;4, refurbished) and Bruce B (Units 5&ndash;8, in refurbishment cycle) near Tiverton, ON, with combined capacity ~6,550 MWe &mdash; making Bruce the largest operating nuclear facility on earth by net capacity. Ontario Power Generation (OPG) operates 4 reactors at Darlington with ~3,512 MWe combined capacity, with the Darlington Refurbishment programme extending operating life beyond 2055. The OPG Pickering station (currently 4 operating reactors at Pickering B; Pickering A largely retired) is heading toward safe-store / decommissioning planning post-2026, though limited refurbishment of Pickering B Units 5&ndash;8 has been proposed. The Bruce Major Component Replacement (MCR) refurbishment programme is the largest infrastructure project in Canadian history at a forecast cost of ~CAD $13B over a multi-decade rolling cycle. The integrity engineering, inspection, and regulatory ecosystem concentrated in Toronto-Hamilton-Tiverton-Darlington is unmatched in CANDU operations globally.</p>

                    <h2>The CANDU-specific damage-mechanism stack</h2>
                    <ul>
                        <li><strong>Pressure tube hydride blister formation.</strong> Zirconium-alloy pressure tubes (Zr-2.5Nb in CANDU) absorb hydrogen during operation, leading to delayed hydride cracking (DHC) and hydride blister formation. Periodic ultrasonic and eddy-current inspection per CSA N285.5.</li>
                        <li><strong>Pressure tube wall thinning from fuel bundle wear.</strong> Fuel bundle &lsquo;flow-rotor&rsquo; mechanism causes localised pressure tube wall thinning. UT thickness mapping and dimensional measurement.</li>
                        <li><strong>End-fitting cracking.</strong> The end fittings (where pressure tubes meet the calandria headers) require periodic inspection for cracking via PT and PAUT.</li>
                        <li><strong>Calandria tube integrity.</strong> The calandria tube (outer tube containing the pressure tube in the calandria moderator tank) requires specialised inspection.</li>
                        <li><strong>Feeder pipe FAC (Flow-Accelerated Corrosion).</strong> The carbon-steel feeder pipes connecting fuel channels to the headers are highly susceptible to FAC. UT thickness mapping and CHECKWORKS analytical software integration.</li>
                        <li><strong>Steam generator tube integrity.</strong> Inconel 600 / 690 tubes with periodic eddy current inspection for SCC, IGA, wear at support plates, and tube denting.</li>
                    </ul>

                    <h2>The CSA N-series + CNSC audit-pack workflow</h2>
                    <p>CSA N285 governs periodic inspection of CANDU nuclear power plant components, with multiple parts covering different component categories: N285.1 covers pressure-retaining components, N285.4 covers in-service inspection of fuel channels, N285.5 covers pressure tubes, N285.6 covers replacement and reuse of components, N285.7 covers periodic inspection of CANDU heavy water plant pressure-retaining components, N285.8 covers periodic inspection requirements. CSA N287 covers concrete containment structures. CSA N289 covers seismic qualification of nuclear power plants. CSA N286 covers management system requirements. Atlantis ships CSA N-series audit-pack templates, with the audit pack generating from the digital twin in &lt;30 seconds, ready for CNSC inspector review. ASME Section XI Division 1 provisions apply where directly relevant (predominantly for components like steam generators where the design follows ASME conventions). IAEA safeguards reporting ties into the inspection data repository.</p>

                    <h2>Pressure tube inspection &mdash; the CANDU-defining workflow</h2>
                    <p>Each CANDU reactor contains hundreds of fuel channels, each with a Zr-2.5Nb pressure tube ~6m long. Across the Bruce 8 + Darlington 4 + Pickering operating reactors, the total Ontario pressure tube inventory exceeds 4,000 tubes. The inspection workflow for each tube includes: hydrogen ingress measurement via micro-sampling, delayed hydride cracking susceptibility assessment, UT/eddy current scans for blister formation, dimensional measurement for diameter growth and wall thinning, and the API 579 / CSA N285.5 fitness-for-service evaluation. Atlantis treats each pressure tube as a discrete asset record with full inspection history, FFS results, and the projected remaining-life calculation feeding the refurbishment / replacement planning cycle.</p>

                    <h2>Feeder pipe FAC &mdash; the other CANDU-defining workflow</h2>
                    <p>Feeder pipe Flow-Accelerated Corrosion (FAC) is one of the most important CANDU damage mechanisms, affecting the carbon-steel feeder pipes connecting fuel channels to the inlet/outlet headers. Each CANDU reactor has 600&ndash;800 feeder pipes; across Ontario&rsquo;s operating fleet that&rsquo;s 8,000+ feeder pipes requiring periodic UT thickness mapping. The CHECKWORKS analytical software (developed by EPRI and widely used in CANDU and PWR feeder FAC programmes) provides the empirical FAC rate model. Atlantis integrates CHECKWORKS outputs with the UT thickness measurement data, with the 3D twin overlaying FAC rate bands on the feeder pipe geometry. Operators report 25&ndash;40% reduction in feeder pipe inspection scope by prioritising the high-FAC-rate components and de-emphasising the low-rate ones &mdash; substantial labour and dose savings.</p>

                    <h2>The Bruce MCR and Darlington Refurbishment integration</h2>
                    <p>The Bruce MCR programme (~CAD $13B forecast) and the OPG Darlington Refurbishment programme are both massive multi-decade investments. Each replaced pressure tube has a full baseline inspection record. Each new feeder pipe has post-installation NDE. Each new steam generator has full hydro-test, PWHT, and pre-service inspection records. Atlantis Digital Twin handles the refurbishment data capture workflow: construction-vintage inspection data, baseline post-installation surveys, and the first 5&ndash;10 years of in-service inspection data &mdash; all consolidated in the twin from day one. Building the digital twin during refurbishment eliminates 6&ndash;18 months of post-startup data backfill effort and creates a defensible, single-source-of-truth integrity record for the next 30&ndash;40 years of operation.</p>

                    <h2>ROI math for a CANDU reactor deployment</h2>
                    <p>For a representative operating CANDU reactor (~860&ndash;935 MWe net capacity), Atlantis Digital Twin enterprise tier ($200K&ndash;$400K/yr per reactor) typically pays back through:</p>
                    <ul>
                        <li><strong>Refurbishment data efficiency:</strong> 6&ndash;18 months of post-startup data backfill effort eliminated = CAD $5&ndash;$15M per refurbishing reactor.</li>
                        <li><strong>Capacity factor protection:</strong> Better inspection-driven prioritisation reduces unplanned outage risk; one avoided forced outage saves CAD $2&ndash;$8M in lost generation revenue.</li>
                        <li><strong>Feeder pipe inspection scope reduction:</strong> 25&ndash;40% reduction in inspection scope by prioritising high-FAC components = CAD $500K&ndash;$2M/yr in labour and dose savings.</li>
                        <li><strong>CNSC audit-pack efficiency:</strong> 1,000&ndash;3,000 hours/yr saved in regulatory submittal preparation.</li>
                    </ul>
                    <p>Net: CAD $5M&ndash;$20M/yr per operating reactor. The Bruce 8 + Darlington 4 deployment cumulatively represents the largest single-utility CANDU digital twin opportunity in the world.</p>

                    <h2>The Ontario SMR future</h2>
                    <p>The Ontario Small Modular Reactor (SMR) programme &mdash; with the OPG Darlington New Nuclear Project deploying the GE Hitachi BWRX-300 (the first commercial SMR deployment in North America, planned for ~2028 commissioning) &mdash; brings a new reactor technology to Ontario. The BWRX-300 inspection workflow differs from CANDU: PWR-style steam generators replaced with natural-circulation BWR design, traditional vertical fuel bundles instead of horizontal pressure tubes. Atlantis is positioned to support both ongoing CANDU integrity work at Bruce and Darlington plus the upcoming BWRX-300 SMR programmes from a common platform.</p>

                    <h2>Implementation path for an Ontario nuclear operator</h2>
                    <p>First reactor live in 12&ndash;20 weeks. Coexistence with existing operator nuclear integrity tools, CHECKWORKS FAC software, the CNSC reporting infrastructure, and the operator&rsquo;s SAP / Maximo asset master. Subsequent reactors 6&ndash;10 weeks each (faster after the first because of the strong commonality between CANDU reactors of the same generation). For a full Bruce 8 or Darlington 4 deployment, the rollout typically lands in 12&ndash;24 months from kickoff to last-reactor-live. Ontario-based inspection contractors integrating with Atlantis include Kinectrics (the legacy Ontario Hydro nuclear inspection business), Stern Laboratories, Candu Energy / SNC-Lavalin Atomic Energy, AtkinsR&eacute;alis, and the in-house inspection departments at Bruce Power and OPG.</p>
                </>
            }
        />
    );
}
