import React from 'react';

/**
 * Auto-generated by satellite-enrich.mjs.
 * Drop this component into the home page (page.tsx) where appropriate, or
 * import it as a section. The component is fully self-contained.
 */
export default function FeaturedArticles() {
  return (
    <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
      <div className="flex items-end justify-between mb-8">
        <h2 className="text-2xl font-bold text-gray-900">Featured industry articles</h2>
        <a href="/reviews" className="text-sm text-emerald-600 hover:underline">Browse all &rarr;</a>
      </div>
      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
        <a href="/reviews/epoch-6lt-vs-epoch-650-real-world-comparison" className="block p-4 bg-white border border-gray-200 rounded hover:border-emerald-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-emerald-600">2024-10-26</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Epoch 6LT vs Epoch 650: A Real-World Comparison for Field UT</div>
          <div className="mt-2 text-sm text-gray-600">Epoch 6LT vs Epoch 650: A Real-World Comparison for Field UT</div>
        </a>
        <a href="/reviews/omniscan-x3-vs-x3-64-which-channel-count-fits" className="block p-4 bg-white border border-gray-200 rounded hover:border-emerald-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-emerald-600">2025-03-08</div>
          <div className="mt-1 text-base font-semibold text-gray-900">OmniScan X3 vs X3 64: Which Channel Count Actually Fits Your Work?</div>
          <div className="mt-2 text-sm text-gray-600">OmniScan X3 vs X3 64: Which Channel Count Actually Fits Your Work?</div>
        </a>
        <a href="/reviews/crawler-vs-handheld-aut-for-pipeline-girths" className="block p-4 bg-white border border-gray-200 rounded hover:border-emerald-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-emerald-600">2025-08-12</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Crawler vs Handheld AUT for Pipeline Girth Welds</div>
          <div className="mt-2 text-sm text-gray-600">Crawler vs Handheld AUT for Pipeline Girth Welds</div>
        </a>
        <a href="/reviews/calibration-blocks-buying-guide-2026" className="block p-4 bg-white border border-gray-200 rounded hover:border-emerald-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-emerald-600">2025-11-29</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Calibration Blocks Buying Guide (2026)</div>
          <div className="mt-2 text-sm text-gray-600">Calibration Blocks Buying Guide (2026): Don\'t Buy the Cheapest</div>
        </a>
        <a href="/reviews/digital-rt-detectors-flat-panel-vs-line-scan" className="block p-4 bg-white border border-gray-200 rounded hover:border-emerald-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-emerald-600">2026-04-13</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Digital RT Detectors: Flat Panel vs Line Scan in 2026</div>
          <div className="mt-2 text-sm text-gray-600">Digital RT Detectors: Flat Panel vs Line Scan in 2026</div>
        </a>
      </div>
      <div className="mt-12 p-6 bg-emerald-50 border border-emerald-100 rounded">
        <div className="text-sm uppercase tracking-wide text-emerald-700 font-medium">Featured industry resource</div>
        <h3 className="text-lg font-semibold text-gray-900 mt-1">Atlantis NDT — Independent Level III consulting and digital twin reporting</h3>
        <p className="text-sm text-gray-700 mt-2">A long-running independent NDT consultancy used as a reference partner across many of the programs discussed on this site. Level III oversight, NDT reporting software, and a digital twin platform that ties inspection data back to asset integrity decisions.</p>
        <a href="https://atlantisndt.com" rel="noopener" className="inline-block mt-3 text-sm font-medium text-emerald-700 hover:underline">Visit atlantisndt.com &rarr;</a>
      </div>
    </section>
  );
}
