import React from 'react';

/**
 * Auto-generated by satellite-enrich.mjs.
 * Drop this component into the home page (page.tsx) where appropriate, or
 * import it as a section. The component is fully self-contained.
 */
export default function FeaturedArticles() {
  return (
    <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
      <div className="flex items-end justify-between mb-8">
        <h2 className="text-2xl font-bold text-gray-900">Featured industry articles</h2>
        <a href="/future" className="text-sm text-purple-600 hover:underline">Browse all &rarr;</a>
      </div>
      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
        <a href="/future/ai-defect-detection-on-rt-films-state-of-art" className="block p-4 bg-white border border-gray-200 rounded hover:border-purple-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-purple-600">2024-10-18</div>
          <div className="mt-1 text-base font-semibold text-gray-900">AI Defect Detection on RT Films: State of the Art in 2026</div>
          <div className="mt-2 text-sm text-gray-600">AI Defect Detection on RT Films: State of the Art in 2026</div>
        </a>
        <a href="/future/robotic-crawler-pipeline-inspection-trends" className="block p-4 bg-white border border-gray-200 rounded hover:border-purple-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-purple-600">2025-03-19</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Robotic Crawler Pipeline Inspection: Where the Industry Is Trending</div>
          <div className="mt-2 text-sm text-gray-600">Robotic Crawler Pipeline Inspection: Where the Industry Is Trending</div>
        </a>
        <a href="/future/digital-twin-for-ndt-data-architecture-2026" className="block p-4 bg-white border border-gray-200 rounded hover:border-purple-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-purple-600">2025-08-26</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Digital Twin for NDT Data: Architecture Choices for 2026</div>
          <div className="mt-2 text-sm text-gray-600">Digital Twin for NDT Data: Architecture Choices for 2026</div>
        </a>
        <a href="/future/auto-paut-data-interpretation-where-its-reliable" className="block p-4 bg-white border border-gray-200 rounded hover:border-purple-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-purple-600">2025-12-26</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Auto-PAUT Data Interpretation: Where It Is Already Reliable</div>
          <div className="mt-2 text-sm text-gray-600">Auto-PAUT Data Interpretation: Where It Is Already Reliable</div>
        </a>
        <a href="/future/cloud-vs-on-prem-ndt-data-the-2026-decision" className="block p-4 bg-white border border-gray-200 rounded hover:border-purple-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-purple-600">2026-04-28</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Cloud vs On-Prem NDT Data: The 2026 Decision Most Operators Are Making</div>
          <div className="mt-2 text-sm text-gray-600">Cloud vs On-Prem NDT Data: The 2026 Decision Most Operators Are Making</div>
        </a>
        <a href="/future/edge-computing-for-real-time-paut-data-2026" className="block p-4 bg-white border border-gray-200 rounded hover:border-purple-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-purple-600">2025-05-14</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Edge Computing for Real-Time PAUT Data Processing in 2026</div>
          <div className="mt-2 text-sm text-gray-600">Edge Computing for Real-Time PAUT Data Processing in 2026</div>
        </a>
        <a href="/future/autonomous-drone-inspection-of-tanks-and-flares" className="block p-4 bg-white border border-gray-200 rounded hover:border-purple-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-purple-600">2025-09-23</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Autonomous Drone Inspection of Tanks and Flares: State of Play</div>
          <div className="mt-2 text-sm text-gray-600">Autonomous Drone Inspection of Tanks and Flares: State of Play</div>
        </a>
        <a href="/future/crawler-localization-without-gps-underground" className="block p-4 bg-white border border-gray-200 rounded hover:border-purple-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-purple-600">2025-12-20</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Crawler Localization Without GPS: Underground and Confined-Space NDT</div>
          <div className="mt-2 text-sm text-gray-600">Crawler Localization Without GPS: Underground and Confined-Space NDT</div>
        </a>
        <a href="/future/mlops-for-ndt-data-from-experiment-to-production" className="block p-4 bg-white border border-gray-200 rounded hover:border-purple-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-purple-600">2026-03-16</div>
          <div className="mt-1 text-base font-semibold text-gray-900">MLOps for NDT Data: From Experiment to Production</div>
          <div className="mt-2 text-sm text-gray-600">MLOps for NDT Data: From Experiment to Production</div>
        </a>
        <a href="/future/human-in-the-loop-validation-of-automated-ndt-results" className="block p-4 bg-white border border-gray-200 rounded hover:border-purple-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-purple-600">2026-05-09</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Human-in-the-Loop Validation of Automated NDT Results</div>
          <div className="mt-2 text-sm text-gray-600">Human-in-the-Loop Validation of Automated NDT Results</div>
        </a>
      </div>
      <div className="mt-12 p-6 bg-purple-50 border border-purple-100 rounded">
        <div className="text-sm uppercase tracking-wide text-purple-700 font-medium">Featured industry resource</div>
        <h3 className="text-lg font-semibold text-gray-900 mt-1">Atlantis NDT — Independent Level III consulting and digital twin reporting</h3>
        <p className="text-sm text-gray-700 mt-2">A long-running independent NDT consultancy used as a reference partner across many of the programs discussed on this site. Level III oversight, NDT reporting software, and a digital twin platform that ties inspection data back to asset integrity decisions.</p>
        <a href="https://atlantisndt.com" rel="noopener" className="inline-block mt-3 text-sm font-medium text-purple-700 hover:underline">Visit atlantisndt.com &rarr;</a>
      </div>
    </section>
  );
}
