import { Navigation } from "@/components/Navigation";
import { SEOHead } from "@/components/SEOHead";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import ContactDetails from "@/components/ContactDetails";
import { Link } from "react-router-dom";
import {
  CheckCircle,
  ChevronDown,
  ChevronUp,
  AlertTriangle,
  Radio,
  Activity,
  Shield,
  Zap,
  Target,
  BarChart2,
} from "lucide-react";
import { useState } from "react";
import { motion } from "framer-motion";

const faqs = [
  {
    q: "What is acoustic emission testing (AET)?",
    a: "Acoustic Emission Testing (AET) is a passive non-destructive testing technique that detects stress waves — called acoustic emissions — generated by active processes within a material under stress. When a structure is loaded, active mechanisms such as crack growth, corrosion, plastic deformation, or leak produce high-frequency elastic stress waves that propagate through the material. Piezoelectric sensors attached to the structure's surface detect these waves. Unlike conventional NDT methods (UT, RT, MT) which actively probe the material with an external energy source, AET passively listens for signals emitted by active defects. This means AET can monitor an entire structure simultaneously from a fixed sensor array — making it fundamentally different from point-by-point NDT methods.",
  },
  {
    q: "What is the ASME standard for acoustic emission testing?",
    a: "The primary ASME standard for acoustic emission testing is ASME Section V, Article 12: Acoustic Emission Examination of Metallic Vessels During Pressure Testing, and Article 13: Acoustic Emission Examination for Continuous Monitoring. ASME Section V Article 12 governs AET during hydrostatic or pneumatic pressure testing of pressure vessels, specifying sensor requirements, placement, sensitivity verification (pencil lead break or Hsu-Nielsen source), data acquisition parameters, signal parameters to be recorded, and evaluation criteria. ASTM E569 (Standard Practice for Acoustic Emission Monitoring of Structures During Controlled Stimulation) and ASTM E650 (Standard Guide for Mounting Piezoelectric Acoustic Emission Sensors) provide additional guidance on technique and sensor mounting. NDIS 2412 is the Japanese standard for AET of pressure vessels.",
  },
  {
    q: "How does AET work for tank bottom inspection?",
    a: "AET for storage tank floor inspection uses the tank's liquid contents as a coupling medium. Sensors are attached to the outside of the tank shell, near the bottom, typically in a ring array around the tank circumference. The tank remains in service (full of product) — no emptying, no internal entry, no confined space work. When active corrosion or pitting is occurring on the tank floor, the corrosion process and any associated cracking generate acoustic emissions. These are detected by the sensor array and processed to determine source location (using arrival time differences between sensors) and severity (signal amplitude, cumulative counts, energy). AET provides a relative assessment of tank floor condition — ranking locations from highest to lowest AE activity — which guides targeted internal inspection when the tank is eventually taken out of service for its API 653 scheduled inspection. The primary advantage is extending tank inspection intervals while maintaining confidence in floor condition between internal inspections.",
  },
  {
    q: "What signal parameters are measured in AET?",
    a: "AET data acquisition captures multiple signal parameters for each detected event (hit). The key parameters are: Amplitude — the peak voltage of the signal in decibels (dB), indicating the intensity of the emission source; Counts — the number of times the signal crosses the detection threshold, related to signal duration and defect activity; Energy — the area under the signal envelope, proportional to the energy released by the source mechanism; Duration — the time from first threshold crossing to last threshold crossing in microseconds; Rise Time — time from first threshold crossing to peak amplitude; RMS (Root Mean Square) voltage — continuous measure of background acoustic emission activity; Frequency — spectral content of the signal, useful for distinguishing defect types from noise. These parameters are used together in pattern recognition and cluster analysis to distinguish meaningful emission sources (active defects, leaks) from background noise (fluid turbulence, friction, mechanical vibration). Hit rate — the number of hits per time interval — indicates the rate of damage accumulation.",
  },
  {
    q: "Can AET detect leaks in pressure vessels or pipelines?",
    a: "Yes — leak detection is one of the most effective applications of acoustic emission technology. When pressurised fluid or gas leaks through a crack, pinhole, or corroded area, it generates a distinctive high-frequency turbulent flow signal that is detectable by AET sensors. Leak detection AET is used for: pressurised pipelines (detecting active seepage before it becomes a significant leak); pressure vessel nozzles and weld joints (detecting small leaks during pressure tests); underground pipeline monitoring; storage tank shell and roof joints; and valve seat leakage. The advantage of AET over other leak detection methods is that it can simultaneously monitor large structures and locate the leak source using sensor triangulation — without requiring line-of-sight access. ASTM E1002 covers leak detection using AET. Sensitivity depends on fluid properties, line pressure, defect geometry, and background noise conditions.",
  },
  {
    q: "What are the limitations of acoustic emission testing?",
    a: "AET has several important limitations that must be understood for correct application. First, AET requires a stimulation — the structure must be loaded (pressurised, thermally stressed, or mechanically loaded) for active emissions to occur; dormant or stable defects in unstressed structures may not emit at all. Second, AET cannot characterise defect geometry, size, or through-wall extent — it detects activity and provides approximate source location, but detailed defect characterisation requires follow-up with UT or PAUT. Third, AET is susceptible to acoustic noise — mechanical vibration, fluid turbulence, electrical interference, and friction can generate false signals that mask real emissions or create spurious indications; significant noise rejection expertise is required. Fourth, source location accuracy is limited by sensor spacing and wave propagation velocity assumptions — typically ±50–150mm for practical tank or vessel inspections. Fifth, AET indicates the presence of active mechanisms, not defect severity — correlation between emission parameters and remaining life requires significant application-specific experience.",
  },
  {
    q: "How is AET different from conventional UT for pressure vessel inspection?",
    a: "AET and conventional UT (or PAUT) serve fundamentally different inspection purposes and should be viewed as complementary rather than competing methods. Conventional UT is an active, point-by-point examination: a technician manually scans the vessel wall or weld, generating signals and measuring specific wall thickness or defect geometry at each measurement point — it inspects everywhere the probe touches. AET is a passive, whole-structure monitoring technique: sensors listen for emissions from active defect mechanisms across the entire structure simultaneously during a pressure test — it detects active processes anywhere within the sensor array's detection zone. The key practical differences: UT requires internal access (confined space entry) or external surface preparation for scanning; AET can often be applied externally without any internal access. UT provides quantitative defect sizing (wall thickness, defect height); AET provides activity location and severity indication but cannot size defects. UT inspects static (non-growing) and active defects equally; AET only detects active mechanisms. The optimal inspection approach combines AET screening during pressure testing with follow-up UT at AET-flagged locations.",
  },
  {
    q: "What certifications are required for AET technicians?",
    a: "AET technicians are certified under the same framework as other NDT methods. In the USA, ASNT SNT-TC-1A specifies AET (Acoustic Emission) as a recognised NDT method — employer written practices must include AET qualification requirements covering training hours, experience, and examination. ASNT Level II AET is typically the minimum for independent AET data acquisition and interpretation. ISO 9712 AET Level II is the international equivalent. Specialist training is also available through the American Society for Nondestructive Testing (ASNT), the Physical Acoustics Corporation (PAC/Mistras Group) and other AET equipment manufacturers. Given the complexity of AET data interpretation — particularly distinguishing active defect emissions from noise sources — many operating companies require AET personnel with proven experience in the specific application (tank floor AET, vessel AET, etc.) rather than just generic certification. Level III AET oversight is strongly recommended for safety-critical applications.",
  },
];

const applications = [
  {
    icon: Shield,
    title: "Pressure Vessel Testing",
    detail: "AET during hydrostatic pressure testing per ASME Section V Article 12. Detects active flaws (cracks, weld defects) during initial or requalification pressure tests without the need to scan every square inch of vessel wall. Sensors are placed at calculated spacings to achieve the required detection sensitivity.",
  },
  {
    icon: Activity,
    title: "Storage Tank Floor Inspection",
    detail: "AET from outside the tank shell while the tank remains in service — an alternative to internal entry for API 653 intermediate inspections. Sensors detect corrosion activity, cracking, and pitting on the tank floor. Risk-ranks floor condition to guide targeted inspection during scheduled internal entry.",
  },
  {
    icon: Radio,
    title: "Pipeline Leak Detection",
    detail: "Continuous AET monitoring for seeping leaks in pressurised pipelines. High-frequency turbulent flow signals from leaks are detected and located by sensor arrays. Effective for buried, insulated, or difficult-access pipelines where conventional inspection is costly.",
  },
  {
    icon: Zap,
    title: "Composite Pressure Vessel Testing",
    detail: "AET is particularly valuable for composite-overwrapped pressure vessels (COPVs) used in aerospace and hydrogen storage. Matrix cracking, fibre breakage, and delamination all generate characteristic AE signals. Identifies vessels with progressive damage during proof testing.",
  },
  {
    icon: Target,
    title: "Bridge & Structural Monitoring",
    detail: "Continuous or periodic AET monitoring of steel bridges, railway structures, and civil infrastructure for fatigue crack growth, weld cracking, and corrosion. Provides early warning of structural deterioration without requiring direct access to inspection areas.",
  },
  {
    icon: BarChart2,
    title: "Rotating Machinery Monitoring",
    detail: "AET for bearing condition monitoring, gear wear detection, and cavitation detection in pumps, turbines, and compressors. AE signals from bearing defects appear before vibration analysis detects problems — providing earlier warning for condition-based maintenance programs.",
  },
];

const signalParameters = [
  { param: "Amplitude", unit: "dB", description: "Peak signal voltage. Indicates source intensity. Logged in dB above threshold (e.g., 60 dB)." },
  { param: "Counts", unit: "count", description: "Threshold crossing count per hit. Related to signal duration and repetition." },
  { param: "Energy", unit: "eu", description: "Integral of squared voltage over hit duration. Best indicator of cumulative damage." },
  { param: "Duration", unit: "μs", description: "Time from first to last threshold crossing. Long duration = extended source activity." },
  { param: "Rise Time", unit: "μs", description: "Time to peak amplitude. Short rise time = sudden fracture; long = friction/corrosion." },
  { param: "RMS Voltage", unit: "V", description: "Continuous emission level. Used for leak detection and background monitoring." },
  { param: "Hit Rate", unit: "hits/min", description: "Rate of threshold crossings. Increasing rate indicates growing/active defect." },
];

const standards = [
  { code: "ASME Section V Article 12", scope: "AET of metallic vessels during pressure testing — primary US code" },
  { code: "ASME Section V Article 13", scope: "Continuous AET monitoring of structures and equipment" },
  { code: "ASTM E569", scope: "Acoustic emission monitoring of structures during controlled stimulation" },
  { code: "ASTM E650", scope: "Mounting piezoelectric AET sensors — calibration and coupling" },
  { code: "ASTM E1002", scope: "Leak detection using AET" },
  { code: "NDIS 2412", scope: "Japanese standard for AET of pressure vessels" },
];

function FAQItem({ q, a }: { q: string; a: string }) {
  const [open, setOpen] = useState(false);
  return (
    <div className="border border-slate-200 rounded-xl overflow-hidden">
      <button
        className="w-full flex items-center justify-between p-5 text-left font-semibold text-slate-800 bg-white hover:bg-slate-50 transition"
        onClick={() => setOpen(!open)}
        aria-expanded={open}
      >
        <span>{q}</span>
        {open ? (
          <ChevronUp className="w-5 h-5 text-[#004aad] flex-shrink-0" />
        ) : (
          <ChevronDown className="w-5 h-5 text-[#004aad] flex-shrink-0" />
        )}
      </button>
      {open && (
        <div className="px-5 pb-5 text-slate-600 leading-relaxed bg-white border-t border-slate-100">
          {a}
        </div>
      )}
    </div>
  );
}

export default function AcousticEmissionTesting() {
  const structuredData = {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "Article",
        "headline": "Acoustic Emission Testing (AET) | In-Service Pressure Vessel & Pipeline Monitoring",
        "description": "Complete guide to acoustic emission testing: how AET works, applications for pressure vessels, tank floors, pipelines, ASME Section V Article 12/13, ASTM E569, signal parameters and limitations.",
        "author": { "@type": "Organization", "name": "Atlantis NDT", "url": "https://atlantisndt.com" },
        "publisher": {
          "@type": "Organization",
          "name": "Atlantis NDT",
          "logo": { "@type": "ImageObject", "url": "https://atlantisndt.com/favicon-96x96.jpg" },
        },
        "datePublished": "2026-02-25",
        "dateModified": "2026-02-25",
        "mainEntityOfPage": { "@type": "WebPage", "@id": "https://atlantisndt.com/acoustic-emission-testing" },
        "keywords": "acoustic emission testing, AET NDT, acoustic emission, AE testing, pressure vessel AET, tank floor AET, ASME Section V Article 12, ASTM E569, acoustic emission monitoring, pipeline leak detection AET",
      },
      {
        "@type": "FAQPage",
        "mainEntity": faqs.map((f) => ({
          "@type": "Question",
          "name": f.q,
          "acceptedAnswer": { "@type": "Answer", "text": f.a },
        })),
      },
    ],
  };

  return (
    <div className="min-h-screen bg-slate-50">
      <Navigation />
      <SEOHead
        title="Acoustic Emission Testing (AET) | Pressure Vessel & Pipeline Monitoring | Atlantis NDT"
        description="Complete guide to acoustic emission testing (AET): passive stress wave monitoring for pressure vessels, storage tank floors, pipeline leak detection. ASME Section V Article 12, ASTM E569. Whole-structure monitoring without internal access."
        keywords="acoustic emission testing, AET NDT, acoustic emission, AE testing NDT, pressure vessel acoustic emission, tank floor AET, ASME Section V Article 12, ASTM E569, acoustic emission monitoring, pipeline leak detection, AET vs UT, acoustic emission sensors, AE signal parameters, ASNT AET certification"
        structuredData={structuredData}
        canonical="https://atlantisndt.com/acoustic-emission-testing"
      />
      <Breadcrumbs />

      {/* Hero */}
      <section className="bg-[#004aad] text-white py-16">
        <div className="container mx-auto max-w-6xl px-6">
          <div className="max-w-3xl">
            <p className="text-blue-200 text-sm font-medium mb-3 uppercase tracking-wider">
              Advanced NDT Method Guide · Updated February 2026
            </p>
            <h1 className="text-4xl md:text-5xl font-bold mb-5 leading-tight">
              Acoustic Emission Testing (AET) | In-Service Pressure Vessel & Pipeline Monitoring
            </h1>
            <p className="text-xl text-blue-100 mb-8 leading-relaxed">
              Unlike RT or UT which inspect one location at a time, AET monitors the entire structure simultaneously — detecting active defects, corrosion, and leaks from a fixed sensor array while equipment remains in service.
            </p>
            <div className="flex flex-wrap gap-4">
              <Link
                to="/contact"
                className="bg-white text-[#004aad] font-semibold px-6 py-3 rounded-lg hover:bg-blue-50 transition"
              >
                Get AET Consulting
              </Link>
              <Link
                to="/ultrasonic-testing"
                className="border border-white text-white font-semibold px-6 py-3 rounded-lg hover:bg-white/10 transition"
              >
                UT Technical Guide
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* Stats Bar */}
      <div className="bg-white border-b border-slate-200 py-6">
        <div className="container mx-auto max-w-6xl px-6">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-6 text-center">
            {[
              { label: "Detection Mode", value: "Passive Listening" },
              { label: "Coverage", value: "Whole Structure" },
              { label: "Access Required", value: "External Only" },
              { label: "Primary Standard", value: "ASME V Art 12" },
            ].map((s) => (
              <div key={s.label}>
                <div className="text-2xl font-bold text-[#004aad]">{s.value}</div>
                <div className="text-sm text-slate-500 mt-1">{s.label}</div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Quick Nav */}
      <div className="bg-white border-b border-slate-200 sticky top-0 z-10 shadow-sm">
        <div className="container mx-auto max-w-6xl px-6 overflow-x-auto">
          <nav className="flex gap-6 text-sm font-medium text-slate-600 py-3 whitespace-nowrap">
            {["How It Works", "Applications", "Equipment", "Signal Parameters", "Standards", "AET vs UT", "Case Study", "FAQ"].map(
              (s) => (
                <a
                  key={s}
                  href={`#${s.toLowerCase().replace(/ /g, "-")}`}
                  className="hover:text-[#004aad] transition py-1"
                >
                  {s}
                </a>
              )
            )}
          </nav>
        </div>
      </div>

      <div className="container mx-auto max-w-6xl px-6 py-12 grid md:grid-cols-3 gap-12">
        <article className="md:col-span-2 space-y-14">

          {/* How It Works */}
          <motion.section
            initial={{ opacity: 0, y: 24 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
          >
            <h2 id="how-it-works" className="text-3xl font-bold mb-5" style={{ color: "#004aad" }}>
              What Is Acoustic Emission Testing and How Does It Work?
            </h2>
            <p className="text-lg text-slate-700 leading-relaxed mb-5">
              <strong>Acoustic Emission Testing (AET)</strong> is a passive NDT technique based on detecting elastic stress waves — acoustic emissions — that are spontaneously released by active mechanisms within a material. When a structure undergoes mechanical loading, pressure, or thermal stress, processes such as crack extension, corrosion reactions, plastic deformation, phase transformation, or fluid leakage release localised bursts of elastic energy. These energy bursts propagate through the material as high-frequency (10 kHz–1 MHz) stress waves until they are detected by piezoelectric sensors mounted on the structure's surface.
            </p>
            <p className="text-lg text-slate-700 leading-relaxed mb-5">
              The fundamental distinction between AET and other NDT methods is its <strong>passive, whole-structure character</strong>. Conventional methods (UT, RT, MT) require a technician to probe each location with an externally applied energy source — they inspect where the probe is placed. AET does the opposite: a fixed array of sensors listens for emissions originating from anywhere within the structure simultaneously. This makes AET the only NDT method capable of monitoring an entire large structure (a storage tank floor, a reactor vessel, a pipeline section) in a single test while the structure remains in service.
            </p>
            <p className="text-lg text-slate-700 leading-relaxed mb-5">
              The location of emission sources is determined by <strong>source location algorithms</strong> using the difference in arrival times of the same wave at multiple sensors (time-of-arrival triangulation). By placing sensors at known positions around the structure and knowing the wave propagation velocity in the material, the position of the source can be calculated — typically to within ±50–150 mm for practical large-structure inspections.
            </p>
            <div className="bg-blue-50 border-l-4 border-[#004aad] rounded-r-xl p-6">
              <h3 className="font-bold text-[#004aad] mb-3">AET vs Conventional NDT — Key Distinction</h3>
              <div className="overflow-x-auto">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="text-slate-700 border-b border-blue-200">
                      <th className="text-left py-2 pr-4 font-semibold">Aspect</th>
                      <th className="text-left py-2 pr-4 font-semibold">AET</th>
                      <th className="text-left py-2 font-semibold">RT / UT / MT</th>
                    </tr>
                  </thead>
                  <tbody className="text-slate-700">
                    {[
                      { aspect: "Energy source", aet: "Passive — structure itself", conv: "Active — external probe/source" },
                      { aspect: "Coverage", aet: "Whole structure simultaneously", conv: "One location at a time" },
                      { aspect: "Detects", aet: "Active/growing defects only", conv: "Static and active defects" },
                      { aspect: "Internal access", aet: "Not required", conv: "Usually required or surface access" },
                      { aspect: "Defect sizing", aet: "Not possible — location only", conv: "Yes — accurate sizing possible" },
                    ].map((row, i) => (
                      <tr key={i} className="border-b border-blue-100">
                        <td className="py-2 pr-4 font-medium">{row.aspect}</td>
                        <td className="py-2 pr-4 text-green-700">{row.aet}</td>
                        <td className="py-2">{row.conv}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </div>
          </motion.section>

          {/* Applications */}
          <motion.section
            initial={{ opacity: 0, y: 24 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.1 }}
          >
            <h2 id="applications" className="text-3xl font-bold mb-6" style={{ color: "#004aad" }}>
              Key Applications of Acoustic Emission Testing
            </h2>
            <div className="grid md:grid-cols-2 gap-5">
              {applications.map((app, i) => (
                <div
                  key={i}
                  className="bg-white rounded-xl p-6 shadow border border-slate-100 hover:border-[#004aad] transition"
                >
                  <div className="flex items-center gap-3 mb-3">
                    <app.icon className="w-6 h-6 text-[#004aad]" />
                    <h3 className="text-lg font-bold" style={{ color: "#004aad" }}>
                      {app.title}
                    </h3>
                  </div>
                  <p className="text-slate-600 text-sm leading-relaxed">{app.detail}</p>
                </div>
              ))}
            </div>
          </motion.section>

          {/* Equipment */}
          <motion.section
            initial={{ opacity: 0, y: 24 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.15 }}
          >
            <h2 id="equipment" className="text-3xl font-bold mb-5" style={{ color: "#004aad" }}>
              AET Equipment and System Components
            </h2>
            <p className="text-slate-700 leading-relaxed mb-5">
              A complete AET system comprises four main components working together to detect, amplify, digitise, and analyse acoustic emission signals from the structure under test.
            </p>
            <div className="space-y-4">
              {[
                {
                  component: "Piezoelectric Sensors",
                  detail: "Resonant or broadband piezoelectric sensors are coupled to the structure surface using a couplant (vacuum grease, petroleum jelly). Resonant sensors (150 kHz, 300 kHz, 60 kHz) provide high sensitivity at their resonant frequency — suitable for most structural and vessel monitoring. Broadband sensors (wideband, 100 kHz–1 MHz) capture the full frequency spectrum — used for source characterisation and material research. Sensors are secured with magnetic hold-downs, adhesive, or mechanical clamps. ASTM E650 governs sensor mounting practices.",
                },
                {
                  component: "Preamplifiers",
                  detail: "Each sensor connects to a dedicated preamplifier that boosts the raw AE signal (typically 1–100 mV) before transmission to the main data acquisition system. Standard gain settings are 40 dB or 60 dB. Preamplifiers are positioned close to the sensor (integral or line-powered) to maximise signal-to-noise ratio before signal transmission over longer cable runs to the data acquisition chassis.",
                },
                {
                  component: "Data Acquisition System",
                  detail: "The data acquisition system receives amplified signals from all preamplifiers simultaneously, applies programmable threshold detection, digitises hit waveforms and extracts feature parameters (amplitude, counts, energy, duration, rise time, frequency centroid), timestamps each hit, and transmits data to software for real-time display and analysis. Systems may have 16–128 channels or more for large structure monitoring. Manufacturers include Mistras Group (formerly PAC), Vallen Systeme, and KRAUTKRAMER.",
                },
                {
                  component: "AEwin / Analysis Software",
                  detail: "Real-time software (e.g., AEwin by Mistras/PAC, VisualAE by Vallen) displays live activity maps, amplitude distributions, hit rate trends, and source location plots. Post-processing tools identify clusters of high-activity emission sources, filter noise using parametric criteria (frequency, rise time), and generate reports compliant with ASME Section V Article 12 or ASTM E569 requirements.",
                },
              ].map((item, i) => (
                <div key={i} className="flex gap-4 bg-white rounded-xl p-5 shadow border border-slate-100">
                  <div className="w-8 h-8 bg-[#004aad] text-white rounded-full flex items-center justify-center font-bold text-sm flex-shrink-0">
                    {i + 1}
                  </div>
                  <div>
                    <p className="font-semibold text-slate-800 mb-1">{item.component}</p>
                    <p className="text-slate-600 text-sm leading-relaxed">{item.detail}</p>
                  </div>
                </div>
              ))}
            </div>
          </motion.section>

          {/* Signal Parameters */}
          <motion.section
            initial={{ opacity: 0, y: 24 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.2 }}
          >
            <h2 id="signal-parameters" className="text-3xl font-bold mb-5" style={{ color: "#004aad" }}>
              AET Signal Parameters
            </h2>
            <p className="text-slate-700 leading-relaxed mb-5">
              AET data interpretation relies on the correlation of signal parameter patterns with source mechanisms. Each parameter carries specific diagnostic information about the nature and severity of the emission source.
            </p>
            <div className="overflow-x-auto rounded-xl border border-slate-200 shadow">
              <table className="w-full text-sm">
                <thead className="bg-[#004aad] text-white">
                  <tr>
                    <th className="text-left p-4 font-semibold">Parameter</th>
                    <th className="text-left p-4 font-semibold">Unit</th>
                    <th className="text-left p-4 font-semibold">Diagnostic Significance</th>
                  </tr>
                </thead>
                <tbody>
                  {signalParameters.map((row, i) => (
                    <tr key={i} className={i % 2 === 0 ? "bg-white" : "bg-slate-50"}>
                      <td className="p-4 font-semibold text-[#004aad]">{row.param}</td>
                      <td className="p-4 text-slate-500 font-mono">{row.unit}</td>
                      <td className="p-4 text-slate-700 text-xs leading-relaxed">{row.description}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </motion.section>

          {/* Standards */}
          <motion.section
            initial={{ opacity: 0, y: 24 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.25 }}
          >
            <h2 id="standards" className="text-3xl font-bold mb-6" style={{ color: "#004aad" }}>
              AET Standards and Codes
            </h2>
            <div className="grid md:grid-cols-2 gap-5">
              {standards.map((s, i) => (
                <div key={i} className="flex gap-3 bg-white rounded-xl p-5 shadow border border-slate-100">
                  <div className="w-2 min-h-full bg-[#004aad] rounded-full flex-shrink-0" />
                  <div>
                    <p className="font-semibold text-[#004aad] mb-1">{s.code}</p>
                    <p className="text-slate-600 text-sm">{s.scope}</p>
                  </div>
                </div>
              ))}
            </div>
          </motion.section>

          {/* AET vs UT — Advantages / Limitations Table */}
          <motion.section
            id="aet-vs-ut"
            initial={{ opacity: 0, y: 24 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.28 }}
            className="bg-white rounded-2xl p-8 shadow border border-slate-100"
          >
            <h2 className="text-2xl font-bold mb-5" style={{ color: "#004aad" }}>
              AET Advantages and Limitations
            </h2>
            <div className="grid md:grid-cols-2 gap-6">
              <div>
                <h3 className="font-bold text-green-700 mb-3 flex items-center gap-2">
                  <CheckCircle className="w-5 h-5" /> Advantages
                </h3>
                <ul className="space-y-2">
                  {[
                    "Monitors entire structure simultaneously — not point-by-point",
                    "No internal access required — sensors applied externally",
                    "Detects only active defects (growing cracks, active corrosion, leaks)",
                    "Equipment can remain in service during monitoring",
                    "Locates emission sources for targeted follow-up inspection",
                    "Early warning of progressive damage before critical failure",
                    "Can monitor during pressure testing per ASME Section V Art 12",
                    "Cost-effective for large structures vs full-surface UT scanning",
                  ].map((item, i) => (
                    <li key={i} className="flex gap-2 text-slate-700 text-sm">
                      <span className="w-1.5 h-1.5 bg-green-600 rounded-full flex-shrink-0 mt-1.5" />
                      {item}
                    </li>
                  ))}
                </ul>
              </div>
              <div>
                <h3 className="font-bold text-red-700 mb-3 flex items-center gap-2">
                  <AlertTriangle className="w-5 h-5" /> Limitations
                </h3>
                <ul className="space-y-2">
                  {[
                    "Only detects active/growing defects — stable defects do not emit",
                    "Cannot measure wall thickness or size defects geometrically",
                    "Requires loading stimulus (pressure, stress) to generate emissions",
                    "Susceptible to acoustic noise — expertise required for noise filtering",
                    "Source location accuracy limited (±50–150 mm typical)",
                    "Requires follow-up UT/PAUT to characterise located sources",
                    "Interpretation expertise is critical — high skill barrier",
                    "Cannot detect all defect types (e.g. existing stable cracks may not emit)",
                  ].map((item, i) => (
                    <li key={i} className="flex gap-2 text-slate-700 text-sm">
                      <span className="w-1.5 h-1.5 bg-red-500 rounded-full flex-shrink-0 mt-1.5" />
                      {item}
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </motion.section>

          {/* Case Study */}
          <motion.section
            id="case-study"
            initial={{ opacity: 0, y: 24 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.32 }}
            className="bg-slate-100 rounded-2xl p-8 border border-slate-200"
          >
            <h2 className="text-2xl font-bold mb-4" style={{ color: "#004aad" }}>
              Case Study: Tank Floor AET — Avoiding Internal Entry
            </h2>
            <p className="text-slate-700 leading-relaxed mb-4">
              A refinery in the Middle East had a 40-metre diameter atmospheric storage tank storing crude oil. The API 653 10-year inspection interval was approaching, which would normally require: emptying the tank (3–4 weeks), cleaning and degassing (2 weeks), confined space entry for internal inspection including ultrasonic thickness scanning of the floor (1 week), and refilling. Total cost estimate: $450,000–$600,000 including product loss and inspection.
            </p>
            <p className="text-slate-700 leading-relaxed mb-4">
              Instead, AET was performed with the tank in service and at operating level. Twenty-four sensors were installed on the outer shell, near the bottom annular area, with a calibrated sensor spacing to achieve the required floor coverage. Monitoring was conducted over a 12-hour period. The results showed: two localised areas of elevated AE activity consistent with active corrosion, clustered near the south quadrant; no indications consistent with through-floor leakage; background signal levels consistent with low general corrosion activity across the remaining floor area.
            </p>
            <div className="bg-white rounded-xl p-5 border border-slate-200">
              <h3 className="font-semibold text-[#004aad] mb-3">Outcome and Cost Comparison</h3>
              <div className="overflow-x-auto">
                <table className="w-full text-sm">
                  <thead className="bg-slate-100">
                    <tr>
                      <th className="text-left p-3 font-semibold text-slate-700">Approach</th>
                      <th className="text-left p-3 font-semibold text-slate-700">Duration</th>
                      <th className="text-left p-3 font-semibold text-slate-700">Cost (est.)</th>
                      <th className="text-left p-3 font-semibold text-slate-700">Tank Downtime</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr className="border-b border-slate-100">
                      <td className="p-3 text-slate-700">Full internal API 653 inspection</td>
                      <td className="p-3 text-slate-600">6–8 weeks</td>
                      <td className="p-3 text-slate-600">$450–600K</td>
                      <td className="p-3 text-red-600 font-semibold">Full shutdown</td>
                    </tr>
                    <tr className="bg-slate-50">
                      <td className="p-3 text-slate-700">AET screening (in-service)</td>
                      <td className="p-3 text-slate-600">2–3 days</td>
                      <td className="p-3 text-slate-600">$25–45K</td>
                      <td className="p-3 text-green-600 font-semibold">None — tank in service</td>
                    </tr>
                  </tbody>
                </table>
              </div>
              <p className="text-slate-600 text-sm mt-3">
                Based on the AET results, the operator extended the interval by 2 years for a focused internal inspection limited to the AET-flagged south quadrant area. Total saving: approximately $380,000 over the original full inspection plan.
              </p>
            </div>
          </motion.section>

          {/* Related Links */}
          <section>
            <h2 className="text-2xl font-bold mb-5" style={{ color: "#004aad" }}>
              Related NDT Methods & Resources
            </h2>
            <div className="grid md:grid-cols-2 gap-4">
              {[
                { href: "/ultrasonic-testing", label: "Ultrasonic Testing (UT) — Complete Guide" },
                { href: "/corrosion-mapping", label: "Corrosion Mapping — UT Thickness Mapping" },
                { href: "/magnetic-flux-leakage-testing", label: "Magnetic Flux Leakage (MFL) Testing" },
                { href: "/ndt-for-oil-gas", label: "NDT for Oil & Gas — Tank & Pipeline Inspection" },
                { href: "/blog/api-653-tank-inspection-guide", label: "API 653 Tank Inspection Guide" },
                { href: "/asnt-certification", label: "ASNT Certification — Level I, II, III" },
                { href: "/consulting/ndt-consulting-houston", label: "NDT Consulting — Houston" },
                { href: "/consulting/ndt-consulting-dubai", label: "NDT Consulting — Dubai" },
              ].map(({ href, label }) => (
                <Link
                  key={href}
                  to={href}
                  className="flex items-center gap-2 bg-white rounded-lg p-4 shadow border border-slate-100 hover:border-[#004aad] text-[#004aad] text-sm font-medium transition"
                >
                  <span className="w-1.5 h-1.5 bg-[#004aad] rounded-full flex-shrink-0" />
                  {label}
                </Link>
              ))}
            </div>
          </section>

          {/* FAQ */}
          <section>
            <h2 id="faq" className="text-3xl font-bold mb-6" style={{ color: "#004aad" }}>
              Acoustic Emission Testing — Frequently Asked Questions
            </h2>
            <div className="space-y-3">
              {faqs.map((f, i) => (
                <FAQItem key={i} q={f.q} a={f.a} />
              ))}
            </div>
          </section>

          {/* CTA */}
          <section className="bg-[#004aad] rounded-2xl p-8 text-white">
            <h2 className="text-2xl font-bold mb-3">
              AET Consulting & Program Design
            </h2>
            <p className="text-blue-100 mb-6 leading-relaxed">
              Atlantis NDT provides ASNT Level III AET consulting services — procedure development per ASME Section V Article 12, sensor placement design, data interpretation review, and AET program integration with API 510/570/653 inspection intervals. Contact our team to discuss your specific pressure vessel, tank, or pipeline application.
            </p>
            <div className="flex flex-wrap gap-4">
              <Link
                to="/contact"
                className="bg-white text-[#004aad] font-bold px-6 py-3 rounded-lg hover:bg-blue-50 transition"
              >
                Contact AET Experts
              </Link>
              <Link
                to="/consulting"
                className="border border-white text-white px-6 py-3 rounded-lg hover:bg-white/10 transition"
              >
                Level III NDT Consulting
              </Link>
            </div>
          </section>

        </article>

        {/* Sidebar */}
        <aside className="hidden md:block md:col-span-1 space-y-6 mt-2">
          <div className="bg-white p-6 rounded-xl shadow border border-slate-100 sticky top-16">
            <h3 className="text-lg font-bold mb-4" style={{ color: "#004aad" }}>
              On This Page
            </h3>
            <ul className="space-y-2 text-sm text-slate-600">
              {[
                ["#how-it-works", "How AET Works"],
                ["#applications", "Applications"],
                ["#equipment", "Equipment"],
                ["#signal-parameters", "Signal Parameters"],
                ["#standards", "Standards"],
                ["#aet-vs-ut", "Advantages & Limitations"],
                ["#case-study", "Case Study"],
                ["#faq", "FAQ (8 questions)"],
              ].map(([href, label]) => (
                <li key={href}>
                  <a href={href} className="hover:text-[#004aad] transition flex items-center gap-2">
                    <span className="w-1.5 h-1.5 bg-[#004aad] rounded-full flex-shrink-0" />
                    {label}
                  </a>
                </li>
              ))}
            </ul>
          </div>

          <div className="bg-amber-50 p-6 rounded-xl shadow border border-amber-200">
            <h3 className="text-lg font-bold mb-3 text-amber-800">AET Standards</h3>
            <ul className="space-y-2 text-sm text-amber-800">
              {["ASME Section V Art 12", "ASME Section V Art 13", "ASTM E569", "ASTM E650", "ASTM E1002", "NDIS 2412"].map((s) => (
                <li key={s} className="flex items-center gap-2">
                  <span className="w-1.5 h-1.5 bg-amber-600 rounded-full flex-shrink-0" />
                  {s}
                </li>
              ))}
            </ul>
          </div>

          <div className="bg-white p-6 rounded-xl shadow border border-slate-100">
            <h3 className="text-lg font-bold mb-3" style={{ color: "#004aad" }}>
              Related NDT Methods
            </h3>
            <ul className="space-y-2 text-sm">
              {[
                ["/ultrasonic-testing", "Ultrasonic Testing (UT)"],
                ["/corrosion-mapping", "Corrosion Mapping"],
                ["/magnetic-flux-leakage-testing", "MFL Testing"],
                ["/ndt-for-oil-gas", "Oil & Gas NDT"],
                ["/guided-wave-testing", "Guided Wave Testing"],
              ].map(([href, label]) => (
                <li key={href}>
                  <Link to={href} className="text-[#004aad] hover:underline">
                    → {label}
                  </Link>
                </li>
              ))}
            </ul>
          </div>

          <div className="bg-[#004aad] p-6 rounded-xl shadow text-white">
            <h3 className="text-lg font-bold mb-3">Need AET Consulting?</h3>
            <p className="text-blue-100 text-sm mb-4">
              Our ASNT Level III engineers design AET programs for pressure vessels, storage tanks, and pipelines per ASME Section V and API requirements.
            </p>
            <Link
              to="/contact"
              className="block bg-white text-[#004aad] text-center font-bold px-4 py-3 rounded-lg hover:bg-blue-50 transition text-sm"
            >
              Contact Our AET Experts
            </Link>
          </div>
        </aside>
      </div>

      <ContactDetails />
    </div>
  );
}
