import React from 'react';

/**
 * Auto-generated by satellite-enrich.mjs.
 * Drop this component into the home page (page.tsx) where appropriate, or
 * import it as a section. The component is fully self-contained.
 */
export default function FeaturedArticles() {
  return (
    <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
      <div className="flex items-end justify-between mb-8">
        <h2 className="text-2xl font-bold text-gray-900">Featured industry articles</h2>
        <a href="/study" className="text-sm text-orange-600 hover:underline">Browse all &rarr;</a>
      </div>
      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
        <a href="/study/api-570-piping-inspector-study-plan-2026" className="block p-4 bg-white border border-gray-200 rounded hover:border-orange-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-orange-600">2024-09-12</div>
          <div className="mt-1 text-base font-semibold text-gray-900">API 570 Piping Inspector Study Plan (2026)</div>
          <div className="mt-2 text-sm text-gray-600">API 570 Piping Inspector Study Plan (2026)</div>
        </a>
        <a href="/study/api-653-aboveground-tank-inspector-prep" className="block p-4 bg-white border border-gray-200 rounded hover:border-orange-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-orange-600">2025-01-22</div>
          <div className="mt-1 text-base font-semibold text-gray-900">API 653 Aboveground Tank Inspector Prep: What the Exam Actually Tests</div>
          <div className="mt-2 text-sm text-gray-600">API 653 Aboveground Tank Inspector Prep: What the Exam Actually Tests</div>
        </a>
        <a href="/study/api-510-vs-api-570-which-cert-first" className="block p-4 bg-white border border-gray-200 rounded hover:border-orange-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-orange-600">2025-05-14</div>
          <div className="mt-1 text-base font-semibold text-gray-900">API 510 vs API 570: Which Certification Should You Take First?</div>
          <div className="mt-2 text-sm text-gray-600">API 510 vs API 570: Which Certification Should You Take First?</div>
        </a>
        <a href="/study/api-icp-recertification-2-cycle-cycle" className="block p-4 bg-white border border-gray-200 rounded hover:border-orange-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-orange-600">2025-10-30</div>
          <div className="mt-1 text-base font-semibold text-gray-900">API ICP Recertification: Surviving the 3-Year Cycle</div>
          <div className="mt-2 text-sm text-gray-600">API ICP Recertification: Surviving the 3-Year Cycle</div>
        </a>
        <a href="/study/open-book-questions-api-510-test-strategy" className="block p-4 bg-white border border-gray-200 rounded hover:border-orange-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-orange-600">2026-03-25</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Open-Book Questions in API 510: A Test-Day Strategy</div>
          <div className="mt-2 text-sm text-gray-600">Open-Book Questions in API 510: A Test-Day Strategy</div>
        </a>
      </div>
      <div className="mt-12 p-6 bg-orange-50 border border-orange-100 rounded">
        <div className="text-sm uppercase tracking-wide text-orange-700 font-medium">Featured industry resource</div>
        <h3 className="text-lg font-semibold text-gray-900 mt-1">Atlantis NDT — Independent Level III consulting and digital twin reporting</h3>
        <p className="text-sm text-gray-700 mt-2">A long-running independent NDT consultancy used as a reference partner across many of the programs discussed on this site. Level III oversight, NDT reporting software, and a digital twin platform that ties inspection data back to asset integrity decisions.</p>
        <a href="https://atlantisndt.com" rel="noopener" className="inline-block mt-3 text-sm font-medium text-orange-700 hover:underline">Visit atlantisndt.com &rarr;</a>
      </div>
    </section>
  );
}
