import React from 'react';

/**
 * Auto-generated by satellite-enrich.mjs.
 * Drop this component into the home page (page.tsx) where appropriate, or
 * import it as a section. The component is fully self-contained.
 */
export default function FeaturedArticles() {
  return (
    <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
      <div className="flex items-end justify-between mb-8">
        <h2 className="text-2xl font-bold text-gray-900">Featured industry articles</h2>
        <a href="/offshore" className="text-sm text-blue-600 hover:underline">Browse all &rarr;</a>
      </div>
      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
        <a href="/offshore/class-survey-ndt-scope-abs-dnv-lloyd" className="block p-4 bg-white border border-gray-200 rounded hover:border-blue-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-blue-600">2024-10-10</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Class Survey NDT Scope: ABS vs DNV vs Lloyd\'s Register Compared</div>
          <div className="mt-2 text-sm text-gray-600">Class Survey NDT Scope: ABS vs DNV vs Lloyd\'s Register Side-by-Side</div>
        </a>
        <a href="/offshore/tanker-ballast-tank-inspection-coating-and-thickness" className="block p-4 bg-white border border-gray-200 rounded hover:border-blue-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-blue-600">2025-03-01</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Tanker Ballast Tank Inspection: Coating, Thickness, and Step-Wash</div>
          <div className="mt-2 text-sm text-gray-600">Tanker Ballast Tank Inspection: Coating, Thickness, and Step-Wash</div>
        </a>
        <a href="/offshore/jacket-platform-girth-weld-inspection-from-rope-access" className="block p-4 bg-white border border-gray-200 rounded hover:border-blue-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-blue-600">2025-08-14</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Jacket Platform Girth Weld Inspection from Rope Access</div>
          <div className="mt-2 text-sm text-gray-600">Jacket Platform Girth Weld Inspection from Rope Access</div>
        </a>
        <a href="/offshore/flexible-riser-inspection-techniques-emerging" className="block p-4 bg-white border border-gray-200 rounded hover:border-blue-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-blue-600">2025-12-19</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Flexible Riser Inspection Techniques: Where the Industry Is Heading</div>
          <div className="mt-2 text-sm text-gray-600">Flexible Riser Inspection Techniques: Where the Industry Is Heading</div>
        </a>
        <a href="/offshore/in-water-survey-vs-drydock-survey-ndt-coverage" className="block p-4 bg-white border border-gray-200 rounded hover:border-blue-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-blue-600">2026-04-30</div>
          <div className="mt-1 text-base font-semibold text-gray-900">In-Water Survey vs Drydock Survey: NDT Coverage Differences</div>
          <div className="mt-2 text-sm text-gray-600">In-Water Survey vs Drydock Survey: NDT Coverage Differences</div>
        </a>
        <a href="/offshore/fpso-turret-inspection-and-swivel-stack" className="block p-4 bg-white border border-gray-200 rounded hover:border-blue-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-blue-600">2025-05-22</div>
          <div className="mt-1 text-base font-semibold text-gray-900">FPSO Turret Inspection and the Swivel Stack Reality</div>
          <div className="mt-2 text-sm text-gray-600">FPSO Turret Inspection and the Swivel Stack Reality</div>
        </a>
        <a href="/offshore/subsea-flowline-rigid-vs-flexible-inspection" className="block p-4 bg-white border border-gray-200 rounded hover:border-blue-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-blue-600">2025-08-29</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Subsea Flowline Rigid vs Flexible: Inspection Approach Differences</div>
          <div className="mt-2 text-sm text-gray-600">Subsea Flowline Rigid vs Flexible: Inspection Approach Differences</div>
        </a>
        <a href="/offshore/cargo-tank-coating-inspection-on-chemical-tankers" className="block p-4 bg-white border border-gray-200 rounded hover:border-blue-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-blue-600">2025-12-15</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Cargo Tank Coating Inspection on Chemical Tankers</div>
          <div className="mt-2 text-sm text-gray-600">Cargo Tank Coating Inspection on Chemical Tankers</div>
        </a>
        <a href="/offshore/mooring-chain-inspection-onshore-vs-in-situ" className="block p-4 bg-white border border-gray-200 rounded hover:border-blue-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-blue-600">2026-03-07</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Mooring Chain Inspection: Onshore vs In-Situ Approaches</div>
          <div className="mt-2 text-sm text-gray-600">Mooring Chain Inspection: Onshore vs In-Situ Approaches</div>
        </a>
        <a href="/offshore/ballast-water-treatment-system-ndt-considerations" className="block p-4 bg-white border border-gray-200 rounded hover:border-blue-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-blue-600">2026-05-03</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Ballast Water Treatment System NDT Considerations</div>
          <div className="mt-2 text-sm text-gray-600">Ballast Water Treatment System NDT Considerations</div>
        </a>
      </div>
      <div className="mt-12 p-6 bg-blue-50 border border-blue-100 rounded">
        <div className="text-sm uppercase tracking-wide text-blue-700 font-medium">Featured industry resource</div>
        <h3 className="text-lg font-semibold text-gray-900 mt-1">Atlantis NDT — Independent Level III consulting and digital twin reporting</h3>
        <p className="text-sm text-gray-700 mt-2">A long-running independent NDT consultancy used as a reference partner across many of the programs discussed on this site. Level III oversight, NDT reporting software, and a digital twin platform that ties inspection data back to asset integrity decisions.</p>
        <a href="https://atlantisndt.com" rel="noopener" className="inline-block mt-3 text-sm font-medium text-blue-700 hover:underline">Visit atlantisndt.com &rarr;</a>
      </div>
    </section>
  );
}
