/**
 * CompliancePage — one renderer for every regime-driven compliance page.
 * ─────────────────────────────────────────────────────────────────────────────
 * Same arrangement as DepthPage, and for the same reason. The pages are DATA in
 * src/data/compliance-pages.json, generated by scripts/build-compliance-pages
 * .mjs from the researched regime store, and this component is the only thing
 * that renders them for humans.
 *
 * IMPORTANT: crawlers never execute this. scripts/prerender.mjs writes the
 * static HTML from the same JSON, and that is the layer that decides whether we
 * get cited. Both layers must stay in step — see memory:
 * prerender-is-the-only-layer-crawlers-see.
 *
 * WHY THIS COMPONENT EXISTS AT ALL: the compliance pages could have shipped
 * prerender-only, like the 234 existing training routes. They serve correctly on
 * a direct hit from search either way. But the catch-all route renders NotFound
 * for any path React does not know, so a visitor CLICKING through from
 * /consulting to a compliance page inside the SPA would have hit a 404 on a page
 * that demonstrably exists. At this family's size that is a real defect, not an
 * edge case.
 */
import { useLocation } from "react-router-dom";
import { Link } from "react-router-dom";
import { SEOHead } from "@/components/SEOHead";
import { Navigation } from "@/components/Navigation";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import AnswerBlock from "@/components/citation/AnswerBlock";
import DecompositionTable from "@/components/citation/DecompositionTable";
import { FacetSection, AuthorByline } from "@/components/citation/FacetSection";
import NotFound from "@/pages/NotFound";
import compliancePages from "@/data/compliance-pages.json";

export interface CompliancePageData {
  slug: string;
  kind: string;
  title: string;
  description: string;
  h1: string;
  answer: string;
  expansion: string;
  source: string;
  table: { caption: string; columns: string[]; rows: string[][]; note?: string };
  facets: { q: string; a: string }[];
  sections: { heading: string; paragraphs: string[]; items?: string[] }[];
  related: { to: string; label: string }[];
}

const PAGES = compliancePages as unknown as CompliancePageData[];
const BY_SLUG = new Map(PAGES.map((p) => [p.slug, p]));

export default function CompliancePage() {
  const { pathname } = useLocation();
  // Trailing slashes are 308-redirected at the edge, but normalise anyway so an
  // in-app link with a stray slash resolves rather than falling to NotFound.
  const key = pathname.replace(/\/+$/, "") || "/";
  const page = BY_SLUG.get(key);

  if (!page) return <NotFound />;

  return (
    <div className="min-h-screen bg-white">
      <SEOHead
        title={page.title}
        description={page.description}
        canonical={`https://atlantisndt.com${page.slug}`}
        faq={page.facets.map((f) => ({ question: f.q, answer: f.a }))}
      />
      <Navigation />
      <Breadcrumbs />

      <main>
        <header className="bg-gradient-to-br from-slate-900 to-slate-800 text-white py-14">
          <div className="max-w-4xl mx-auto px-4">
            <h1 className="text-3xl md:text-4xl font-bold mb-4">{page.h1}</h1>
            <p className="text-slate-300 text-lg">{page.description}</p>
          </div>
        </header>

        <div className="max-w-4xl mx-auto px-4 py-10 space-y-12">
          <AnswerBlock answer={page.answer} expansion={page.expansion} source={page.source} />

          <AuthorByline />

          <DecompositionTable
            caption={page.table.caption}
            columns={page.table.columns}
            rows={page.table.rows}
            note={page.table.note}
          />

          {page.sections.map((s, i) => (
            <section key={i} className="prose prose-slate max-w-none">
              <h2>{s.heading}</h2>
              {s.paragraphs?.map((p, j) => (
                <p key={j}>{p}</p>
              ))}
              {s.items && s.items.length > 0 && (
                <ul>
                  {s.items.map((it, j) => (
                    <li key={j}>{it}</li>
                  ))}
                </ul>
              )}
            </section>
          ))}

          <div className="mt-12 border-t border-slate-200 dark:border-slate-800 pt-8">
            {page.facets.map((f, i) => (
              <FacetSection key={i} question={f.q} answer={f.a} />
            ))}
          </div>

          {page.related?.length > 0 && (
            <nav aria-label="Related pages" className="border-t border-slate-200 pt-8">
              <h2 className="text-lg font-semibold mb-3">Related</h2>
              <ul className="grid gap-2 sm:grid-cols-2">
                {page.related.map((r) => (
                  <li key={r.to}>
                    <Link to={r.to} className="text-blue-700 hover:underline">
                      {r.label}
                    </Link>
                  </li>
                ))}
              </ul>
            </nav>
          )}
        </div>
      </main>
    </div>
  );
}
