// Exam-prep inbound block (2026-09-29). Renders the same HTML that
// scripts/training-gap-routes-2026-09-29.mjs appends for crawlers, for the
// hubs and the practice-question / study-guide pages listed in
// src/data/training-gap-inbound.json (generated by scripts/training-gap/build.mjs).
import inbound from "@/data/training-gap-inbound.json";

const MAP = inbound as Record<string, string>;

export default function TrainingGapInbound({ path }: { path: string }) {
  const html = MAP[path.replace(/\/+$/, "") || "/"];
  if (!html) return null;
  return (
    <section className="container mx-auto px-6 py-10 max-w-4xl">
      <div
        className="prose prose-lg max-w-none prose-headings:font-bold prose-a:text-primary rounded-lg border border-slate-200 bg-slate-50 p-6"
        dangerouslySetInnerHTML={{ __html: html }}
      />
    </section>
  );
}
