import React from 'react';

/**
 * Auto-generated by satellite-enrich.mjs.
 * Drop this component into the home page (page.tsx) where appropriate, or
 * import it as a section. The component is fully self-contained.
 */
export default function FeaturedArticles() {
  return (
    <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
      <div className="flex items-end justify-between mb-8">
        <h2 className="text-2xl font-bold text-gray-900">Featured industry articles</h2>
        <a href="/guides" className="text-sm text-sky-600 hover:underline">Browse all &rarr;</a>
      </div>
      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
        <a href="/guides/cryogenic-tank-inspection-9-percent-nickel-steel" className="block p-4 bg-white border border-gray-200 rounded hover:border-sky-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-sky-600">2024-08-16</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Cryogenic Tank Inspection: 9% Nickel Steel and Its Inspection Quirks</div>
          <div className="mt-2 text-sm text-gray-600">Cryogenic Tank Inspection: 9% Nickel Steel and Its Inspection Quirks</div>
        </a>
        <a href="/guides/lng-loading-arm-inspection-program" className="block p-4 bg-white border border-gray-200 rounded hover:border-sky-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-sky-600">2025-01-14</div>
          <div className="mt-1 text-base font-semibold text-gray-900">LNG Loading Arm Inspection Program: From Pin to Swivel</div>
          <div className="mt-2 text-sm text-gray-600">LNG Loading Arm Inspection Program: From Pin to Swivel</div>
        </a>
        <a href="/guides/lng-piping-weld-acceptance-criteria" className="block p-4 bg-white border border-gray-200 rounded hover:border-sky-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-sky-600">2025-06-30</div>
          <div className="mt-1 text-base font-semibold text-gray-900">LNG Piping Weld Acceptance Criteria: ASME B31.3 in Cold Service</div>
          <div className="mt-2 text-sm text-gray-600">LNG Piping Weld Acceptance Criteria: ASME B31.3 in Cold Service</div>
        </a>
        <a href="/guides/small-scale-lng-asset-integrity-program" className="block p-4 bg-white border border-gray-200 rounded hover:border-sky-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-sky-600">2025-11-21</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Small-Scale LNG Asset Integrity: Building a Program Without Refinery Resources</div>
          <div className="mt-2 text-sm text-gray-600">Small-Scale LNG Asset Integrity: Building a Program Without Refinery Resources</div>
        </a>
        <a href="/guides/bog-compressor-inspection-and-monitoring" className="block p-4 bg-white border border-gray-200 rounded hover:border-sky-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-sky-600">2026-04-09</div>
          <div className="mt-1 text-base font-semibold text-gray-900">BOG Compressor Inspection and Vibration Monitoring on LNG Trains</div>
          <div className="mt-2 text-sm text-gray-600">BOG Compressor Inspection and Vibration Monitoring on LNG Trains</div>
        </a>
      </div>
      <div className="mt-12 p-6 bg-sky-50 border border-sky-100 rounded">
        <div className="text-sm uppercase tracking-wide text-sky-700 font-medium">Featured industry resource</div>
        <h3 className="text-lg font-semibold text-gray-900 mt-1">Atlantis NDT — Independent Level III consulting and digital twin reporting</h3>
        <p className="text-sm text-gray-700 mt-2">A long-running independent NDT consultancy used as a reference partner across many of the programs discussed on this site. Level III oversight, NDT reporting software, and a digital twin platform that ties inspection data back to asset integrity decisions.</p>
        <a href="https://atlantisndt.com" rel="noopener" className="inline-block mt-3 text-sm font-medium text-sky-700 hover:underline">Visit atlantisndt.com &rarr;</a>
      </div>
    </section>
  );
}
