import React from 'react';

/**
 * Auto-generated by satellite-enrich.mjs.
 * Drop this component into the home page (page.tsx) where appropriate, or
 * import it as a section. The component is fully self-contained.
 */
export default function FeaturedArticles() {
  return (
    <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
      <div className="flex items-end justify-between mb-8">
        <h2 className="text-2xl font-bold text-gray-900">Featured industry articles</h2>
        <a href="/practices" className="text-sm text-zinc-600 hover:underline">Browse all &rarr;</a>
      </div>
      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
        <a href="/practices/inline-ut-on-tube-mills-defect-detection" className="block p-4 bg-white border border-gray-200 rounded hover:border-zinc-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-zinc-600">2024-09-23</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Inline UT on Tube Mills: What Production Defect Detection Actually Catches</div>
          <div className="mt-2 text-sm text-gray-600">Inline UT on Tube Mills: What Production Defect Detection Actually Catches</div>
        </a>
        <a href="/practices/casting-radiography-acceptance-by-grade" className="block p-4 bg-white border border-gray-200 rounded hover:border-zinc-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-zinc-600">2025-02-15</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Casting Radiography Acceptance by Grade: ASTM E446 vs E186 vs E280</div>
          <div className="mt-2 text-sm text-gray-600">Casting Radiography Acceptance by Grade: ASTM E446 vs E186 vs E280</div>
        </a>
        <a href="/practices/supplier-quality-audit-ndt-shop" className="block p-4 bg-white border border-gray-200 rounded hover:border-zinc-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-zinc-600">2025-07-26</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Supplier Quality Audit of an NDT Shop: A 50-Item Checklist</div>
          <div className="mt-2 text-sm text-gray-600">Supplier Quality Audit of an NDT Shop: A 50-Item Checklist</div>
        </a>
        <a href="/practices/additive-manufactured-parts-ndt-cap-cct-vs-ut" className="block p-4 bg-white border border-gray-200 rounded hover:border-zinc-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-zinc-600">2025-12-12</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Additive Manufactured Parts NDT: CT vs UT vs PAUT for AM Inspection</div>
          <div className="mt-2 text-sm text-gray-600">Additive Manufactured Parts NDT: CT vs UT vs PAUT for AM Inspection</div>
        </a>
        <a href="/practices/in-process-quality-control-vs-final-ndt-trade-offs" className="block p-4 bg-white border border-gray-200 rounded hover:border-zinc-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-zinc-600">2026-04-23</div>
          <div className="mt-1 text-base font-semibold text-gray-900">In-Process Quality Control vs Final NDT: Where to Spend the Budget</div>
          <div className="mt-2 text-sm text-gray-600">In-Process Quality Control vs Final NDT: Where to Spend the Budget</div>
        </a>
      </div>
      <div className="mt-12 p-6 bg-zinc-50 border border-zinc-100 rounded">
        <div className="text-sm uppercase tracking-wide text-zinc-700 font-medium">Featured industry resource</div>
        <h3 className="text-lg font-semibold text-gray-900 mt-1">Atlantis NDT — Independent Level III consulting and digital twin reporting</h3>
        <p className="text-sm text-gray-700 mt-2">A long-running independent NDT consultancy used as a reference partner across many of the programs discussed on this site. Level III oversight, NDT reporting software, and a digital twin platform that ties inspection data back to asset integrity decisions.</p>
        <a href="https://atlantisndt.com" rel="noopener" className="inline-block mt-3 text-sm font-medium text-zinc-700 hover:underline">Visit atlantisndt.com &rarr;</a>
      </div>
    </section>
  );
}
