import React from 'react';

/**
 * Auto-generated by satellite-enrich.mjs.
 * Drop this component into the home page (page.tsx) where appropriate, or
 * import it as a section. The component is fully self-contained.
 */
export default function FeaturedArticles() {
  return (
    <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
      <div className="flex items-end justify-between mb-8">
        <h2 className="text-2xl font-bold text-gray-900">Featured industry articles</h2>
        <a href="/blog" className="text-sm text-blue-600 hover:underline">Browse all &rarr;</a>
      </div>
      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
        <a href="/blog/risk-based-inspection-vs-time-based-which-cuts-cost-more" className="block p-4 bg-white border border-gray-200 rounded hover:border-blue-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-blue-600">2024-09-30</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Risk-Based Inspection vs Time-Based Inspection: Which Cuts Cost More?</div>
          <div className="mt-2 text-sm text-gray-600">Risk-Based Inspection vs Time-Based: Which Cuts Cost More?</div>
        </a>
        <a href="/blog/building-an-asset-integrity-management-system-12-month-roadmap" className="block p-4 bg-white border border-gray-200 rounded hover:border-blue-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-blue-600">2025-01-15</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Building an Asset Integrity Management System: A 12-Month Roadmap</div>
          <div className="mt-2 text-sm text-gray-600">Building an Asset Integrity Management System: A 12-Month Roadmap</div>
        </a>
        <a href="/blog/fitness-for-service-api-579-when-to-use-which-level" className="block p-4 bg-white border border-gray-200 rounded hover:border-blue-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-blue-600">2025-05-22</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Fitness-for-Service (API 579): When to Use Level 1, 2, or 3 Assessment</div>
          <div className="mt-2 text-sm text-gray-600">Fitness-for-Service (API 579): When to Use Level 1, 2, or 3</div>
        </a>
        <a href="/blog/measuring-asset-integrity-kpis-that-actually-matter" className="block p-4 bg-white border border-gray-200 rounded hover:border-blue-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-blue-600">2025-10-04</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Measuring Asset Integrity: KPIs That Actually Matter</div>
          <div className="mt-2 text-sm text-gray-600">Measuring Asset Integrity: KPIs That Actually Matter</div>
        </a>
        <a href="/blog/integrity-operating-windows-ow-best-practices-refineries" className="block p-4 bg-white border border-gray-200 rounded hover:border-blue-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-blue-600">2026-02-11</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Integrity Operating Windows (IOWs): Best Practices for Refineries</div>
          <div className="mt-2 text-sm text-gray-600">Integrity Operating Windows (IOWs): Best Practices for Refineries</div>
        </a>
        <a href="/blog/damage-mechanism-review-dmr-step-by-step" className="block p-4 bg-white border border-gray-200 rounded hover:border-blue-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-blue-600">2025-05-22</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Damage Mechanism Review (DMR): Step-by-Step for Refining Units</div>
          <div className="mt-2 text-sm text-gray-600">Damage Mechanism Review (DMR): Step-by-Step for Refining Units</div>
        </a>
        <a href="/blog/inspection-data-quality-when-it-quietly-fails-rbi" className="block p-4 bg-white border border-gray-200 rounded hover:border-blue-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-blue-600">2025-09-09</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Inspection Data Quality: When It Quietly Fails Your RBI Model</div>
          <div className="mt-2 text-sm text-gray-600">Inspection Data Quality: When It Quietly Fails Your RBI Model</div>
        </a>
        <a href="/blog/turnaround-readiness-review-30-day-window" className="block p-4 bg-white border border-gray-200 rounded hover:border-blue-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-blue-600">2025-12-21</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Turnaround Readiness Review: What Matters in the Final 30-Day Window</div>
          <div className="mt-2 text-sm text-gray-600">Turnaround Readiness Review: What Matters in the Final 30-Day Window</div>
        </a>
        <a href="/blog/integrity-management-software-pitfalls-buyers-miss" className="block p-4 bg-white border border-gray-200 rounded hover:border-blue-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-blue-600">2026-03-04</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Integrity Management Software: Five Pitfalls Buyers Almost Always Miss</div>
          <div className="mt-2 text-sm text-gray-600">Integrity Management Software: Five Pitfalls Buyers Almost Always Miss</div>
        </a>
        <a href="/blog/closing-the-loop-from-ndt-finding-to-integrity-action" className="block p-4 bg-white border border-gray-200 rounded hover:border-blue-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-blue-600">2026-05-09</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Closing the Loop: From an NDT Finding to a Recorded Integrity Action</div>
          <div className="mt-2 text-sm text-gray-600">Closing the Loop: From an NDT Finding to a Recorded Integrity Action</div>
        </a>
      </div>
      <div className="mt-12 p-6 bg-blue-50 border border-blue-100 rounded">
        <div className="text-sm uppercase tracking-wide text-blue-700 font-medium">Featured industry resource</div>
        <h3 className="text-lg font-semibold text-gray-900 mt-1">Atlantis NDT — Independent Level III consulting and digital twin reporting</h3>
        <p className="text-sm text-gray-700 mt-2">A long-running independent NDT consultancy used as a reference partner across many of the programs discussed on this site. Level III oversight, NDT reporting software, and a digital twin platform that ties inspection data back to asset integrity decisions.</p>
        <a href="https://atlantisndt.com" rel="noopener" className="inline-block mt-3 text-sm font-medium text-blue-700 hover:underline">Visit atlantisndt.com &rarr;</a>
      </div>
    </section>
  );
}
