import ErpIndustryPage from '@/components/ErpIndustryPage';
const data = {
  "slug": "ndt-inspection-companies",
  "name": "NDT Inspection Companies",
  "title": "ERP Software for NDT Inspection Companies",
  "h1": "ERP for NDT Inspection Service Companies",
  "desc": "Purpose-built ERP for non-destructive testing (NDT) inspection service providers. ASNT, ISO 9712, PCN, API 510/570/653 certification tracking, work-order management, corrosion data trending, inspection report generation, and multi-client compliance dashboards.",
  "intro": "An NDT inspection service company is a unique kind of business. You ship intellectual property (a signed inspection report) generated by certified personnel using calibrated equipment, executed against codes that change every two years, billed to dozens of clients with overlapping but contradictory quality requirements. Generic ERP software (SAP Business One, NetSuite, Microsoft Dynamics) does not understand any of this. Atlantis NDT ERP was built specifically for NDT inspection companies — by an ASNT Level III who has run an NDT business and felt every pain point.",
  "modules": [
    "certification-tracking",
    "work-order-management",
    "inspection-scheduling",
    "asset-management",
    "corrosion-tracking",
    "quality-management",
    "document-control",
    "inventory-management"
  ],
  "regs": [
    "ASNT SNT-TC-1A / CP-189 / ACCP",
    "ISO 9712:2021",
    "PCN GEN",
    "CSWIP 3.1 / 3.2 / 3.3",
    "AWS QC1",
    "NAS-410 Rev 5",
    "API ICP — 510 / 570 / 580 / 653",
    "ASME Section V",
    "ASME Section VIII Division 1",
    "ASME B31.3",
    "ISO 9001:2015",
    "ISO/IEC 17025:2017",
    "AS9100D"
  ],
  "operators": [
    "Saudi Aramco — SAEP-1142",
    "ADNOC — ACS-01",
    "QatarEnergy — NFPS",
    "Shell — DEP",
    "BP — ETP / GIS",
    "ExxonMobil — GP",
    "Chevron — CC-CHV",
    "TotalEnergies — TGS / GS-PVV",
    "Petronas — PTS",
    "Reliance — RIL Quality"
  ],
  "pain": [
    "Spreadsheets tracking 50+ technician certifications across multiple schemes — always 2 months behind reality",
    "Manual API 510 / 570 / 653 inspection interval tracking — frequent missed due dates",
    "Word / Excel report templates per client — hours wasted on formatting",
    "No corrosion-rate trending — engineers re-calculate from scratch each inspection",
    "Multi-client compliance dashboards built ad-hoc by office admin — not auditable"
  ],
  "faqs": [
    [
      "What makes a 'purpose-built NDT ERP' different from generic ERP like NetSuite or SAP?",
      "Generic ERPs are designed for accounting, inventory, and order processing — none of which require knowledge of API 510, ASNT, or radiography. Atlantis NDT ERP includes the inspection-specific functions: certification expiry tracking against ASNT / ISO 9712 / PCN / CSWIP schemes natively, inspection scheduling per API 510/570/653 code intervals, corrosion-rate calculation per API methodology, RBI per API 581, and report templates that match the dozen API formats your customers expect. A generic ERP would require 6–18 months of custom development to achieve a fraction of this."
    ],
    [
      "Does it work for a 5-person NDT shop or only large multinationals?",
      "Both. Atlantis NDT ERP is delivered as a multi-tenant SaaS — a 5-person NDT contractor pays a small monthly subscription and uses the same platform as a 500-person inspection multinational. The data model and feature set scale with the customer; you only pay for the seats and modules you need. Typical NDT-shop pricing starts at $300/month for a 3-user package."
    ],
    [
      "Can it manage Saudi Aramco SAEP-1142 / ADNOC ACS-01 / Petronas PTS qualification schemes?",
      "Yes. Major-operator qualification schemes are configured natively: Saudi Aramco SAEP-1112 / SAEP-1142, ADNOC Company Standards (ACS), QatarEnergy NFPS, Shell DEP, BP ETP, Petronas PTS, and others are pre-loaded with their scope-of-work, qualification-prerequisite, and renewal-cycle definitions. Each technician carries a qualification matrix showing all current operator-approved scopes."
    ],
    [
      "How does it integrate with our existing CMMS (Maximo, SAP PM, AspenTech APM)?",
      "Bi-directional REST API integration. The CMMS owns the equipment register and work-order origination; Atlantis NDT ERP receives the work orders and adds the inspection-specific layer (method, technician qualification matching, inspection plan, code-specific report). Inspection completion data + as-found wall thickness flow back to the CMMS to update equipment condition."
    ],
    [
      "What about deployment in confidential / air-gapped environments — defense, nuclear, refining?",
      "On-premise deployment is supported for customers requiring air-gap separation from public networks. The same product runs inside the customer's data center with no outbound dependencies. Customer-managed encryption keys, customer-managed identity (LDAP / Active Directory / SAML), and customer-managed backup are standard."
    ]
  ]
};
export default function ErpIndustry_ndt_inspection_companies() { return <ErpIndustryPage {...data} />; }
