import React from 'react';

/**
 * Auto-generated by satellite-enrich.mjs.
 * Drop this component into the home page (page.tsx) where appropriate, or
 * import it as a section. The component is fully self-contained.
 */
export default function FeaturedArticles() {
  return (
    <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
      <div className="flex items-end justify-between mb-8">
        <h2 className="text-2xl font-bold text-gray-900">Featured industry articles</h2>
        <a href="/deepdives" className="text-sm text-violet-600 hover:underline">Browse all &rarr;</a>
      </div>
      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
        <a href="/deepdives/paut-vs-tofd-when-to-combine" className="block p-4 bg-white border border-gray-200 rounded hover:border-violet-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-violet-600">2024-10-14</div>
          <div className="mt-1 text-base font-semibold text-gray-900">PAUT vs TOFD: When to Combine vs When to Pick One</div>
          <div className="mt-2 text-sm text-gray-600">PAUT vs TOFD: When to Combine vs When to Pick One</div>
        </a>
        <a href="/deepdives/guided-wave-screening-program-design" className="block p-4 bg-white border border-gray-200 rounded hover:border-violet-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-violet-600">2025-02-22</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Guided Wave Screening Program Design for Long Pipelines</div>
          <div className="mt-2 text-sm text-gray-600">Guided Wave Screening Program Design for Long Pipelines</div>
        </a>
        <a href="/deepdives/eddy-current-array-for-heat-exchanger-tubes" className="block p-4 bg-white border border-gray-200 rounded hover:border-violet-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-violet-600">2025-08-09</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Eddy Current Array for Heat Exchanger Tubes: A Field Workflow</div>
          <div className="mt-2 text-sm text-gray-600">Eddy Current Array for Heat Exchanger Tubes: A Field Workflow</div>
        </a>
        <a href="/deepdives/digital-radiography-cr-vs-dr-which-system" className="block p-4 bg-white border border-gray-200 rounded hover:border-violet-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-violet-600">2025-11-26</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Digital Radiography: CR vs DR — Which System Fits Which Site?</div>
          <div className="mt-2 text-sm text-gray-600">Digital Radiography: CR vs DR — Which System Fits Which Site?</div>
        </a>
        <a href="/deepdives/automated-ut-scanner-deployment-2026" className="block p-4 bg-white border border-gray-200 rounded hover:border-violet-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-violet-600">2026-04-08</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Automated UT Scanner Deployment: A 2026 Playbook</div>
          <div className="mt-2 text-sm text-gray-600">Automated UT Scanner Deployment: A 2026 Playbook</div>
        </a>
        <a href="/deepdives/full-matrix-capture-fmc-tfm-when-it-justifies-its-cost" className="block p-4 bg-white border border-gray-200 rounded hover:border-violet-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-violet-600">2025-05-27</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Full Matrix Capture (FMC) / TFM: When It Justifies Its Cost</div>
          <div className="mt-2 text-sm text-gray-600">Full Matrix Capture (FMC) / TFM: When It Justifies Its Cost</div>
        </a>
        <a href="/deepdives/low-frequency-eddy-current-thick-aluminum-and-clad" className="block p-4 bg-white border border-gray-200 rounded hover:border-violet-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-violet-600">2025-09-25</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Low-Frequency Eddy Current for Thick Aluminum and Clad Components</div>
          <div className="mt-2 text-sm text-gray-600">Low-Frequency Eddy Current for Thick Aluminum and Clad Components</div>
        </a>
        <a href="/deepdives/industrial-ct-scanning-buyers-mindset" className="block p-4 bg-white border border-gray-200 rounded hover:border-violet-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-violet-600">2025-12-23</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Industrial CT Scanning: A Buyer\'s Mindset for 2026</div>
          <div className="mt-2 text-sm text-gray-600">Industrial CT Scanning: A Buyer\'s Mindset for 2026</div>
        </a>
        <a href="/deepdives/electromagnetic-acoustic-transducer-emat-realistic-uses" className="block p-4 bg-white border border-gray-200 rounded hover:border-violet-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-violet-600">2026-03-06</div>
          <div className="mt-1 text-base font-semibold text-gray-900">EMAT Transducers: Realistic Uses Beyond the Sales Pitch</div>
          <div className="mt-2 text-sm text-gray-600">EMAT Transducers: Realistic Uses Beyond the Sales Pitch</div>
        </a>
        <a href="/deepdives/time-of-flight-diffraction-tofd-on-thin-wall-pipe" className="block p-4 bg-white border border-gray-200 rounded hover:border-violet-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-violet-600">2026-05-14</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Time-of-Flight Diffraction (TOFD) on Thin-Wall Pipe: Where It Struggles</div>
          <div className="mt-2 text-sm text-gray-600">Time-of-Flight Diffraction (TOFD) on Thin-Wall Pipe: Where It Struggles</div>
        </a>
      </div>
      <div className="mt-12 p-6 bg-violet-50 border border-violet-100 rounded">
        <div className="text-sm uppercase tracking-wide text-violet-700 font-medium">Featured industry resource</div>
        <h3 className="text-lg font-semibold text-gray-900 mt-1">Atlantis NDT — Independent Level III consulting and digital twin reporting</h3>
        <p className="text-sm text-gray-700 mt-2">A long-running independent NDT consultancy used as a reference partner across many of the programs discussed on this site. Level III oversight, NDT reporting software, and a digital twin platform that ties inspection data back to asset integrity decisions.</p>
        <a href="https://atlantisndt.com" rel="noopener" className="inline-block mt-3 text-sm font-medium text-violet-700 hover:underline">Visit atlantisndt.com &rarr;</a>
      </div>
    </section>
  );
}
