import React from 'react';

/**
 * Auto-generated by satellite-enrich.mjs.
 * Drop this component into the home page (page.tsx) where appropriate, or
 * import it as a section. The component is fully self-contained.
 */
export default function FeaturedArticles() {
  return (
    <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
      <div className="flex items-end justify-between mb-8">
        <h2 className="text-2xl font-bold text-gray-900">Featured industry articles</h2>
        <a href="/techniques" className="text-sm text-fuchsia-600 hover:underline">Browse all &rarr;</a>
      </div>
      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
        <a href="/techniques/cfrp-phased-array-vs-thermography-which-finds-disbonds" className="block p-4 bg-white border border-gray-200 rounded hover:border-fuchsia-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-fuchsia-600">2024-09-18</div>
          <div className="mt-1 text-base font-semibold text-gray-900">CFRP Phased Array vs Thermography: Which Finds Disbonds Faster?</div>
          <div className="mt-2 text-sm text-gray-600">CFRP Phased Array vs Thermography: Which Finds Disbonds Faster?</div>
        </a>
        <a href="/techniques/wind-blade-inspection-from-rope-access-to-drones" className="block p-4 bg-white border border-gray-200 rounded hover:border-fuchsia-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-fuchsia-600">2025-03-25</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Wind Blade Inspection: From Rope Access to Drones</div>
          <div className="mt-2 text-sm text-gray-600">Wind Blade Inspection: From Rope Access to Drones</div>
        </a>
        <a href="/techniques/sandwich-panel-honeycomb-core-defects-and-detection" className="block p-4 bg-white border border-gray-200 rounded hover:border-fuchsia-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-fuchsia-600">2025-08-20</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Sandwich Panel Honeycomb Core Defects and How to Detect Them</div>
          <div className="mt-2 text-sm text-gray-600">Sandwich Panel Honeycomb Core Defects and How to Detect Them</div>
        </a>
        <a href="/techniques/shearography-on-composite-pressure-vessels" className="block p-4 bg-white border border-gray-200 rounded hover:border-fuchsia-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-fuchsia-600">2025-12-15</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Shearography on Composite Pressure Vessels: When It Earns Its Keep</div>
          <div className="mt-2 text-sm text-gray-600">Shearography on Composite Pressure Vessels: When It Earns Its Keep</div>
        </a>
        <a href="/techniques/pulse-thermography-vs-lock-in-thermography-quick-decision-guide" className="block p-4 bg-white border border-gray-200 rounded hover:border-fuchsia-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-fuchsia-600">2026-04-26</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Pulse Thermography vs Lock-In Thermography: A Quick Decision Guide</div>
          <div className="mt-2 text-sm text-gray-600">Pulse Thermography vs Lock-In Thermography: A Quick Decision Guide</div>
        </a>
        <a href="/techniques/composite-bolted-joint-inspection-aerospace" className="block p-4 bg-white border border-gray-200 rounded hover:border-fuchsia-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-fuchsia-600">2025-05-16</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Composite Bolted Joint Inspection in Aerospace Structures</div>
          <div className="mt-2 text-sm text-gray-600">Composite Bolted Joint Inspection in Aerospace Structures</div>
        </a>
        <a href="/techniques/visual-inspection-of-composite-tooling-cure-defects" className="block p-4 bg-white border border-gray-200 rounded hover:border-fuchsia-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-fuchsia-600">2025-08-31</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Visual Inspection of Composite Tooling and Cure Defects</div>
          <div className="mt-2 text-sm text-gray-600">Visual Inspection of Composite Tooling and Cure Defects</div>
        </a>
        <a href="/techniques/wind-blade-trailing-edge-bond-line-inspection" className="block p-4 bg-white border border-gray-200 rounded hover:border-fuchsia-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-fuchsia-600">2025-11-27</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Wind Blade Trailing Edge Bond Line Inspection</div>
          <div className="mt-2 text-sm text-gray-600">Wind Blade Trailing Edge Bond Line Inspection</div>
        </a>
        <a href="/techniques/composite-overwrapped-pressure-vessel-copv-inspection" className="block p-4 bg-white border border-gray-200 rounded hover:border-fuchsia-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-fuchsia-600">2026-03-08</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Composite Overwrapped Pressure Vessel (COPV) Inspection Approaches</div>
          <div className="mt-2 text-sm text-gray-600">Composite Overwrapped Pressure Vessel (COPV) Inspection Approaches</div>
        </a>
        <a href="/techniques/composite-repair-patch-inspection-and-validation" className="block p-4 bg-white border border-gray-200 rounded hover:border-fuchsia-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-fuchsia-600">2026-05-03</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Composite Repair Patch Inspection and Validation</div>
          <div className="mt-2 text-sm text-gray-600">Composite Repair Patch Inspection and Validation</div>
        </a>
      </div>
      <div className="mt-12 p-6 bg-fuchsia-50 border border-fuchsia-100 rounded">
        <div className="text-sm uppercase tracking-wide text-fuchsia-700 font-medium">Featured industry resource</div>
        <h3 className="text-lg font-semibold text-gray-900 mt-1">Atlantis NDT — Independent Level III consulting and digital twin reporting</h3>
        <p className="text-sm text-gray-700 mt-2">A long-running independent NDT consultancy used as a reference partner across many of the programs discussed on this site. Level III oversight, NDT reporting software, and a digital twin platform that ties inspection data back to asset integrity decisions.</p>
        <a href="https://atlantisndt.com" rel="noopener" className="inline-block mt-3 text-sm font-medium text-fuchsia-700 hover:underline">Visit atlantisndt.com &rarr;</a>
      </div>
    </section>
  );
}
