import React from 'react';

/**
 * Auto-generated by satellite-enrich.mjs.
 * Drop this component into the home page (page.tsx) where appropriate, or
 * import it as a section. The component is fully self-contained.
 */
export default function FeaturedArticles() {
  return (
    <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
      <div className="flex items-end justify-between mb-8">
        <h2 className="text-2xl font-bold text-gray-900">Featured industry articles</h2>
        <a href="/tubes" className="text-sm text-red-600 hover:underline">Browse all &rarr;</a>
      </div>
      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
        <a href="/tubes/iris-vs-ecit-vs-rfet-tube-inspection-decision" className="block p-4 bg-white border border-gray-200 rounded hover:border-red-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-red-600">2024-10-04</div>
          <div className="mt-1 text-base font-semibold text-gray-900">IRIS vs ECT vs RFET: Tube Inspection Method Decision Matrix</div>
          <div className="mt-2 text-sm text-gray-600">IRIS vs ECT vs RFET: Tube Inspection Method Decision Matrix</div>
        </a>
        <a href="/tubes/cleaning-tubes-before-ndt-why-it-decides-everything" className="block p-4 bg-white border border-gray-200 rounded hover:border-red-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-red-600">2025-02-26</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Cleaning Tubes Before NDT: Why It Decides Everything</div>
          <div className="mt-2 text-sm text-gray-600">Cleaning Tubes Before NDT: Why It Decides Everything</div>
        </a>
        <a href="/tubes/air-cooler-tube-bundle-inspection-program" className="block p-4 bg-white border border-gray-200 rounded hover:border-red-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-red-600">2025-07-21</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Air Cooler Tube Bundle Inspection Program: Building One That Works</div>
          <div className="mt-2 text-sm text-gray-600">Air Cooler Tube Bundle Inspection Program: Building One That Works</div>
        </a>
        <a href="/tubes/fouling-vs-corrosion-tube-signal-interpretation" className="block p-4 bg-white border border-gray-200 rounded hover:border-red-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-red-600">2025-11-30</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Fouling vs Corrosion in Tube Signals: How to Tell Them Apart</div>
          <div className="mt-2 text-sm text-gray-600">Fouling vs Corrosion in Tube Signals: How to Tell Them Apart</div>
        </a>
        <a href="/tubes/plugging-vs-retubing-heat-exchanger-economics" className="block p-4 bg-white border border-gray-200 rounded hover:border-red-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-red-600">2026-04-14</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Plugging vs Retubing: The Economics of Tube Failure Response</div>
          <div className="mt-2 text-sm text-gray-600">Plugging vs Retubing: The Economics of Tube Failure Response</div>
        </a>
        <a href="/tubes/shell-and-tube-vs-plate-frame-inspection-realities" className="block p-4 bg-white border border-gray-200 rounded hover:border-red-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-red-600">2025-05-24</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Shell-and-Tube vs Plate-Frame Heat Exchanger Inspection Realities</div>
          <div className="mt-2 text-sm text-gray-600">Shell-and-Tube vs Plate-Frame Heat Exchanger Inspection Realities</div>
        </a>
        <a href="/tubes/tube-bundle-extraction-and-rebundling-decisions" className="block p-4 bg-white border border-gray-200 rounded hover:border-red-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-red-600">2025-09-16</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Tube Bundle Extraction and Rebundling: Decision Framework</div>
          <div className="mt-2 text-sm text-gray-600">Tube Bundle Extraction and Rebundling: Decision Framework</div>
        </a>
        <a href="/tubes/air-cooler-header-box-inspection-for-cracks" className="block p-4 bg-white border border-gray-200 rounded hover:border-red-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-red-600">2025-12-07</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Air Cooler Header Box Inspection for Cracks and Distortion</div>
          <div className="mt-2 text-sm text-gray-600">Air Cooler Header Box Inspection for Cracks and Distortion</div>
        </a>
        <a href="/tubes/tube-to-tubesheet-weld-inspection-techniques" className="block p-4 bg-white border border-gray-200 rounded hover:border-red-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-red-600">2026-02-21</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Tube-to-Tubesheet Weld Inspection: Methods That Hold Up to Audit</div>
          <div className="mt-2 text-sm text-gray-600">Tube-to-Tubesheet Weld Inspection: Methods That Hold Up to Audit</div>
        </a>
        <a href="/tubes/expansion-joint-inspection-on-shell-and-tube-exchangers" className="block p-4 bg-white border border-gray-200 rounded hover:border-red-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-red-600">2026-05-02</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Expansion Joint Inspection on Shell-and-Tube Exchangers</div>
          <div className="mt-2 text-sm text-gray-600">Expansion Joint Inspection on Shell-and-Tube Exchangers</div>
        </a>
      </div>
      <div className="mt-12 p-6 bg-red-50 border border-red-100 rounded">
        <div className="text-sm uppercase tracking-wide text-red-700 font-medium">Featured industry resource</div>
        <h3 className="text-lg font-semibold text-gray-900 mt-1">Atlantis NDT — Independent Level III consulting and digital twin reporting</h3>
        <p className="text-sm text-gray-700 mt-2">A long-running independent NDT consultancy used as a reference partner across many of the programs discussed on this site. Level III oversight, NDT reporting software, and a digital twin platform that ties inspection data back to asset integrity decisions.</p>
        <a href="https://atlantisndt.com" rel="noopener" className="inline-block mt-3 text-sm font-medium text-red-700 hover:underline">Visit atlantisndt.com &rarr;</a>
      </div>
    </section>
  );
}
