import React from 'react';

/**
 * Auto-generated by satellite-enrich.mjs.
 * Drop this component into the home page (page.tsx) where appropriate, or
 * import it as a section. The component is fully self-contained.
 */
export default function FeaturedArticles() {
  return (
    <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
      <div className="flex items-end justify-between mb-8">
        <h2 className="text-2xl font-bold text-gray-900">Featured industry articles</h2>
        <a href="/paths" className="text-sm text-rose-600 hover:underline">Browse all &rarr;</a>
      </div>
      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
        <a href="/paths/ndt-salary-by-method-and-region-2026" className="block p-4 bg-white border border-gray-200 rounded hover:border-rose-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-rose-600">2024-08-09</div>
          <div className="mt-1 text-base font-semibold text-gray-900">NDT Salary by Method and Region: A 2026 Snapshot</div>
          <div className="mt-2 text-sm text-gray-600">NDT Salary by Method and Region (2026 Snapshot)</div>
        </a>
        <a href="/paths/transitioning-from-welder-to-ndt-inspector" className="block p-4 bg-white border border-gray-200 rounded hover:border-rose-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-rose-600">2025-01-08</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Transitioning From Welder to NDT Inspector: A Practical Roadmap</div>
          <div className="mt-2 text-sm text-gray-600">Transitioning From Welder to NDT Inspector: A Practical Roadmap</div>
        </a>
        <a href="/paths/remote-ndt-jobs-are-they-real" className="block p-4 bg-white border border-gray-200 rounded hover:border-rose-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-rose-600">2025-05-29</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Remote NDT Jobs: Are They Real?</div>
          <div className="mt-2 text-sm text-gray-600">Remote NDT Jobs: Are They Real?</div>
        </a>
        <a href="/paths/offshore-vs-onshore-ndt-careers-financial-and-lifestyle" className="block p-4 bg-white border border-gray-200 rounded hover:border-rose-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-rose-600">2025-10-15</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Offshore vs Onshore NDT Careers: Financial and Lifestyle Trade-Offs</div>
          <div className="mt-2 text-sm text-gray-600">Offshore vs Onshore NDT Careers: Financial and Lifestyle Trade-Offs</div>
        </a>
        <a href="/paths/building-a-level-iii-consulting-practice" className="block p-4 bg-white border border-gray-200 rounded hover:border-rose-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-rose-600">2026-03-30</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Building a Level III Consulting Practice: From Salaried to Self-Employed</div>
          <div className="mt-2 text-sm text-gray-600">Building a Level III Consulting Practice: From Salaried to Self-Employed</div>
        </a>
        <a href="/paths/ndt-resume-templates-that-actually-pass-screening" className="block p-4 bg-white border border-gray-200 rounded hover:border-rose-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-rose-600">2025-05-12</div>
          <div className="mt-1 text-base font-semibold text-gray-900">NDT Resume Templates That Actually Pass Recruiter Screening</div>
          <div className="mt-2 text-sm text-gray-600">NDT Resume Templates That Actually Pass Recruiter Screening</div>
        </a>
        <a href="/paths/interviewing-for-an-ndt-supervisor-role" className="block p-4 bg-white border border-gray-200 rounded hover:border-rose-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-rose-600">2025-09-06</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Interviewing for an NDT Supervisor Role: What the Hiring Manager Looks For</div>
          <div className="mt-2 text-sm text-gray-600">Interviewing for an NDT Supervisor Role: What the Hiring Manager Looks For</div>
        </a>
        <a href="/paths/side-income-options-for-a-working-ndt-inspector" className="block p-4 bg-white border border-gray-200 rounded hover:border-rose-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-rose-600">2025-12-03</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Side Income Options for a Working NDT Inspector</div>
          <div className="mt-2 text-sm text-gray-600">Side Income Options for a Working NDT Inspector</div>
        </a>
        <a href="/paths/mid-career-pivot-from-field-ndt-to-software" className="block p-4 bg-white border border-gray-200 rounded hover:border-rose-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-rose-600">2026-02-23</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Mid-Career Pivot from Field NDT to NDT Software</div>
          <div className="mt-2 text-sm text-gray-600">Mid-Career Pivot from Field NDT to NDT Software</div>
        </a>
        <a href="/paths/visa-and-relocation-for-international-ndt-work" className="block p-4 bg-white border border-gray-200 rounded hover:border-rose-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-rose-600">2026-05-05</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Visa and Relocation Pathways for International NDT Work</div>
          <div className="mt-2 text-sm text-gray-600">Visa and Relocation Pathways for International NDT Work</div>
        </a>
      </div>
      <div className="mt-12 p-6 bg-rose-50 border border-rose-100 rounded">
        <div className="text-sm uppercase tracking-wide text-rose-700 font-medium">Featured industry resource</div>
        <h3 className="text-lg font-semibold text-gray-900 mt-1">Atlantis NDT — Independent Level III consulting and digital twin reporting</h3>
        <p className="text-sm text-gray-700 mt-2">A long-running independent NDT consultancy used as a reference partner across many of the programs discussed on this site. Level III oversight, NDT reporting software, and a digital twin platform that ties inspection data back to asset integrity decisions.</p>
        <a href="https://atlantisndt.com" rel="noopener" className="inline-block mt-3 text-sm font-medium text-rose-700 hover:underline">Visit atlantisndt.com &rarr;</a>
      </div>
    </section>
  );
}
