import React from 'react';

/**
 * Auto-generated by satellite-enrich.mjs.
 * Drop this component into the home page (page.tsx) where appropriate, or
 * import it as a section. The component is fully self-contained.
 */
export default function FeaturedArticles() {
  return (
    <section className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
      <div className="flex items-end justify-between mb-8">
        <h2 className="text-2xl font-bold text-gray-900">Featured industry articles</h2>
        <a href="/curriculum" className="text-sm text-indigo-600 hover:underline">Browse all &rarr;</a>
      </div>
      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-4">
        <a href="/curriculum/designing-a-level-ii-ut-course-syllabus" className="block p-4 bg-white border border-gray-200 rounded hover:border-indigo-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-indigo-600">2024-09-09</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Designing a Level II UT Course Syllabus That Actually Prepares Students</div>
          <div className="mt-2 text-sm text-gray-600">Designing a Level II UT Course Syllabus That Actually Prepares Students</div>
        </a>
        <a href="/curriculum/practical-vs-theory-hours-snt-tc-1a-vs-cp-189" className="block p-4 bg-white border border-gray-200 rounded hover:border-indigo-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-indigo-600">2025-02-18</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Practical vs Theory Hours: SNT-TC-1A vs CP-189</div>
          <div className="mt-2 text-sm text-gray-600">Practical vs Theory Hours: SNT-TC-1A vs CP-189</div>
        </a>
        <a href="/curriculum/building-an-ndt-school-business-model" className="block p-4 bg-white border border-gray-200 rounded hover:border-indigo-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-indigo-600">2025-07-12</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Building an NDT School: Business Model and Curriculum Choices</div>
          <div className="mt-2 text-sm text-gray-600">Building an NDT School: Business Model and Curriculum Choices</div>
        </a>
        <a href="/curriculum/online-vs-in-person-ndt-courses-where-each-wins" className="block p-4 bg-white border border-gray-200 rounded hover:border-indigo-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-indigo-600">2025-11-25</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Online vs In-Person NDT Courses: Where Each Format Wins</div>
          <div className="mt-2 text-sm text-gray-600">Online vs In-Person NDT Courses: Where Each Format Wins</div>
        </a>
        <a href="/curriculum/eye-exam-jaeger-near-vision-ndt-acceptance" className="block p-4 bg-white border border-gray-200 rounded hover:border-indigo-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-indigo-600">2026-04-06</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Eye Exam and Jaeger Near Vision: What the NDT Standards Require</div>
          <div className="mt-2 text-sm text-gray-600">Eye Exam and Jaeger Near Vision: What the NDT Standards Require</div>
        </a>
        <a href="/curriculum/designing-a-paut-level-ii-practical-program" className="block p-4 bg-white border border-gray-200 rounded hover:border-indigo-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-indigo-600">2025-05-11</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Designing a PAUT Level II Practical Program That Produces Field-Ready Inspectors</div>
          <div className="mt-2 text-sm text-gray-600">Designing a PAUT Level II Practical Program That Produces Field-Ready Inspectors</div>
        </a>
        <a href="/curriculum/mt-and-pt-practical-stations-for-classroom-courses" className="block p-4 bg-white border border-gray-200 rounded hover:border-indigo-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-indigo-600">2025-09-19</div>
          <div className="mt-1 text-base font-semibold text-gray-900">MT and PT Practical Stations for Classroom Courses</div>
          <div className="mt-2 text-sm text-gray-600">MT and PT Practical Stations for Classroom Courses</div>
        </a>
        <a href="/curriculum/how-to-write-an-snt-tc-1a-employer-written-practice" className="block p-4 bg-white border border-gray-200 rounded hover:border-indigo-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-indigo-600">2025-12-17</div>
          <div className="mt-1 text-base font-semibold text-gray-900">How to Write an SNT-TC-1A Employer Written Practice</div>
          <div className="mt-2 text-sm text-gray-600">How to Write an SNT-TC-1A Employer Written Practice</div>
        </a>
        <a href="/curriculum/scheduling-and-tracking-on-the-job-training-hours" className="block p-4 bg-white border border-gray-200 rounded hover:border-indigo-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-indigo-600">2026-03-18</div>
          <div className="mt-1 text-base font-semibold text-gray-900">Scheduling and Tracking On-the-Job Training Hours for NDT Candidates</div>
          <div className="mt-2 text-sm text-gray-600">Scheduling and Tracking On-the-Job Training Hours for NDT Candidates</div>
        </a>
        <a href="/curriculum/pcn-vs-cswip-vs-asnt-for-european-students" className="block p-4 bg-white border border-gray-200 rounded hover:border-indigo-500 hover:shadow transition">
          <div className="text-xs uppercase tracking-wide text-indigo-600">2026-05-08</div>
          <div className="mt-1 text-base font-semibold text-gray-900">PCN vs CSWIP vs ASNT for European NDT Students</div>
          <div className="mt-2 text-sm text-gray-600">PCN vs CSWIP vs ASNT for European NDT Students</div>
        </a>
      </div>
      <div className="mt-12 p-6 bg-indigo-50 border border-indigo-100 rounded">
        <div className="text-sm uppercase tracking-wide text-indigo-700 font-medium">Featured industry resource</div>
        <h3 className="text-lg font-semibold text-gray-900 mt-1">Atlantis NDT — Independent Level III consulting and digital twin reporting</h3>
        <p className="text-sm text-gray-700 mt-2">A long-running independent NDT consultancy used as a reference partner across many of the programs discussed on this site. Level III oversight, NDT reporting software, and a digital twin platform that ties inspection data back to asset integrity decisions.</p>
        <a href="https://atlantisndt.com" rel="noopener" className="inline-block mt-3 text-sm font-medium text-indigo-700 hover:underline">Visit atlantisndt.com &rarr;</a>
      </div>
    </section>
  );
}
