import ErpIndustryAppPage from "@/components/ErpIndustryAppPage";

export default function HrPayrollForGeotechnicalEngineering() {
  return (
    <ErpIndustryAppPage
      pageTitle="HR & Payroll for Geotechnical Engineering Firms"
      slug="hr-payroll-for-geotechnical-engineering"
      appName="HR & Payroll"
      industry="geotechnical engineering"
      breadcrumbLabel="HR & Payroll for Geotechnical Firms"
      trustBadge="ASCE / GEO / PE / GBC compliance"
      metaDescription="Atlantis NDT ERP HR & Payroll for geotechnical engineering firms. Professional Engineer license tracking, field-technician certification (NICET, ACI, AASHTO), multi-state PE registration, FIFO crew payroll. regional pricing flat."
      heroBody="Atlantis NDT ERP HR & Payroll pre-configured for geotechnical engineering firms — Professional Engineer (PE) license tracking with multi-state registration management, NICET / ACI / AASHTO field-technician certifications, FIFO crew payroll with prevailing wage compliance, Davis-Bacon Act records for federally-funded projects, multi-currency payroll for international geotechnical consultancies, and ASCE / Geo-Institute / DFI / ADSC membership tracking. Part of the all-apps-included subscription."
      whatItIs={[
        "HR & Payroll for Geotechnical Engineering inside Atlantis NDT ERP is the Odoo 18 HR + Payroll + Time-Tracking module pre-configured for the operating reality of geotechnical engineering firms — site investigation contractors, foundation-design engineers, retaining-wall and earth-retention specialists, slope-stability consultants, dam-engineering practices, tunnel-engineering firms, ground-improvement specialists, geotechnical instrumentation contractors and earthquake-engineering practices. The system manages every license, certification and qualification required to keep a geotechnical engineering practice operating legally and bidding competitively: state-by-state Professional Engineer (PE) licensure (NCEES Council Record, individual state-board renewal cycles, continuing-education credits per state), Specialty Engineering registrations (Geotechnical Engineering specialty in CA, TX, OR, WA), Authorized Inspector / Special Inspector qualifications (NCEES ICC ES, IAS AC172), and field-technician credentials (NICET Levels I-IV in Geotechnical Construction Materials Testing, ACI Concrete Field-Testing Technician Grade I, AASHTO/ASCE Field Inspector Certifications).",
        "Every employee record tracks: PE license number per state with expiry dates and continuing-education credit hours per state's specific requirement (NY 36 PDH per 3 years, CA 16 PDH per 2 years, TX 15 PDH per year, FL 18 PDH per 2 years), NCEES Council Record currency for fast multi-state mobility, specialty Geotechnical Engineering (GE) credentials, Geotechnical Engineering Society memberships (ASCE Geo-Institute, DFI, ADSC, ISSMGE), continuing-education courses (auto-tracked from NCEES, ASCE, DFI, ASEC PE Continuing Education providers), and current-project assignments to ensure no employee is over-allocated across federally-funded projects with conflict-of-interest rules. Field-technician records track NICET (National Institute for Certification in Engineering Technologies) credentials, ACI Field-Testing Technician credentials, ATSSA (American Traffic Safety Services Association) flagger certification, OSHA 10/30 hours, MSHA Part 46/48, and confined-space / fall-protection / first-aid currency.",
      ]}
      useCases={[
        { useCase: "Use Case 1", body: "A Houston-based geotechnical engineering firm (35 PEs across 12 states, 60 field technicians) tracks multi-state PE renewals automatically — eliminated 4 missed-renewal incidents per year (each typically costing $8K-$15K in project-team disruption) and saved approximately 240 hours/year of HR admin time on continuing-education tracking." },
        { useCase: "Use Case 2", body: "A Denver-based geotechnical firm (28 PEs, 45 field staff) serving FHWA / WSDOT / CDOT / UDOT federally-funded highway projects manages Davis-Bacon Act prevailing-wage compliance, WH-347 weekly certified-payroll submission, and DBE (Disadvantaged Business Enterprise) participation tracking — cleared next DOT FHWA audit with zero non-conformances." },
        { useCase: "Use Case 3", body: "A Calgary-based geotechnical firm (22 P.Eng across Alberta + BC + Saskatchewan, 35 field technicians) supporting oil-sands tailings dam, pipeline-right-of-way and SAGD operations tracks APEGA / EGBC / APEGS professional registration, CGSB 48.9712 NDT currency, and CCO Common Core Operations safety training — cleared next APEGA continuing-competence audit with zero remediation actions." },
        { useCase: "Use Case 4", body: "A Dubai-based geotechnical engineering firm (18 chartered engineers, 30 site technicians) serving ADNOC Onshore foundation work, Etihad Rail subgrade design, Hyperloop Dubai-Abu Dhabi alignment and Dubai Metro extension uses bilingual English/Arabic payroll, end-of-service-benefit (EOSB) gratuity calculations per UAE Labour Law Article 132, and multi-emirate work-permit tracking across DM, RTA, ADQCC and SCAD jurisdictions." },
      ]}
      keyFeatures={[
        "Multi-state Professional Engineer (PE) license tracking with state-specific CE requirements",
        "NCEES Council Record currency for rapid multi-state mobility",
        "Specialty Geotechnical Engineering (GE) credential management",
        "NICET / ACI / AASHTO field-technician certification database",
        "Davis-Bacon Act prevailing-wage compliance with WH-347 submission",
        "DBE (Disadvantaged Business Enterprise) participation tracking",
        "Multi-state payroll tax compliance (50 states + DC + territories)",
        "FIFO / per-diem / mobilization payroll with IRS Publication 463 substantiation",
        "OSHA 10 / 30 / Confined Space / Fall Protection / MSHA Part 46/48 currency",
        "Field-time-capture from mobile app with GPS verification",
        "International multi-currency payroll (UAE EOSB, KSA EOSB, India PF/ESI/Gratuity, Canada CPP/EI)",
        "ASCE / Geo-Institute / DFI / ADSC membership renewals",
        "Continuing-education automatic credit import from NCEES / ASCE provider feeds",
        "Subconsultant 1099 / TDS / WHT compliance",
      ]}
      integrations={[
        "NCEES Council Record API integration for multi-state PE verification",
        "ASCE Continuing Education Provider course completion feed",
        "NICET certification verification portal",
        "ACI certification database lookup",
        "Department of Labor WH-347 prevailing-wage electronic submission",
        "FHWA / state DOT certified payroll portals",
        "ADP / Paychex / Gusto US-payroll feed integration",
        "Tally Prime / RazorpayX / GreyHR / KekaHR India HR/payroll feed",
        "Bayzat / Mercans / Sage 300 People UAE / KSA payroll integration",
        "Ceridian Dayforce / Ultimate Software / Workday HCM integration",
      ]}
      faqs={[
        { question: "How does multi-state PE license tracking work?", answer: "Each Professional Engineer in your firm typically holds licenses in multiple US states — geotechnical firms operating regionally (e.g. a Texas-based firm bidding work in OK, LA, NM, AR, MS, FL) need to track 3-12 state licenses per engineer with state-specific renewal cycles, continuing-education credit-hour requirements, ethics-course requirements, and laws-and-rules course requirements. Atlantis NDT ERP supports per-state license records with expiry alerts (180 / 90 / 30 days), state-specific CE-credit-hour tracking with bucket-by-category (technical, ethics, laws-and-rules), NCEES Council Record currency for fast comity processing, and automatic suspension of an engineer from state-specific project teams when their state-specific license expires." },
        { question: "Does the system handle Davis-Bacon Act prevailing-wage compliance?", answer: "Yes. Davis-Bacon Act compliance on federally-funded construction projects (FHWA highway projects, Army Corps of Engineers projects, FAA airport projects, federal-aid public-housing projects) requires weekly submission of WH-347 certified payroll with prevailing-wage-rate evidence per Wage Determination, fringe-benefit-rate documentation, and DOL/state-DOT enforcement-action defensibility. Atlantis NDT ERP supports: per-project Wage Determination assignment, automatic prevailing-wage-rate enforcement per Davis-Bacon Act job classification, fringe-benefit-rate substitution rules (per Davis-Bacon Related Acts), WH-347 electronic submission per 29 CFR 5.5(a)(3)(ii)(C), and DBE participation tracking for federally-funded projects." },
        { question: "How does NICET / ACI / AASHTO field-technician certification work?", answer: "Field technicians require credentials that differ from PE engineers: NICET (National Institute for Certification in Engineering Technologies) Levels I-IV in Construction Materials Testing — Concrete, Asphalt, Soils, Aggregates, In-Place Density; ACI (American Concrete Institute) Concrete Field-Testing Technician Grade I and Grade II, ACI Concrete Strength Testing Technician, ACI Aggregate Testing Technician; AASHTO Highway-Materials Technician credentials. State-specific overlays (TxDOT TQAS, FDOT Materials Acceptance, CalTrans Maintenance, ODOT, NYSDOT) are tracked separately. Atlantis NDT ERP maintains current-credential dashboards per technician with auto-renewal-reminder workflows." },
        { question: "Can the system handle FIFO / per-diem payroll with IRS substantiation?", answer: "Yes. Geotechnical site investigation work often requires multi-week mobilizations to remote sites — pipeline-right-of-way work, dam-engineering work, mining-engineering work, oil-sands work — under IRS Revenue Procedure 2019-48 (per-diem substantiation), IRS Publication 463 (Travel, Gift, and Car Expenses) and accountable-plan substantiation rules. Atlantis NDT ERP supports: per-diem rate-table per locality per IRS GSA tables, automatic substantiation against trip-record evidence (project location, dates, lodging receipts where required), IRS accountable-plan vs nonaccountable-plan classification, and 1099 / W-2 reporting integrity for travel-reimbursement compliance." },
        { question: "Does the system support APEGA / EGBC / APEGS Canadian professional regulation?", answer: "Yes. Canadian Professional Engineering regulation is provincial — APEGA (Alberta), EGBC (BC), APEGS (Saskatchewan), APEGM (Manitoba), PEO (Ontario), OIQ (Quebec, with title 'Ing'), APEGNB (NB), PEGNL (NL), APENS (NS), EGPEI (PEI). Each province has continuing-competence requirements (typically 240 hours over 3 years for APEGA, with 50 hours mandatory in specific categories) and specific code-of-ethics commitments. Atlantis NDT ERP supports per-province registration tracking with continuing-competence audit-pack export per APEGA / EGBC / APEGS audit cycles." },
        { question: "Can the system handle UAE / KSA end-of-service-benefit calculations?", answer: "Yes. UAE Federal Labour Law Article 132 (now superseded by Federal Decree-Law 33 of 2021) and Saudi Labor Law Article 84-87 mandate end-of-service-benefit (EOSB / gratuity) accruals for expatriate employees. Atlantis NDT ERP supports: 21-day-base salary per year for first 5 years, 30-day-base salary per year thereafter (UAE pre-2022 formula); the post-DIFC ESB scheme for DIFC-based UAE employees; KSA EOSB at half-month-base per year for first 5 years, full-month-base thereafter; expat-vs-national differential calculation; service-period tracking with leaves and unpaid-absence adjustment per UAE / KSA legal interpretation; statutory-export reporting templates for GOSI (KSA) and the new UAE MOHRE Workforce Insurance scheme." },
        { question: "How does subconsultant 1099 / TDS / WHT compliance work?", answer: "Many geotechnical firms engage independent consulting engineers as 1099 contractors (US) or subject-to-TDS-Withholding contractors (India) or WHT-withheld contractors (other jurisdictions). Atlantis NDT ERP supports: US 1099-NEC reporting for independent contractor payments above $600/year per IRS Section 6041A, W-9 / W-8BEN / W-8BEN-E foreign-contractor classification, India Section 194J TDS Withholding for professional services, UAE / KSA / Qatar WHT (Withholding Tax) on cross-border professional-service payments, OECD CRS (Common Reporting Standard) compliance for international contractor banking, and per-contractor banking-detail security with PCI-DSS-compliant payment-credentials handling." },
        { question: "Is the system suitable for multi-currency international payroll?", answer: "Yes. Geotechnical engineering firms with international operations need parallel payroll across home-country (e.g. USD-based US firm) and host-country (e.g. AED-based UAE branch, INR-based India branch, CAD-based Canada branch, SAR-based KSA branch). Atlantis NDT ERP supports: per-employee home-country / host-country split-payroll, multi-currency journal entries with monthly FX revaluation, expat-package allowance management (housing, cost-of-living, hardship, hazard, education, repatriation), tax-equalization calculation, hypothetical-tax accrual, host-country-statutory-pay (e.g. UAE EOSB, India PF / ESI / Gratuity, Saudi GOSI), and consolidation to home-country reporting at month-end." },
      ]}
    />
  );
}
